import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { ServiceOffering } from '../service-offerings/service-offerings.js';
import type { ServiceExposure, ServiceExposureRepository, ServiceExposureStatus } from './service-exposures.js';

export class PostgresServiceExposureRepository implements ServiceExposureRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async find(id: string) { return exposure(await this.database.query('SELECT exposure.id,exposure.service_offering_id,exposure.provider_doctor_profile_id,exposure.provider_clinic_id,exposure.tenant_id,exposure.status FROM service_exposures exposure WHERE exposure.id=$1', [id])); }
  public async findDoctorOwnedOffering(offeringId: string, accountId: string) { return offering(await this.database.query('SELECT offering.id,offering.owner_doctor_profile_id,offering.owner_clinic_id,NULL::uuid AS tenant_id,offering.name,offering.description,offering.status FROM service_offerings offering JOIN doctor_profiles doctor ON doctor.id=offering.owner_doctor_profile_id WHERE offering.id=$1 AND doctor.account_id=$2', [offeringId, accountId])); }
  public async findOffering(offeringId: string) { return offering(await this.database.query('SELECT offering.id,offering.owner_doctor_profile_id,offering.owner_clinic_id,clinic.tenant_id,offering.name,offering.description,offering.status FROM service_offerings offering LEFT JOIN clinics clinic ON clinic.id=offering.owner_clinic_id WHERE offering.id=$1', [offeringId])); }
  public async create(database: PostgresExecutor, value: ServiceExposure, actor: string) { await database.query('INSERT INTO service_exposures (id,service_offering_id,provider_doctor_profile_id,provider_clinic_id,tenant_id,status,created_by_account_id,updated_by_account_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$7)', [value.id,value.serviceOfferingId,value.provider.kind === 'DOCTOR' ? value.provider.doctorProfileId : null,value.provider.kind === 'CLINIC' ? value.provider.clinicId : null,value.provider.kind === 'CLINIC' ? value.provider.tenantId : null,value.status,actor]); }
  public async transition(database: PostgresExecutor, exposureId: string, from: ServiceExposureStatus, to: ServiceExposureStatus, actor: string) { return exposure(await database.query('UPDATE service_exposures SET status=$3,updated_by_account_id=$4,updated_at=current_timestamp WHERE id=$1 AND status=$2 RETURNING id,service_offering_id,provider_doctor_profile_id,provider_clinic_id,tenant_id,status', [exposureId,from,to,actor])); }
}

function offering(result: { rows: unknown[] }): ServiceOffering | null { const row=result.rows[0] as Record<string, unknown> | undefined; return row ? {id:String(row.id),owner:row.owner_doctor_profile_id ? {kind:'DOCTOR',doctorProfileId:String(row.owner_doctor_profile_id)} : {kind:'CLINIC',clinicId:String(row.owner_clinic_id),tenantId:String(row.tenant_id)},name:String(row.name),description:row.description === null ? null : String(row.description),status:row.status as ServiceOffering['status']} : null; }
function exposure(result: { rows: unknown[] }): ServiceExposure | null { const row=result.rows[0] as Record<string, unknown> | undefined; return row ? {id:String(row.id),serviceOfferingId:String(row.service_offering_id),provider:row.provider_doctor_profile_id ? {kind:'DOCTOR',doctorProfileId:String(row.provider_doctor_profile_id)} : {kind:'CLINIC',clinicId:String(row.provider_clinic_id),tenantId:String(row.tenant_id)},status:row.status as ServiceExposureStatus} : null; }
