import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { AuditEventInput } from '../audit/audit.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { MedicationItem, Prescription, PrescriptionAccess, PrescriptionItemInput, PrescriptionRepository } from './appointment-prescriptions.js';

export class PostgresAppointmentPrescriptionRepository implements PrescriptionRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async access(appointmentId: string) { return access((await this.database.query<Record<string, unknown>>(queryAccess(), [appointmentId])).rows[0]); }
  public async lockAccess(db: PostgresExecutor, appointmentId: string) { return access((await db.query<Record<string, unknown>>(`${queryAccess()} FOR UPDATE OF a`, [appointmentId])).rows[0]); }
  public async ownsPatient(db: PostgresExecutor, accountId: string, profileId: string) { return (await db.query('SELECT 1 FROM patient_profiles WHERE id=$1 AND account_id=$2', [profileId, accountId])).rowCount === 1; }
  public async ownsDoctor(db: PostgresExecutor, accountId: string, profileId: string) { return (await db.query('SELECT 1 FROM doctor_profiles WHERE id=$1 AND account_id=$2', [profileId, accountId])).rowCount === 1; }
  public async find(db: PostgresExecutor, appointmentId: string) { const row=(await db.query<Record<string,unknown>>('SELECT id,appointment_id,patient_profile_id,doctor_profile_id,status,created_by_account_id,create_request_fingerprint,created_at,updated_at,draft_version,issued_at,issued_by_account_id,final_snapshot,final_snapshot_hash FROM prescriptions WHERE appointment_id=$1',[appointmentId])).rows[0]; if(!row)return null; return { ...prescription(row), items:(await db.query<Record<string,unknown>>('SELECT id,position,medicine_name,strength,dosage,frequency,duration,route,quantity,instructions FROM prescription_items WHERE prescription_id=$1 ORDER BY position,id',[row.id])).rows.map(item) }; }
  public async findByCreateKey(db: PostgresExecutor, accountId: string, key: string) { const row=(await db.query<{appointment_id:string}>('SELECT appointment_id FROM prescriptions WHERE created_by_account_id=$1 AND create_idempotency_key=$2',[accountId,key])).rows[0]; return row ? this.find(db,row.appointment_id) : null; }
  public async findByIssueKey(db: PostgresExecutor, accountId: string, key: string) { const row=(await db.query<{appointment_id:string}>('SELECT appointment_id FROM prescriptions WHERE issued_by_account_id=$1 AND issue_idempotency_key=$2',[accountId,key])).rows[0]; return row ? this.find(db,row.appointment_id) : null; }
  public async create(db: PostgresExecutor, value: Prescription & {createIdempotencyKey:string;createRequestFingerprint:string}) { await db.query("INSERT INTO prescriptions (id,appointment_id,patient_profile_id,doctor_profile_id,status,created_by_account_id,created_at,updated_at,draft_version,create_idempotency_key,create_request_fingerprint) VALUES ($1,$2,$3,$4,'DRAFT',$5,$6,$6,1,$7,$8)",[value.id,value.appointmentId,value.patientProfileId,value.doctorProfileId,value.createdByAccountId,value.createdAt,value.createIdempotencyKey,value.createRequestFingerprint]); }
  public async replaceItems(db: PostgresExecutor, id: string, items: PrescriptionItemInput[]) { await db.query('DELETE FROM prescription_items WHERE prescription_id=$1',[id]); for(const item of items) await db.query('INSERT INTO prescription_items (id,prescription_id,position,medicine_name,strength,dosage,frequency,duration,route,quantity,instructions) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[createIdentifier(),id,item.position,item.medicineName,item.strength,item.dosage,item.frequency,item.duration,item.route,item.quantity,item.instructions]); }
  public async updateDraft(db: PostgresExecutor,id:string,version:number){return (await db.query("UPDATE prescriptions SET draft_version=draft_version+1 WHERE id=$1 AND status='DRAFT' AND draft_version=$2",[id,version])).rowCount===1;}
  public async issue(db: PostgresExecutor,value:{id:string;expectedVersion:number;issuedAt:Date;issuedByAccountId:string;issueIdempotencyKey:string;issueRequestFingerprint:string;snapshot:Record<string,unknown>;hash:string}){return (await db.query("UPDATE prescriptions SET status='ISSUED',issued_at=$3,issued_by_account_id=$4,issue_idempotency_key=$5,issue_request_fingerprint=$6,final_snapshot=$7::jsonb,final_snapshot_hash=$8 WHERE id=$1 AND status='DRAFT' AND draft_version=$2",[value.id,value.expectedVersion,value.issuedAt,value.issuedByAccountId,value.issueIdempotencyKey,value.issueRequestFingerprint,JSON.stringify(value.snapshot),value.hash])).rowCount===1;}
  public async appendAudit(db:PostgresExecutor,event:AuditEventInput){await db.query('INSERT INTO audit_events (id,category,event_type,actor_account_id,tenant_id,target_type,target_id,outcome,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[createIdentifier(),event.category,event.eventType,event.actorAccountId??null,event.tenantId??null,event.targetType,event.targetId??null,event.outcome,JSON.stringify(event.metadata??{})]);}
}
function queryAccess(){return "SELECT a.id,a.status,p.patient_profile_id,d.doctor_profile_id FROM appointments a JOIN appointment_participants p ON p.appointment_id=a.id AND p.participant_type='PATIENT' JOIN appointment_participants d ON d.appointment_id=a.id AND d.participant_type='DOCTOR' WHERE a.id=$1";}
function access(row:Record<string,unknown>|undefined):PrescriptionAccess|null{return row?{appointmentId:String(row.id),status:String(row.status),patientProfileId:String(row.patient_profile_id),doctorProfileId:String(row.doctor_profile_id)}:null;}
function prescription(row:Record<string,unknown>):Omit<Prescription,'items'>{return{id:String(row.id),appointmentId:String(row.appointment_id),patientProfileId:String(row.patient_profile_id),doctorProfileId:String(row.doctor_profile_id),status:row.status as Prescription['status'],createdByAccountId:String(row.created_by_account_id),createRequestFingerprint:String(row.create_request_fingerprint),createdAt:new Date(String(row.created_at)),updatedAt:new Date(String(row.updated_at)),draftVersion:Number(row.draft_version),issuedAt:row.issued_at?new Date(String(row.issued_at)):null,issuedByAccountId:row.issued_by_account_id?String(row.issued_by_account_id):null,finalSnapshot:row.final_snapshot as Record<string,unknown>|null,finalSnapshotHash:row.final_snapshot_hash?String(row.final_snapshot_hash):null};}
function item(row:Record<string,unknown>):MedicationItem{return{id:String(row.id),position:Number(row.position),medicineName:String(row.medicine_name),strength:String(row.strength),dosage:String(row.dosage),frequency:String(row.frequency),duration:String(row.duration),route:row.route?String(row.route):null,quantity:row.quantity?String(row.quantity):null,instructions:row.instructions?String(row.instructions):null};}
