import { createHash } from 'node:crypto';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { VerifiedFirebaseIdentity } from '../identity/identity.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';

type Invitation = { id:string; targetAccountId:string; email:string; displayName:string|null; status:string; expiresAt:Date; secretHash:string };
export class DoctorInvitationAcceptanceError extends Error { public constructor(public readonly code:'FORBIDDEN'|'CONFLICT') { super(code==='FORBIDDEN'?'Doctor invitation access is not permitted.':'The doctor invitation cannot be accepted.'); } }
export interface DoctorInvitationAcceptanceRepository { transaction<T>(operation:(db:PostgresExecutor)=>Promise<T>):Promise<T>; lock(db:PostgresExecutor,id:string):Promise<Invitation|null>; identityAccount(db:PostgresExecutor, identity:VerifiedFirebaseIdentity):Promise<string|null>; linkIdentity(db:PostgresExecutor,accountId:string,identity:VerifiedFirebaseIdentity):Promise<void>; activateAccount(db:PostgresExecutor,accountId:string):Promise<void>; ensureProfile(db:PostgresExecutor,accountId:string,displayName:string|null):Promise<void>; accept(db:PostgresExecutor,id:string):Promise<boolean>; audit(db:PostgresExecutor,accountId:string,id:string):Promise<void>; }
export class DoctorInvitationAcceptanceService { public constructor(private readonly repository:DoctorInvitationAcceptanceRepository,private readonly now:()=>Date=()=>new Date()){} async accept(id:string,secret:string,identity:VerifiedFirebaseIdentity){ const email=identity.email; if(!email||identity.emailVerified!==true) throw new DoctorInvitationAcceptanceError('FORBIDDEN'); return this.repository.transaction(async(db)=>{const invitation=await this.repository.lock(db,id);if(!invitation||invitation.status!=='INVITED'||invitation.expiresAt<=this.now()||hash(secret)!==invitation.secretHash||email.trim().toLowerCase()!==invitation.email)throw new DoctorInvitationAcceptanceError('FORBIDDEN');const linked=await this.repository.identityAccount(db,identity);if(linked&&linked!==invitation.targetAccountId)throw new DoctorInvitationAcceptanceError('FORBIDDEN');if(!linked)await this.repository.linkIdentity(db,invitation.targetAccountId,identity);await this.repository.activateAccount(db,invitation.targetAccountId);await this.repository.ensureProfile(db,invitation.targetAccountId,invitation.displayName);if(!await this.repository.accept(db,id))throw new DoctorInvitationAcceptanceError('CONFLICT');await this.repository.audit(db,invitation.targetAccountId,id);});} }
function hash(value:string){return createHash('sha256').update(value).digest('base64url');}
export { createIdentifier };
