import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import { newApprovalId, type DiscoveryReadinessService, type DiscoveryReadinessSubject, type PublicDiscoveryControlRepository } from './public-discovery-control.js';

export class PostgresPublicDiscoveryControlRepository implements PublicDiscoveryControlRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async subjectExists(kind: 'CLINIC' | 'DOCTOR', id: string) { return (await this.database.query(kind === 'CLINIC' ? 'SELECT 1 FROM clinics WHERE id=$1' : 'SELECT 1 FROM doctor_profiles WHERE id=$1', [id])).rowCount === 1; }
  public async readyExposureCount(kind: 'CLINIC' | 'DOCTOR', id: string) { const provider = kind === 'CLINIC' ? 'exposure.provider_clinic_id=$1' : 'exposure.provider_doctor_profile_id=$1'; const subject = kind === 'CLINIC' ? "JOIN clinics clinic ON clinic.id=exposure.provider_clinic_id AND clinic.status='ACTIVE' JOIN tenants tenant ON tenant.id=clinic.tenant_id AND tenant.status='ACTIVE'" : "JOIN doctor_profiles doctor ON doctor.id=exposure.provider_doctor_profile_id AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED'"; const result = await this.database.query<{ count: string }>(`SELECT count(*)::text AS count FROM service_exposures exposure ${subject} JOIN service_offerings offering ON offering.id=exposure.service_offering_id AND offering.status='ACTIVE' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE exposure.status='PUBLISHED' AND ${provider}`, [id]); return Number(result.rows[0]?.count ?? 0); }
  public async readinessSubject(kind: 'CLINIC' | 'DOCTOR', id: string): Promise<DiscoveryReadinessSubject | null> { const result = await this.database.query<Record<string, unknown>>(kind === 'CLINIC' ? 'SELECT clinic.status,tenant.status AS tenant_status FROM clinics clinic LEFT JOIN tenants tenant ON tenant.id=clinic.tenant_id WHERE clinic.id=$1' : 'SELECT doctor.status,doctor.professional_verification_status FROM doctor_profiles doctor WHERE doctor.id=$1', [id]); const row = result.rows[0]; return row ? { status: String(row.status), tenantStatus: row.tenant_status === null || row.tenant_status === undefined ? null : String(row.tenant_status), professionalVerificationStatus: row.professional_verification_status === null || row.professional_verification_status === undefined ? null : String(row.professional_verification_status) } : null; }
  public async readinessServices(kind: 'CLINIC' | 'DOCTOR', id: string): Promise<DiscoveryReadinessService[]> { const provider = kind === 'CLINIC' ? 'exposure.provider_clinic_id=offering.owner_clinic_id' : 'exposure.provider_doctor_profile_id=offering.owner_doctor_profile_id'; const owner = kind === 'CLINIC' ? 'offering.owner_clinic_id=$1' : 'offering.owner_doctor_profile_id=$1'; const result = await this.database.query<Record<string, unknown>>(`SELECT offering.id AS service_id,offering.name AS service_name,offering.status AS service_status,version.status AS version_status,availability.status AS availability_status,exposure.id AS exposure_id,exposure.status AS exposure_status FROM service_offerings offering LEFT JOIN LATERAL (SELECT status,id FROM service_offering_versions version WHERE version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) ORDER BY version.effective_from DESC LIMIT 1) version ON true LEFT JOIN availability_configurations availability ON availability.service_offering_version_id=version.id LEFT JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND ${provider} WHERE ${owner} ORDER BY offering.created_at,offering.id`, [id]); return result.rows.map((row) => ({ serviceId: String(row.service_id), serviceName: String(row.service_name), serviceStatus: String(row.service_status), versionStatus: row.version_status === null ? null : String(row.version_status), versionEffective: row.version_status === 'ACTIVE', availabilityStatus: row.availability_status === null ? null : String(row.availability_status), exposureId: row.exposure_id === null ? null : String(row.exposure_id), exposureStatus: row.exposure_status === null ? null : String(row.exposure_status) })); }
  public async approvalStatus(kind: 'CLINIC' | 'DOCTOR', id: string) { const result = await this.database.query<{ status: 'PUBLISHED' | 'REVOKED' }>(kind === 'CLINIC' ? "SELECT status FROM platform_public_discovery_approvals WHERE subject_kind='CLINIC' AND clinic_id=$1" : "SELECT status FROM platform_public_discovery_approvals WHERE subject_kind='DOCTOR' AND doctor_profile_id=$1", [id]); return result.rows[0]?.status ?? null; }
  public async setApproval(database: PostgresExecutor, actorId: string, kind: 'CLINIC' | 'DOCTOR', id: string, status: 'PUBLISHED' | 'REVOKED') { const key = kind === 'CLINIC' ? 'clinic_id' : 'doctor_profile_id'; const other = kind === 'CLINIC' ? 'doctor_profile_id' : 'clinic_id'; await database.query(`INSERT INTO platform_public_discovery_approvals (id,subject_kind,${key},${other},status,published_at,revoked_at,updated_by_account_id) VALUES ($1,$2,$3,NULL,$4,CASE WHEN $4='PUBLISHED' THEN current_timestamp ELSE NULL END,CASE WHEN $4='REVOKED' THEN current_timestamp ELSE NULL END,$5) ON CONFLICT (${key}) WHERE subject_kind='${kind}' DO UPDATE SET status=EXCLUDED.status,published_at=CASE WHEN EXCLUDED.status='PUBLISHED' THEN current_timestamp ELSE platform_public_discovery_approvals.published_at END,revoked_at=CASE WHEN EXCLUDED.status='REVOKED' THEN current_timestamp ELSE NULL END,updated_at=current_timestamp,updated_by_account_id=EXCLUDED.updated_by_account_id`, [newApprovalId(), kind, id, status, actorId]); }
}
