import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { DoctorInvitation, PlatformAdminRepository, PlatformClinic, PlatformDoctor, PlatformMetrics } from './platform-admin.js';
type Database = { query: PostgresExecutor['query']; transaction<T>(operation: (database: PostgresExecutor) => Promise<T>): Promise<T> };

export class PostgresPlatformAdminRepository implements PlatformAdminRepository {
  public constructor(private readonly database: Database) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async listClinics() { return (await this.database.query<Record<string, unknown>>(`${clinicSql} ORDER BY clinic.display_name`, [])).rows.map(clinic); }
  public async findClinic(id: string) { const row = (await this.database.query<Record<string, unknown>>(`${clinicSql} WHERE clinic.id=$1`, [id])).rows[0]; return row ? clinic(row) : null; }
  public async listDoctors() { return (await this.database.query<Record<string, unknown>>(`${doctorSql} GROUP BY doctor.id ORDER BY doctor.display_name NULLS LAST,doctor.id`, [])).rows.map(doctor); }
  public async findDoctor(id: string) { const row = (await this.database.query<Record<string, unknown>>(`${doctorSql} WHERE doctor.id=$1 GROUP BY doctor.id`, [id])).rows[0]; return row ? doctor(row) : null; }
  public async listDoctorInvitations() { return (await this.database.query<Record<string, unknown>>('SELECT id,target_account_id,invited_email_normalized,display_name,status,created_at,expires_at,revoked_at,accepted_at FROM doctor_invitations ORDER BY created_at DESC', [])).rows.map(invitation); }
  public async metrics(): Promise<PlatformMetrics> { const row = (await this.database.query<Record<string, unknown>>(`SELECT (SELECT count(*)::text FROM clinics) clinics, (SELECT count(*)::text FROM doctor_profiles) doctors, (SELECT count(*)::text FROM patient_profiles) patients, ((SELECT count(*) FROM tenant_invitations WHERE status='INVITED' AND expires_at > current_timestamp) + (SELECT count(*) FROM doctor_invitations WHERE status='INVITED' AND expires_at > current_timestamp))::text active_invitations, (SELECT count(*)::text FROM appointments WHERE status='CONFIRMED' AND starts_at >= current_timestamp) upcoming_appointments`, [])).rows[0] ?? {}; return { clinics: Number(row.clinics ?? 0), doctors: Number(row.doctors ?? 0), patients: Number(row.patients ?? 0), activeInvitations: Number(row.active_invitations ?? 0), upcomingAppointments: Number(row.upcoming_appointments ?? 0) }; }
  public async createDoctorInvitation(database: PostgresExecutor, actorId: string, value: DoctorInvitation & { secretHash: string }) { await database.query("INSERT INTO accounts (id,status,created_by_account_id,updated_by_account_id) VALUES ($1,'PENDING_VERIFICATION',$2,$2)", [value.targetAccountId, actorId]); await database.query("INSERT INTO doctor_invitations (id,target_account_id,invited_email_normalized,display_name,secret_hash,status,expires_at,created_by_account_id) VALUES ($1,$2,$3,$4,$5,'INVITED',$6,$7)", [value.id, value.targetAccountId, value.email, value.displayName, value.secretHash, value.expiresAt, actorId]); }
  public async lockDoctorInvitation(database: PostgresExecutor, id: string) { const row = (await database.query<Record<string, unknown>>('SELECT id,target_account_id,invited_email_normalized,display_name,secret_hash,status,created_at,expires_at,revoked_at,accepted_at FROM doctor_invitations WHERE id=$1 FOR UPDATE', [id])).rows[0]; return row ? { ...invitation(row), secretHash: String(row.secret_hash) } : null; }
  public async revokeDoctorInvitation(database: PostgresExecutor, id: string, actorId: string) { const result = await database.query("UPDATE doctor_invitations SET status='REVOKED',revoked_at=current_timestamp,revoked_by_account_id=$2,updated_at=current_timestamp WHERE id=$1 AND status='INVITED'", [id, actorId]); if (result.rowCount !== 1) throw new Error('DOCTOR_INVITATION_REVOKE_FAILED'); }
  public async replaceDoctorInvitation(database: PostgresExecutor, actorId: string, previous: DoctorInvitation, secretHash: string) { const value: DoctorInvitation = { ...previous, id: createIdentifier(), status: 'INVITED', createdAt: new Date(), expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), revokedAt: null, acceptedAt: null }; await database.query("INSERT INTO doctor_invitations (id,target_account_id,invited_email_normalized,display_name,secret_hash,status,expires_at,created_by_account_id) VALUES ($1,$2,$3,$4,$5,'INVITED',$6,$7)", [value.id, value.targetAccountId, value.email, value.displayName, secretHash, value.expiresAt, actorId]); return value; }
  public async lockClinicForActivation(database: PostgresExecutor, id: string) { const row = (await database.query<Record<string, unknown>>('SELECT clinic.id,clinic.tenant_id,clinic.status clinic_status,tenant.status tenant_status FROM clinics clinic JOIN tenants tenant ON tenant.id=clinic.tenant_id WHERE clinic.id=$1 FOR UPDATE OF clinic,tenant', [id])).rows[0]; return row ? { id: String(row.id), tenantId: String(row.tenant_id), clinicStatus: String(row.clinic_status), tenantStatus: String(row.tenant_status) } : null; }
  public async hasActiveClinicOwner(database: PostgresExecutor, tenantId: string) { return (await database.query("SELECT membership.id FROM tenant_memberships membership JOIN accounts account ON account.id=membership.account_id WHERE membership.tenant_id=$1 AND membership.role_key='CLINIC_OWNER' AND membership.status='ACTIVE' AND account.status='ACTIVE' FOR UPDATE OF membership,account", [tenantId])).rows.length > 0; }
  public async activateClinic(database: PostgresExecutor, id: string, actorId: string) { const row = (await database.query<Record<string, unknown>>("UPDATE clinics SET status='ACTIVE',updated_at=current_timestamp,updated_by_account_id=$2 WHERE id=$1 AND status='DRAFT' RETURNING id,tenant_id,display_name,legal_name,status", [id, actorId])).rows[0]; return row ? { id: String(row.id), tenantId: String(row.tenant_id), displayName: String(row.display_name), legalName: String(row.legal_name), clinicStatus: String(row.status), tenantStatus: 'ACTIVE', ownerEmail: null, ownerMembershipStatus: 'ACTIVE', invitationStatus: null } : null; }
}
const clinicSql = `SELECT clinic.id,clinic.tenant_id,clinic.display_name,clinic.legal_name,clinic.status clinic_status,tenant.status tenant_status,owner.invited_email_normalized owner_email,membership.status owner_membership_status,owner.status invitation_status FROM clinics clinic JOIN tenants tenant ON tenant.id=clinic.tenant_id LEFT JOIN LATERAL (SELECT invitation.* FROM tenant_invitations invitation WHERE invitation.tenant_id=tenant.id AND invitation.role_key='CLINIC_OWNER' ORDER BY invitation.created_at DESC LIMIT 1) owner ON true LEFT JOIN tenant_memberships membership ON membership.tenant_id=tenant.id AND membership.role_key='CLINIC_OWNER' AND membership.account_id=owner.target_account_id`;
const doctorSql = `SELECT doctor.id,doctor.account_id,doctor.display_name,doctor.status,doctor.professional_verification_status,COALESCE(array_agg(DISTINCT clinic.display_name) FILTER (WHERE clinic.id IS NOT NULL),'{}') clinic_names FROM doctor_profiles doctor LEFT JOIN network_connections connection ON connection.connection_kind='CLINIC_DOCTOR' AND connection.status='ACCEPTED' AND connection.doctor_profile_id=doctor.id LEFT JOIN clinics clinic ON clinic.id=connection.clinic_left_id`;
function clinic(row: Record<string, unknown>): PlatformClinic { return { id: String(row.id), tenantId: String(row.tenant_id), displayName: String(row.display_name), legalName: String(row.legal_name), clinicStatus: String(row.clinic_status), tenantStatus: String(row.tenant_status), ownerEmail: row.owner_email === null ? null : String(row.owner_email), ownerMembershipStatus: row.owner_membership_status === null ? null : String(row.owner_membership_status), invitationStatus: row.invitation_status === null ? null : String(row.invitation_status) }; }
function doctor(row: Record<string, unknown>): PlatformDoctor { return { id: String(row.id), accountId: String(row.account_id), displayName: row.display_name === null ? null : String(row.display_name), status: String(row.status), professionalVerificationStatus: String(row.professional_verification_status), clinicNames: Array.isArray(row.clinic_names) ? row.clinic_names.map(String) : [] }; }
function invitation(row: Record<string, unknown>): DoctorInvitation { return { id: String(row.id), targetAccountId: String(row.target_account_id), email: String(row.invited_email_normalized), displayName: row.display_name === null ? null : String(row.display_name), status: String(row.status), createdAt: new Date(String(row.created_at)), expiresAt: new Date(String(row.expires_at)), revokedAt: row.revoked_at === null ? null : new Date(String(row.revoked_at)), acceptedAt: row.accepted_at === null ? null : new Date(String(row.accepted_at)) }; }
