import type { FastifyInstance } from 'fastify';
import { AppointmentPrescriptionService, PrescriptionError, type PrescriptionItemInput } from '../modules/prescriptions/appointment-prescriptions.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export async function registerAppointmentPrescriptionRoutes(app: FastifyInstance, dependencies: { prescriptions: AppointmentPrescriptionService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) {
  const account = async (cookie: string | undefined) => { try { return (await authenticateSession(cookie?.split(';').map((v) => v.trim()).find((v) => v.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1), dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new PrescriptionError('UNAUTHORIZED'); } };
  const appointmentId = (request: { params: unknown }) => typeof (request.params as { appointmentId?: unknown }).appointmentId === 'string' ? (request.params as { appointmentId: string }).appointmentId : '';
  const guard = (error: unknown) => { if (error instanceof PrescriptionError) throw Object.assign(error, { code: error.code }); throw error; };
  const items = (value: unknown): PrescriptionItemInput[] => { if (!Array.isArray(value)) throw new PrescriptionError('CONFLICT'); return value as PrescriptionItemInput[]; };
  app.post('/v1/appointments/:appointmentId/prescription', async (request) => { try { const body = request.body as { idempotencyKey?: unknown; items?: unknown }; if (typeof body?.idempotencyKey !== 'string') throw new PrescriptionError('CONFLICT'); return await dependencies.prescriptions.create(await account(request.headers.cookie), appointmentId(request), { idempotencyKey: body.idempotencyKey, items: body.items === undefined ? [] : items(body.items) }); } catch (error) { return guard(error); } });
  app.get('/v1/appointments/:appointmentId/prescription', async (request) => { try { return await dependencies.prescriptions.get(await account(request.headers.cookie), appointmentId(request)); } catch (error) { return guard(error); } });
  app.patch('/v1/appointments/:appointmentId/prescription', async (request) => { try { const body = request.body as { expectedDraftVersion?: unknown; items?: unknown }; if (!Number.isInteger(body?.expectedDraftVersion)) throw new PrescriptionError('CONFLICT'); return await dependencies.prescriptions.update(await account(request.headers.cookie), appointmentId(request), { expectedDraftVersion: body.expectedDraftVersion as number, items: items(body.items) }); } catch (error) { return guard(error); } });
  app.post('/v1/appointments/:appointmentId/prescription/issue', async (request) => { try { const body = request.body as { idempotencyKey?: unknown }; if (typeof body?.idempotencyKey !== 'string') throw new PrescriptionError('CONFLICT'); return await dependencies.prescriptions.issue(await account(request.headers.cookie), appointmentId(request), body.idempotencyKey); } catch (error) { return guard(error); } });
}
