import type { FastifyInstance } from 'fastify';
import { AvailabilityError, type AvailabilityInput, type AvailabilityService } from '../modules/availability/availability.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export async function registerAvailabilityRoutes(app: FastifyInstance, dependencies: { availability: AvailabilityService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }): Promise<void> {
  app.post('/v1/service-offering-versions/:versionId/availability', async (request, reply) => reply.code(201).send(await dependencies.availability.create(await account(request.headers.cookie, dependencies), (request.params as { versionId: string }).versionId, input(request.body))));
  app.get('/v1/service-offering-versions/:versionId/availability', async (request) => dependencies.availability.read(await account(request.headers.cookie, dependencies), (request.params as { versionId: string }).versionId));
}
async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { const value = header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1); return (await authenticateSession(value, dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new AvailabilityError('UNAUTHORIZED'); } }
function input(value: unknown): AvailabilityInput {
  const body = value as Record<string, unknown>; const rules = Array.isArray(body?.rules) ? body.rules.map((rule) => { const item = rule as Record<string, unknown>; if (typeof item.recurrence !== 'string' || typeof item.effectiveFrom !== 'string' || (item.effectiveTo !== undefined && item.effectiveTo !== null && typeof item.effectiveTo !== 'string') || !Array.isArray(item.windows)) throw new AvailabilityError('CONFLICT'); return { recurrence: item.recurrence, effectiveFrom: new Date(item.effectiveFrom), effectiveTo: item.effectiveTo ? new Date(String(item.effectiveTo)) : null, windows: item.windows.map((itemValue: unknown) => itemValue) }; }) : null;
  const exceptions = body?.exceptions === undefined ? [] : Array.isArray(body.exceptions) ? body.exceptions.map((exception) => { const item = exception as Record<string, unknown>; if (!['HOLIDAY', 'LEAVE', 'BLOCKED', 'ONE_OFF'].includes(String(item.kind)) || typeof item.localStart !== 'string' || typeof item.localEnd !== 'string') throw new AvailabilityError('CONFLICT'); return { kind: item.kind as 'HOLIDAY' | 'LEAVE' | 'BLOCKED' | 'ONE_OFF', localStart: item.localStart, localEnd: item.localEnd }; }) : null;
  if (!rules || !exceptions || typeof body.providerTimezone !== 'string' || !numbers(body.slotDurationSeconds, body.bufferBeforeSeconds, body.bufferAfterSeconds, body.capacity, body.bookingLeadTimeSeconds, body.bookingHorizonSeconds)) throw new AvailabilityError('CONFLICT');
  return { providerTimezone: body.providerTimezone, slotDurationSeconds: body.slotDurationSeconds as number, bufferBeforeSeconds: body.bufferBeforeSeconds as number, bufferAfterSeconds: body.bufferAfterSeconds as number, capacity: body.capacity as number, bookingLeadTimeSeconds: body.bookingLeadTimeSeconds as number, bookingHorizonSeconds: body.bookingHorizonSeconds as number, rules: rules as AvailabilityInput['rules'], exceptions: exceptions as AvailabilityInput['exceptions'] };
}
function numbers(...values: unknown[]) { return values.every((value) => typeof value === 'number' && Number.isInteger(value)); }
