import type { FastifyInstance } from 'fastify';
import { DelegatedBookingError, type DelegatedAuthorizationInput, type DelegatedBookingInput, type DelegatedBookingService } from '../modules/appointments/delegated-bookings.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export async function registerDelegatedBookingRoutes(app: FastifyInstance, dependencies: { bookings: DelegatedBookingService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }): Promise<void> {
  app.post('/v1/delegated-booking-authorizations', async (request, reply) => reply.code(201).send(await dependencies.bookings.authorize(await account(request.headers.cookie, dependencies), authorizationInput(request.body))));
  app.post('/v1/delegated-booking-authorizations/:authorizationId/revoke', async (request, reply) => { await dependencies.bookings.revoke(await account(request.headers.cookie, dependencies), (request.params as { authorizationId: string }).authorizationId); return reply.code(204).send(); });
  app.post('/v1/delegated-bookings', async (request, reply) => reply.code(201).send(await dependencies.bookings.book(await account(request.headers.cookie, dependencies), bookingInput(request.body))));
}
async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { const value = header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1); return (await authenticateSession(value, dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new DelegatedBookingError('UNAUTHORIZED'); } }
function authorizationInput(value: unknown): DelegatedAuthorizationInput { const body = value as Record<string, unknown>; if (typeof body?.delegatedClinicId !== 'string' || typeof body.serviceExposureId !== 'string' || typeof body.approvedStartsAt !== 'string' || typeof body.approvedEndsAt !== 'string') throw new DelegatedBookingError('CONFLICT'); return { delegatedClinicId: body.delegatedClinicId, serviceExposureId: body.serviceExposureId, approvedStartsAt: body.approvedStartsAt, approvedEndsAt: body.approvedEndsAt }; }
function bookingInput(value: unknown): DelegatedBookingInput { const body = value as Record<string, unknown>; if (typeof body?.authorizationId !== 'string' || typeof body.idempotencyKey !== 'string' || !body.idempotencyKey) throw new DelegatedBookingError('CONFLICT'); return { authorizationId: body.authorizationId, idempotencyKey: body.idempotencyKey }; }
