import type { FastifyInstance } from 'fastify';
import type { VerificationEvidenceService } from '../modules/doctor-verification/verification-evidence.js';
import { DoctorVerificationError } from '../modules/doctor-verification/doctor-verification.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export function registerDoctorVerificationEvidenceRoutes(app: FastifyInstance, dependencies: { evidence: VerificationEvidenceService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) {
  app.post('/v1/me/doctor-profiles/:doctorProfileId/verification-evidence', { bodyLimit: 5_600_000 }, async (request, reply) => reply.code(201).send({ evidence: await dependencies.evidence.upload(await account(request.headers.cookie, dependencies), id(request, 'doctorProfileId'), upload(request.body)) }));
  app.get('/v1/me/doctor-profiles/:doctorProfileId/verification-evidence', async (request) => ({ items: await dependencies.evidence.listForDoctor(await account(request.headers.cookie, dependencies), id(request, 'doctorProfileId')) }));
  app.get('/v1/me/doctor-profiles/:doctorProfileId/verification-evidence/:fileId/download', async (request, reply) => send(reply, await dependencies.evidence.downloadForDoctor(await account(request.headers.cookie, dependencies), id(request, 'doctorProfileId'), id(request, 'fileId'))));
  app.get('/v1/platform/doctor-verification-submissions/:submissionId/evidence', async (request) => ({ items: await dependencies.evidence.listForReviewer(await account(request.headers.cookie, dependencies), id(request, 'submissionId')) }));
  app.get('/v1/platform/doctor-verification-submissions/:submissionId/evidence/:fileId/download', async (request, reply) => send(reply, await dependencies.evidence.downloadForReviewer(await account(request.headers.cookie, dependencies), id(request, 'submissionId'), id(request, 'fileId'))));
}

async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { return (await authenticateSession(cookie(header, sessionCookieName), dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new DoctorVerificationError('UNAUTHORIZED'); } }
function cookie(header: string | undefined, name: string) { return header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${name}=`))?.slice(name.length + 1); }
function id(request: { params: unknown }, key: string) { const value = (request.params as Record<string, unknown>)[key]; if (typeof value !== 'string' || !value.trim()) throw new DoctorVerificationError('CONFLICT'); return value; }
function upload(value: unknown) { if (typeof value !== 'object' || value === null) throw new DoctorVerificationError('CONFLICT'); const input = value as Record<string, unknown>; if (typeof input.originalFilename !== 'string' || typeof input.contentType !== 'string' || typeof input.contentBase64 !== 'string' || !/^[A-Za-z0-9+/]*={0,2}$/.test(input.contentBase64)) throw new DoctorVerificationError('CONFLICT'); const body = Buffer.from(input.contentBase64, 'base64'); if (body.byteLength === 0) throw new DoctorVerificationError('CONFLICT'); return { originalFilename: input.originalFilename, contentType: input.contentType, body }; }
function send(reply: { header(name: string, value: string): unknown; send(value: Uint8Array): unknown }, value: { evidence: { originalFilename: string; contentType: string }; body: Uint8Array }) { reply.header('content-type', value.evidence.contentType); reply.header('content-disposition', `attachment; filename="${value.evidence.originalFilename.replace(/["\\]/g, '_')}"`); reply.header('cache-control', 'private, no-store'); return reply.send(value.body); }
