import type { FastifyInstance } from 'fastify';
import { MembershipAccessError, type MembershipService } from '../modules/memberships/memberships.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export async function registerMembershipRoutes(app: FastifyInstance, dependencies: { memberships: MembershipService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }): Promise<void> {
  app.post('/v1/tenants/:tenantId/invitations', async (request, reply) => { const body = request.body as { targetAccountId?: unknown; role?: unknown; expiresAt?: unknown }; if (typeof body.targetAccountId !== 'string' || typeof body.role !== 'string' || typeof body.expiresAt !== 'string') throw new MembershipAccessError('FORBIDDEN'); const result = await dependencies.memberships.invite(await account(request.headers.cookie, dependencies), (request.params as { tenantId: string }).tenantId, body.targetAccountId, body.role as never, new Date(body.expiresAt)); return reply.code(201).send({ invitationId: result.invitation.id, invitationSecret: result.secret }); });
  app.post('/v1/tenant-invitations/:invitationId/accept', async (request) => { const body = request.body as { secret?: unknown }; if (typeof body.secret !== 'string') throw new MembershipAccessError('FORBIDDEN'); return dependencies.memberships.accept(await account(request.headers.cookie, dependencies), (request.params as { invitationId: string }).invitationId, body.secret); });
  app.post('/v1/tenant-invitations/:invitationId/reject', async (request) => dependencies.memberships.reject(await account(request.headers.cookie, dependencies), (request.params as { invitationId: string }).invitationId));
  app.post('/v1/tenant-invitations/:invitationId/revoke', async (request) => dependencies.memberships.revoke(await account(request.headers.cookie, dependencies), (request.params as { invitationId: string }).invitationId));
  app.patch('/v1/tenants/:tenantId/memberships/:membershipId', async (request) => { const body = request.body as { status?: unknown; role?: unknown }; if (typeof body.status !== 'string' || typeof body.role !== 'string') throw new MembershipAccessError('FORBIDDEN'); return dependencies.memberships.change(await account(request.headers.cookie, dependencies), (request.params as { tenantId: string }).tenantId, (request.params as { membershipId: string }).membershipId, body.status as never, body.role as never); });
}
async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { const value = header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1); return (await authenticateSession(value, dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new MembershipAccessError('FORBIDDEN'); } }
