import type { FastifyInstance } from 'fastify';
import { NetworkError, type NetworkService, type PartyInput } from '../modules/network/network.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export async function registerNetworkRoutes(app: FastifyInstance, dependencies: { network: NetworkService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }): Promise<void> {
  app.post('/v1/network-connections', async (request, reply) => reply.code(201).send(await dependencies.network.request(await account(request.headers.cookie, dependencies), party((request.body as { source?: unknown }).source), party((request.body as { target?: unknown }).target))));
  app.post('/v1/network-connections/:connectionId/accept', async (request) => dependencies.network.accept(await account(request.headers.cookie, dependencies), (request.params as { connectionId: string }).connectionId));
  app.post('/v1/network-connections/:connectionId/reject', async (request) => dependencies.network.reject(await account(request.headers.cookie, dependencies), (request.params as { connectionId: string }).connectionId));
  app.post('/v1/network-connections/:connectionId/revoke', async (request) => dependencies.network.revoke(await account(request.headers.cookie, dependencies), (request.params as { connectionId: string }).connectionId));
  app.post('/v1/network-connections/:connectionId/capability-proposals', async (request, reply) => reply.code(201).send(await dependencies.network.propose(await account(request.headers.cookie, dependencies), (request.params as { connectionId: string }).connectionId, (request.body as { capability?: unknown }).capability as string)));
  app.post('/v1/network-connections/:connectionId/capability-proposals/:proposalId/accept', async (request) => dependencies.network.acceptCapability(await account(request.headers.cookie, dependencies), (request.params as { connectionId: string }).connectionId, (request.params as { proposalId: string }).proposalId));
  app.post('/v1/network-connections/:connectionId/capabilities/:capability/revoke', async (request) => dependencies.network.revokeCapability(await account(request.headers.cookie, dependencies), (request.params as { connectionId: string }).connectionId, (request.params as { capability: string }).capability));
}
function party(value: unknown): PartyInput { const item = value as { kind?: unknown; clinicId?: unknown; doctorProfileId?: unknown }; if (item?.kind === 'CLINIC' && typeof item.clinicId === 'string') return { kind: 'CLINIC', clinicId: item.clinicId }; if (item?.kind === 'DOCTOR' && typeof item.doctorProfileId === 'string') return { kind: 'DOCTOR', doctorProfileId: item.doctorProfileId }; throw new NetworkError(); }
async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { const value = header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1); return (await authenticateSession(value, dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new NetworkError(); } }
