import type { FastifyInstance } from 'fastify';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';
import { PlatformAdminError, type PlatformAdminService } from '../modules/platform-admin/platform-admin.js';
import { type PublicDiscoveryControlService } from '../modules/platform-admin/public-discovery-control.js';

export function registerPlatformAdminRoutes(app: FastifyInstance, dependencies: { platform: PlatformAdminService; discovery: PublicDiscoveryControlService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) {
  app.get('/v1/platform/dashboard', async (request) => dependencies.platform.dashboard(await account(request.headers.cookie, dependencies)));
  app.get('/v1/platform/clinics', async (request) => ({ items: await dependencies.platform.clinics(await account(request.headers.cookie, dependencies)) }));
  app.get('/v1/platform/clinics/:clinicId', async (request) => ({ clinic: await dependencies.platform.clinic(await account(request.headers.cookie, dependencies), id(request, 'clinicId')) }));
  app.post('/v1/platform/clinics/:clinicId/activate', async (request) => ({ clinic: await dependencies.platform.activateClinic(await account(request.headers.cookie, dependencies), id(request, 'clinicId')) }));
  app.get('/v1/platform/doctors', async (request) => ({ items: await dependencies.platform.doctors(await account(request.headers.cookie, dependencies)) }));
  app.get('/v1/platform/doctors/:doctorId', async (request) => ({ doctor: await dependencies.platform.doctor(await account(request.headers.cookie, dependencies), id(request, 'doctorId')) }));
  app.get('/v1/platform/doctor-invitations', async (request) => ({ items: await dependencies.platform.invitations(await account(request.headers.cookie, dependencies)) }));
  app.post('/v1/platform/doctor-invitations', async (request, reply) => { const body = request.body as { email?: unknown; displayName?: unknown }; if (typeof body?.email !== 'string' || (body.displayName !== undefined && typeof body.displayName !== 'string')) throw new PlatformAdminError('CONFLICT'); const result = await dependencies.platform.inviteDoctor(await account(request.headers.cookie, dependencies), { email: body.email, ...(typeof body.displayName === 'string' ? { displayName: body.displayName } : {}) }); return reply.code(201).send({ invitation: safe(result.invitation) }); });
  app.post('/v1/platform/doctor-invitations/:invitationId/resend', async (request) => { const result = await dependencies.platform.resendDoctorInvitation(await account(request.headers.cookie, dependencies), id(request, 'invitationId')); return { invitation: safe(result.invitation) }; });
  app.post('/v1/platform/doctor-invitations/:invitationId/revoke', async (request, reply) => { await dependencies.platform.revokeDoctorInvitation(await account(request.headers.cookie, dependencies), id(request, 'invitationId')); return reply.code(204).send(); });
  app.get('/v1/platform/clinics/:clinicId/public-discovery', async (request) => ({ publicDiscovery: await dependencies.discovery.status(await account(request.headers.cookie, dependencies), 'CLINIC', id(request, 'clinicId')) }));
  app.get('/v1/platform/clinics/:clinicId/discovery-readiness', async (request) => ({ discoveryReadiness: await dependencies.discovery.readiness(await account(request.headers.cookie, dependencies), 'CLINIC', id(request, 'clinicId')) }));
  app.post('/v1/platform/clinics/:clinicId/public-discovery/publish', async (request) => ({ publicDiscovery: await dependencies.discovery.publish(await account(request.headers.cookie, dependencies), 'CLINIC', id(request, 'clinicId')) }));
  app.post('/v1/platform/clinics/:clinicId/public-discovery/revoke', async (request) => ({ publicDiscovery: await dependencies.discovery.revoke(await account(request.headers.cookie, dependencies), 'CLINIC', id(request, 'clinicId')) }));
  app.get('/v1/platform/doctors/:doctorId/public-discovery', async (request) => ({ publicDiscovery: await dependencies.discovery.status(await account(request.headers.cookie, dependencies), 'DOCTOR', id(request, 'doctorId')) }));
  app.get('/v1/platform/doctors/:doctorId/discovery-readiness', async (request) => ({ discoveryReadiness: await dependencies.discovery.readiness(await account(request.headers.cookie, dependencies), 'DOCTOR', id(request, 'doctorId')) }));
  app.post('/v1/platform/doctors/:doctorId/public-discovery/publish', async (request) => ({ publicDiscovery: await dependencies.discovery.publish(await account(request.headers.cookie, dependencies), 'DOCTOR', id(request, 'doctorId')) }));
  app.post('/v1/platform/doctors/:doctorId/public-discovery/revoke', async (request) => ({ publicDiscovery: await dependencies.discovery.revoke(await account(request.headers.cookie, dependencies), 'DOCTOR', id(request, 'doctorId')) }));
}
async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { const value = header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1); return (await authenticateSession(value, dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new PlatformAdminError('UNAUTHORIZED'); } }
function id(request: { params: unknown }, key: string) { const value = (request.params as Record<string, unknown>)[key]; if (typeof value !== 'string' || !value.trim()) throw new PlatformAdminError('CONFLICT'); return value; }
function safe(value: { id: string; email: string; displayName: string | null; status: string; createdAt: Date; expiresAt: Date; revokedAt: Date | null; acceptedAt: Date | null }) { return { id: value.id, email: value.email, displayName: value.displayName, status: value.status, createdAt: value.createdAt, expiresAt: value.expiresAt, revokedAt: value.revokedAt, acceptedAt: value.acceptedAt }; }
