import type { FastifyInstance } from 'fastify';
import { ServiceOfferingError, type ServiceOfferingInput, type ServiceOfferingMutation, type ServiceOfferingService, type ServiceOfferingVersionInput } from '../modules/service-offerings/service-offerings.js';
import { authenticateSession, sessionCookieName, type SessionAuthenticatorRepository, type SessionPolicy } from '../modules/sessions/session.js';

export async function registerServiceOfferingRoutes(app: FastifyInstance, dependencies: { offerings: ServiceOfferingService; sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }): Promise<void> {
  app.post('/v1/service-offerings', async (request, reply) => reply.code(201).send(await dependencies.offerings.create(await account(request.headers.cookie, dependencies), createInput(request.body))));
  app.get('/v1/service-offerings/:offeringId', async (request) => dependencies.offerings.read(await account(request.headers.cookie, dependencies), (request.params as { offeringId: string }).offeringId));
  app.patch('/v1/service-offerings/:offeringId', async (request) => dependencies.offerings.update(await account(request.headers.cookie, dependencies), (request.params as { offeringId: string }).offeringId, mutation(request.body)));
  app.post('/v1/service-offerings/:offeringId/versions', async (request, reply) => reply.code(201).send(await dependencies.offerings.createVersion(await account(request.headers.cookie, dependencies), (request.params as { offeringId: string }).offeringId, versionInput(request.body))));
  app.get('/v1/service-offerings/:offeringId/versions/applicable', async (request) => { const at = new Date(String((request.query as { at?: unknown }).at)); if (Number.isNaN(at.getTime())) throw new ServiceOfferingError('CONFLICT'); return dependencies.offerings.applicableVersion(await account(request.headers.cookie, dependencies), (request.params as { offeringId: string }).offeringId, at); });
}
async function account(header: string | undefined, dependencies: { sessions: SessionAuthenticatorRepository; sessionPolicy: SessionPolicy }) { try { const value = header?.split(';').map((part) => part.trim()).find((part) => part.startsWith(`${sessionCookieName}=`))?.slice(sessionCookieName.length + 1); return (await authenticateSession(value, dependencies.sessionPolicy, dependencies.sessions)).accountId; } catch { throw new ServiceOfferingError('UNAUTHORIZED'); } }
function createInput(value: unknown): ServiceOfferingInput { const body = value as { owner?: { kind?: unknown; doctorProfileId?: unknown; clinicId?: unknown }; name?: unknown; description?: unknown; status?: unknown }; if (typeof body?.name !== 'string' || !status(body.status) || (body.description !== undefined && body.description !== null && typeof body.description !== 'string')) throw new ServiceOfferingError('CONFLICT'); if (body.owner?.kind === 'DOCTOR' && typeof body.owner.doctorProfileId === 'string') return { owner: { kind: 'DOCTOR', doctorProfileId: body.owner.doctorProfileId }, name: body.name, description: body.description as string | null | undefined, status: body.status }; if (body.owner?.kind === 'CLINIC' && typeof body.owner.clinicId === 'string') return { owner: { kind: 'CLINIC', clinicId: body.owner.clinicId }, name: body.name, description: body.description as string | null | undefined, status: body.status }; throw new ServiceOfferingError('CONFLICT'); }
function mutation(value: unknown): ServiceOfferingMutation { const body = value as { name?: unknown; description?: unknown; status?: unknown }; if (typeof body?.name !== 'string' || !status(body.status) || (body.description !== undefined && body.description !== null && typeof body.description !== 'string')) throw new ServiceOfferingError('CONFLICT'); return { name: body.name, description: body.description as string | null | undefined, status: body.status }; }
function versionInput(value: unknown): ServiceOfferingVersionInput { const body = value as { versionNumber?: unknown; status?: unknown; effectiveFrom?: unknown; effectiveTo?: unknown; currency?: unknown; amountMinor?: unknown }; if (!Number.isInteger(body?.versionNumber) || !versionStatus(body.status) || typeof body.effectiveFrom !== 'string' || (body.effectiveTo !== undefined && body.effectiveTo !== null && typeof body.effectiveTo !== 'string') || typeof body.currency !== 'string' || typeof body.amountMinor !== 'string' || !/^(0|[1-9]\d*)$/.test(body.amountMinor)) throw new ServiceOfferingError('CONFLICT'); try { return { versionNumber: body.versionNumber as number, status: body.status, effectiveFrom: new Date(body.effectiveFrom), effectiveTo: body.effectiveTo ? new Date(body.effectiveTo as string) : null, currency: body.currency, amountMinor: BigInt(body.amountMinor) }; } catch { throw new ServiceOfferingError('CONFLICT'); } }
function status(value: unknown): value is 'DRAFT' | 'ACTIVE' | 'ARCHIVED' { return value === 'DRAFT' || value === 'ACTIVE' || value === 'ARCHIVED'; }
function versionStatus(value: unknown): value is 'DRAFT' | 'ACTIVE' | 'RETIRED' { return value === 'DRAFT' || value === 'ACTIVE' || value === 'RETIRED'; }
