import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { AuditRepository } from '../audit/audit.js';
import type { TenantContextService } from '../memberships/memberships.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';

export type Party = { kind: 'CLINIC'; id: string; tenantId: string } | { kind: 'DOCTOR'; id: string };
export type PartyInput = { kind: 'CLINIC'; clinicId: string } | { kind: 'DOCTOR'; doctorProfileId: string };
export type ConnectionStatus = 'REQUESTED' | 'ACCEPTED' | 'REJECTED' | 'REVOKED';
export type Capability = 'DISCOVER' | 'CONTACT';
export type Connection = { id: string; status: ConnectionStatus; left: Party; right: Party; initiatedBy: string; initiator: Party };
export type Proposal = { id: string; connectionId: string; capability: Capability; proposer: Party; accepter: Party; status: 'PENDING' | 'ACCEPTED' | 'REVOKED' };
export class NetworkError extends Error { public constructor(public readonly code: 'FORBIDDEN' | 'CONFLICT' = 'FORBIDDEN') { super(code === 'CONFLICT' ? 'The requested network operation cannot be completed.' : 'Network access is not permitted.'); } }
export interface NetworkRepository { transaction<T>(operation: (database: PostgresExecutor) => Promise<T>): Promise<T>; clinic(database: PostgresExecutor, clinicId: string): Promise<Party | null>; ownedEligibleDoctor(database: PostgresExecutor, accountId: string, profileId: string): Promise<Party | null>; eligibleDoctor(database: PostgresExecutor, profileId: string): Promise<Party | null>; create(database: PostgresExecutor, connection: Connection): Promise<void>; lockConnection(database: PostgresExecutor, id: string): Promise<Connection | null>; updateConnection(database: PostgresExecutor, id: string, from: ConnectionStatus, to: ConnectionStatus, actorId: string): Promise<boolean>; appendConnectionEvent(database: PostgresExecutor, connectionId: string, event: string, actorId: string): Promise<void>; createProposal(database: PostgresExecutor, proposal: Proposal, actorId: string): Promise<void>; lockProposal(database: PostgresExecutor, id: string): Promise<Proposal | null>; acceptProposal(database: PostgresExecutor, proposal: Proposal, actorId: string): Promise<boolean>; revokeCapability(database: PostgresExecutor, connectionId: string, capability: Capability, actorId: string): Promise<boolean>; }
const capabilities: readonly Capability[] = ['DISCOVER', 'CONTACT'];
export class NetworkService {
  public constructor(private readonly repository: NetworkRepository, private readonly context: Pick<TenantContextService, 'require'>, private readonly audit: AuditRepository) {}
  public async request(accountId: string, source: PartyInput, target: PartyInput): Promise<Connection> { return this.repository.transaction(async (db) => { if (source.kind === 'DOCTOR' && target.kind === 'DOCTOR') return this.denied(accountId, 'NETWORK_CONNECTION'); const left = await this.ownedParty(db, accountId, source); const right = await this.targetParty(db, target); if (!left || !right || same(left, right)) return this.denied(accountId, 'NETWORK_CONNECTION'); const pair = normalize(left, right); const connection: Connection = { id: createIdentifier(), status: 'REQUESTED', left: pair.left, right: pair.right, initiatedBy: accountId, initiator: left }; try { await this.repository.create(db, connection); } catch { return this.conflict(accountId, 'NETWORK_CONNECTION'); } await this.repository.appendConnectionEvent(db, connection.id, 'CONNECTION_CREATED', accountId); await this.audit.append({ category: 'BUSINESS', eventType: 'NETWORK_REQUESTED', actorAccountId: accountId, targetType: 'NETWORK_CONNECTION', targetId: connection.id, outcome: 'SUCCESS' }); return connection; }); }
  public async accept(accountId: string, id: string) { return this.transition(accountId, id, 'ACCEPTED'); } public async reject(accountId: string, id: string) { return this.transition(accountId, id, 'REJECTED'); } public async revoke(accountId: string, id: string) { return this.transition(accountId, id, 'REVOKED'); }
  public async propose(accountId: string, connectionId: string, capability: string): Promise<Proposal> { if (!capabilities.includes(capability as Capability)) return this.denied(accountId, 'NETWORK_CAPABILITY', connectionId); return this.repository.transaction(async (db) => { const connection = await this.repository.lockConnection(db, connectionId); const actor = connection && await this.participant(db, accountId, connection); if (!connection || !actor || connection.status !== 'ACCEPTED') return this.denied(accountId, 'NETWORK_CAPABILITY', connectionId); const proposal: Proposal = { id: createIdentifier(), connectionId, capability: capability as Capability, proposer: actor, accepter: other(connection, actor), status: 'PENDING' }; try { await this.repository.createProposal(db, proposal, accountId); } catch { return this.conflict(accountId, 'NETWORK_CAPABILITY', connectionId); } await this.audit.append({ category: 'BUSINESS', eventType: 'NETWORK_CAPABILITY_PROPOSED', actorAccountId: accountId, targetType: 'NETWORK_CAPABILITY_PROPOSAL', targetId: proposal.id, outcome: 'SUCCESS' }); return proposal; }); }
  public async acceptCapability(accountId: string, connectionId: string, proposalId: string): Promise<void> { return this.repository.transaction(async (db) => { const connection = await this.repository.lockConnection(db, connectionId); const proposal = await this.repository.lockProposal(db, proposalId); const actor = connection && await this.participant(db, accountId, connection); if (!connection || !proposal || !actor || proposal.connectionId !== connectionId || connection.status !== 'ACCEPTED' || proposal.status !== 'PENDING' || !same(proposal.accepter, actor) || !await this.repository.acceptProposal(db, proposal, accountId)) return this.denied(accountId, 'NETWORK_CAPABILITY_PROPOSAL', proposalId); await this.repository.appendConnectionEvent(db, connectionId, 'CAPABILITY_GRANTED', accountId); await this.audit.append({ category: 'BUSINESS', eventType: 'NETWORK_CAPABILITY_ACCEPTED', actorAccountId: accountId, targetType: 'NETWORK_CAPABILITY_PROPOSAL', targetId: proposalId, outcome: 'SUCCESS' }); }); }
  public async revokeCapability(accountId: string, connectionId: string, capability: string): Promise<void> { if (!capabilities.includes(capability as Capability)) return this.denied(accountId, 'NETWORK_CAPABILITY', connectionId); return this.repository.transaction(async (db) => { const connection = await this.repository.lockConnection(db, connectionId); if (!connection || connection.status !== 'ACCEPTED' || !await this.participant(db, accountId, connection) || !await this.repository.revokeCapability(db, connectionId, capability as Capability, accountId)) return this.denied(accountId, 'NETWORK_CAPABILITY', connectionId); await this.repository.appendConnectionEvent(db, connectionId, 'CAPABILITY_REVOKED', accountId); await this.audit.append({ category: 'BUSINESS', eventType: 'NETWORK_CAPABILITY_REVOKED', actorAccountId: accountId, targetType: 'NETWORK_CAPABILITY', targetId: connectionId, outcome: 'SUCCESS' }); }); }
  private async transition(accountId: string, id: string, to: Exclude<ConnectionStatus, 'REQUESTED'>): Promise<void> { return this.repository.transaction(async (db) => { const connection = await this.repository.lockConnection(db, id); const actor = connection && await this.participant(db, accountId, connection); const from: ConnectionStatus = to === 'REVOKED' ? 'ACCEPTED' : 'REQUESTED'; if (!connection || !actor || (to !== 'REVOKED' && same(actor, connection.initiator)) || !await this.repository.updateConnection(db, id, from, to, accountId)) return this.denied(accountId, 'NETWORK_CONNECTION', id); await this.repository.appendConnectionEvent(db, id, `CONNECTION_${to}`, accountId); await this.audit.append({ category: 'BUSINESS', eventType: `NETWORK_${to}`, actorAccountId: accountId, targetType: 'NETWORK_CONNECTION', targetId: id, outcome: 'SUCCESS' }); }); }
  private async ownedParty(db: PostgresExecutor, accountId: string, party: PartyInput) { if (party.kind === 'DOCTOR') return this.repository.ownedEligibleDoctor(db, accountId, party.doctorProfileId); const clinic = await this.repository.clinic(db, party.clinicId); if (!clinic || clinic.kind !== 'CLINIC') return null; try { await this.context.require(accountId, clinic.tenantId, 'network.manage'); return clinic; } catch { return null; } } private async targetParty(db: PostgresExecutor, party: PartyInput) { return party.kind === 'CLINIC' ? this.repository.clinic(db, party.clinicId) : this.repository.eligibleDoctor(db, party.doctorProfileId); } private async participant(db: PostgresExecutor, accountId: string, connection: Connection): Promise<Party | null> { for (const party of [connection.left, connection.right]) { const owned = party.kind === 'CLINIC' ? await this.ownedParty(db, accountId, { kind: 'CLINIC', clinicId: party.id }) : await this.repository.ownedEligibleDoctor(db, accountId, party.id); if (owned) return owned; } return null; } private async denied(accountId: string, targetType: string, targetId?: string): Promise<never> { await this.audit.append({ category: 'AUTHORIZATION', eventType: 'NETWORK_ACCESS_DENIED', actorAccountId: accountId, targetType, targetId, outcome: 'DENIED' }); throw new NetworkError(); } private async conflict(accountId: string, targetType: string, targetId?: string): Promise<never> { await this.audit.append({ category: 'SECURITY', eventType: 'NETWORK_OPERATION_CONFLICT', actorAccountId: accountId, targetType, targetId, outcome: 'DENIED' }); throw new NetworkError('CONFLICT'); }
}
function same(left: Party | null, right: Party | null) { return !!left && !!right && left.kind === right.kind && left.id === right.id; } function other(connection: Connection, actor: Party) { return same(connection.left, actor) ? connection.right : connection.left; } function normalize(left: Party, right: Party) { return left.kind === 'CLINIC' && right.kind === 'CLINIC' && left.id > right.id ? { left: right, right: left } : { left, right }; }
