import type { DatabaseHealth } from '../../infrastructure/database.js';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { Capability, Connection, ConnectionStatus, NetworkRepository, Party, Proposal } from './network.js';

export class PostgresNetworkRepository implements NetworkRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async clinic(db: PostgresExecutor, clinicId: string) { return party(await db.query("SELECT clinics.id, clinics.tenant_id FROM clinics JOIN tenants ON tenants.id = clinics.tenant_id WHERE clinics.id = $1 AND tenants.status = 'ACTIVE' AND clinics.status = 'ACTIVE'", [clinicId]), 'CLINIC'); }
  public async ownedEligibleDoctor(db: PostgresExecutor, accountId: string, profileId: string) { return party(await db.query("SELECT id FROM doctor_profiles WHERE id = $1 AND account_id = $2 AND status = 'ACTIVE' AND professional_verification_status = 'VERIFIED'", [profileId, accountId]), 'DOCTOR'); }
  public async eligibleDoctor(db: PostgresExecutor, profileId: string) { return party(await db.query("SELECT id FROM doctor_profiles WHERE id = $1 AND status = 'ACTIVE' AND professional_verification_status = 'VERIFIED'", [profileId]), 'DOCTOR'); }
  public async create(db: PostgresExecutor, c: Connection) { const clinicLeft = c.left.kind === 'CLINIC' ? c.left.id : c.right.kind === 'CLINIC' ? c.right.id : null; const clinicRight = c.left.kind === 'CLINIC' && c.right.kind === 'CLINIC' ? c.right.id : null; const doctor = c.left.kind === 'DOCTOR' ? c.left.id : c.right.kind === 'DOCTOR' ? c.right.id : null; const kind = doctor ? 'CLINIC_DOCTOR' : 'CLINIC_CLINIC'; const recipient = c.right.kind; await db.query('INSERT INTO network_connections (id, connection_kind, clinic_left_id, clinic_right_id, doctor_profile_id, status, initiated_by_account_id, recipient_party_kind, initiator_party_kind, initiator_clinic_id, initiator_doctor_profile_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)', [c.id, kind, clinicLeft!, clinicRight, doctor, c.status, c.initiatedBy, recipient, c.initiator.kind, c.initiator.kind === 'CLINIC' ? c.initiator.id : null, c.initiator.kind === 'DOCTOR' ? c.initiator.id : null]); }
  public async lockConnection(db: PostgresExecutor, id: string) { const result = await db.query('SELECT id, status, clinic_left_id, clinic_right_id, doctor_profile_id, initiated_by_account_id, initiator_party_kind, initiator_clinic_id, initiator_doctor_profile_id FROM network_connections WHERE id = $1 FOR UPDATE', [id]); const row = result.rows[0] as Record<string, string> | undefined; if (!row || !isStatus(row.status) || !row.initiator_party_kind) return null; const left: Party = { kind: 'CLINIC', id: row.clinic_left_id, tenantId: await this.tenantId(db, row.clinic_left_id) }; const right: Party = row.doctor_profile_id ? { kind: 'DOCTOR', id: row.doctor_profile_id } : { kind: 'CLINIC', id: row.clinic_right_id, tenantId: await this.tenantId(db, row.clinic_right_id) }; const initiator: Party = row.initiator_party_kind === 'CLINIC' ? { kind: 'CLINIC', id: row.initiator_clinic_id, tenantId: await this.tenantId(db, row.initiator_clinic_id) } : { kind: 'DOCTOR', id: row.initiator_doctor_profile_id }; return { id: row.id, status: row.status, left, right, initiatedBy: row.initiated_by_account_id, initiator }; }
  public async updateConnection(db: PostgresExecutor, id: string, from: ConnectionStatus, to: ConnectionStatus, actorId: string) { void actorId; const column = to === 'ACCEPTED' ? 'accepted_at' : to === 'REJECTED' ? 'rejected_at' : 'revoked_at'; const result = await db.query(`UPDATE network_connections SET status = $3, ${column} = current_timestamp, updated_at = current_timestamp WHERE id = $1 AND status = $2`, [id, from, to]); return result.rowCount === 1; }
  public async appendConnectionEvent(db: PostgresExecutor, connectionId: string, event: string, actorId: string) { await db.query('INSERT INTO network_connection_events (id, network_connection_id, event_type, actor_account_id) VALUES ($1,$2,$3,$4)', [createIdentifier(), connectionId, event, actorId]); }
  public async createProposal(db: PostgresExecutor, p: Proposal, actorId: string) { await db.query('INSERT INTO network_capability_proposals (id, network_connection_id, capability_key, proposer_party_kind, proposer_clinic_id, proposer_doctor_profile_id, accepter_party_kind, accepter_clinic_id, accepter_doctor_profile_id, proposed_by_account_id, status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)', [p.id,p.connectionId,p.capability,p.proposer.kind,p.proposer.kind === 'CLINIC' ? p.proposer.id : null,p.proposer.kind === 'DOCTOR' ? p.proposer.id : null,p.accepter.kind,p.accepter.kind === 'CLINIC' ? p.accepter.id : null,p.accepter.kind === 'DOCTOR' ? p.accepter.id : null,actorId,p.status]); }
  public async lockProposal(db: PostgresExecutor, id: string) { const r = await db.query('SELECT * FROM network_capability_proposals WHERE id = $1 FOR UPDATE', [id]); const x = r.rows[0] as Record<string, string> | undefined; if (!x || !isCapability(x.capability_key) || !isProposalStatus(x.status)) return null; return { id: x.id, connectionId: x.network_connection_id, capability: x.capability_key, proposer: dbParty(x, 'proposer'), accepter: dbParty(x, 'accepter'), status: x.status }; }
  public async acceptProposal(db: PostgresExecutor, p: Proposal, actorId: string) { const updated = await db.query("UPDATE network_capability_proposals SET status = 'ACCEPTED', accepted_at = current_timestamp, accepted_by_account_id = $2, updated_at = current_timestamp WHERE id = $1 AND status = 'PENDING'", [p.id, actorId]); if (updated.rowCount !== 1) return false; await db.query("INSERT INTO network_connection_capabilities (id, network_connection_id, capability_key, status, granted_at, granted_by_account_id) VALUES ($1,$2,$3,'ACTIVE',current_timestamp,$4)", [createIdentifier(), p.connectionId, p.capability, actorId]); return true; }
  public async revokeCapability(db: PostgresExecutor, connectionId: string, capability: Capability, actorId: string) { const capabilityRow = await db.query("UPDATE network_connection_capabilities SET status = 'REVOKED', revoked_at = current_timestamp, revoked_by_account_id = $3, updated_at = current_timestamp WHERE network_connection_id = $1 AND capability_key = $2 AND status = 'ACTIVE'", [connectionId, capability, actorId]); if (capabilityRow.rowCount !== 1) return false; await db.query("UPDATE network_capability_proposals SET status = 'REVOKED', revoked_at = current_timestamp, revoked_by_account_id = $3, updated_at = current_timestamp WHERE network_connection_id = $1 AND capability_key = $2 AND status = 'ACCEPTED'", [connectionId, capability, actorId]); return true; }
  private async tenantId(db: PostgresExecutor, clinicId: string) { const r = await db.query('SELECT tenant_id FROM clinics WHERE id = $1', [clinicId]); return (r.rows[0] as { tenant_id: string } | undefined)?.tenant_id ?? ''; }
}
function party(result: { rows: unknown[] }, kind: 'CLINIC' | 'DOCTOR'): Party | null { const row = result.rows[0] as { id: string; tenant_id?: string } | undefined; return row ? kind === 'CLINIC' ? { kind, id: row.id, tenantId: row.tenant_id! } : { kind, id: row.id } : null; }
function dbParty(row: Record<string, string>, prefix: 'proposer' | 'accepter'): Party { return row[`${prefix}_party_kind`] === 'CLINIC' ? { kind: 'CLINIC', id: row[`${prefix}_clinic_id`], tenantId: '' } : { kind: 'DOCTOR', id: row[`${prefix}_doctor_profile_id`] }; }
function isStatus(value: string): value is ConnectionStatus { return ['REQUESTED','ACCEPTED','REJECTED','REVOKED'].includes(value); } function isCapability(value: string): value is Capability { return ['DISCOVER','CONTACT'].includes(value); } function isProposalStatus(value: string): value is Proposal['status'] { return ['PENDING','ACCEPTED','REVOKED'].includes(value); }
