import { describe, expect, it } from 'vitest';
import { AppointmentError, AppointmentService, type AppointmentIntent, type AppointmentRepository, type AvailabilityException, type AvailabilityRule, type BookableService, type ProviderInput, type SlotReservation } from '../src/modules/appointments/appointments.js';

const now = new Date('2029-12-31T00:00:00Z');
const local = '2030-01-07T10:00:00'; // Monday in the configured provider timezone.
const doctor: ProviderInput = { kind: 'DOCTOR', doctorProfileId: 'doctor-a' };
const clinic: ProviderInput = { kind: 'CLINIC', clinicId: 'clinic-a' };

class Repository implements AppointmentRepository {
  public patientActive = true; public bookable = true; public exposurePublished = true; public capacity = 1; public exceptions: AvailabilityException[] = []; public intents = new Map<string, AppointmentIntent>(); public reservations = new Map<string, SlotReservation>(); public audits: unknown[] = [];
  async transaction<T>(operation: Parameters<AppointmentRepository['transaction']>[0]): Promise<T> { return operation({ query: async () => ({ rows: [], rowCount: 0 }) }); }
  async activePatient() { return this.patientActive; }
  async findByIdempotency(actor: string, key: string) { return [...this.intents.values()].find((item) => item.bookingActorAccountId === actor && item.idempotencyKey === key) ?? null; }
  async lockPublishedExposure(_db: unknown, exposureId: string) { if (!this.exposurePublished || !['exposure-a', 'clinic-exposure'].includes(exposureId)) return null; return exposureId === 'clinic-exposure' ? { id: exposureId, serviceOfferingId: 'clinic-offering', provider: clinic } : { id: exposureId, serviceOfferingId: 'offering-a', provider: doctor }; }
  async lockBookable(_db: unknown, offeringId: string, provider: ProviderInput): Promise<BookableService | null> { if (!this.bookable || !['offering-a', 'clinic-offering'].includes(offeringId)) return null; const selected = offeringId === 'clinic-offering' ? clinic : doctor; if (selected.kind !== provider.kind || (selected.kind === 'DOCTOR' ? selected.doctorProfileId !== (provider as typeof doctor).doctorProfileId : selected.clinicId !== (provider as typeof clinic).clinicId)) return null; return { provider: selected, serviceOfferingId: offeringId, versionId: `${offeringId}-version`, priceId: `${offeringId}-price`, currency: 'INR', priceAmountMinor: 10_000n, bookingTenantId: selected.kind === 'CLINIC' ? 'clinic-tenant-a' : null, timezone: 'Asia/Kolkata', durationSeconds: 1800, bufferBeforeSeconds: 0, bufferAfterSeconds: 0, capacity: this.capacity, bookingLeadSeconds: 60, bookingHorizonSeconds: 60 * 60 * 24 * 14, holdSeconds: 600, rules: rules(), exceptions: this.exceptions }; }
  async createIntent(_db: unknown, intent: AppointmentIntent) { if (await this.findByIdempotency(intent.bookingActorAccountId, intent.idempotencyKey)) throw { code: '23505' }; this.intents.set(intent.id, intent); }
  async lockIntent(_db: unknown, id: string) { return this.intents.get(id) ?? null; }
  async findReservationIntentId(id: string) { return this.reservations.get(id)?.appointmentIntentId ?? null; }
  async activeCapacityUnits(_db: unknown, version: string, starts: Date, ends: Date) { return [...this.reservations.values()].filter((item) => item.serviceOfferingVersionId === version && item.status === 'HELD' && item.expiresAt > now && item.startsAt < ends && starts < item.endsAt).reduce((total, item) => total + item.capacityUnits, 0); }
  async createReservation(_db: unknown, reservation: SlotReservation) { if ([...this.reservations.values()].some((item) => item.appointmentIntentId === reservation.appointmentIntentId)) throw { code: '23505' }; this.reservations.set(reservation.id, reservation); }
  async transitionIntent(_db: unknown, id: string, from: AppointmentIntent['state'], to: AppointmentIntent['state']) { const intent = this.intents.get(id); if (!intent || intent.state !== from) return false; this.intents.set(id, { ...intent, state: to }); return true; }
  async lockReservation(_db: unknown, id: string) { return this.reservations.get(id) ?? null; }
  async releaseReservation(_db: unknown, id: string, at: Date) { const item = this.reservations.get(id); if (!item || item.status !== 'HELD') return false; this.reservations.set(id, { ...item, status: 'RELEASED', releasedAt: at }); return true; }
  async expireReservation(_db: unknown, id: string, at: Date) { const item = this.reservations.get(id); if (!item || item.status !== 'HELD' || item.expiresAt > at) return false; this.reservations.set(id, { ...item, status: 'EXPIRED', expiredAt: at }); return true; }
  async appendAudit(_db: unknown, event: unknown) { this.audits.push(event); }
}
function rules(): AvailabilityRule[] { return [{ canonicalRecurrence: 'FREQ=WEEKLY;BYDAY=MO', effectiveFrom: new Date('2029-01-01T00:00:00Z'), effectiveTo: null, windows: [{ kind: 'WORKING', weekday: 1, startSeconds: 9 * 3600, endSeconds: 17 * 3600 }] }]; }
function setup() { const repository = new Repository(); const audit = { events: [] as unknown[], append: async (event: unknown) => { audit.events.push(event); } }; return { repository, audit, service: new AppointmentService(repository, audit, () => now) }; }
function input(overrides: Partial<{ serviceExposureId: string; requestedLocalAt: string; idempotencyKey: string }> = {}) { return { serviceExposureId: 'exposure-a', requestedLocalAt: local, idempotencyKey: 'key-a', ...overrides }; }

describe('theCliniQ Phase 5 Step 3.2 Appointment Intent and Reservation service', () => {
  it('creates valid patient-to-doctor and patient-to-clinic intents only through published exposure', async () => { const { service } = setup(); await expect(service.create('patient-a', input())).resolves.toMatchObject({ provider: doctor, serviceExposureId: 'exposure-a', bookingTenantId: null, state: 'APPOINTMENT_INTENT', patientAccountId: 'patient-a' }); await expect(service.create('patient-a', input({ serviceExposureId: 'clinic-exposure', idempotencyKey: 'clinic-key' }))).resolves.toMatchObject({ provider: clinic, bookingTenantId: 'clinic-tenant-a', serviceExposureId: 'clinic-exposure' }); });
  it('derives patient, provider, offering, and booking actor exclusively from the authenticated account and published exposure', async () => { const { service } = setup(); await expect(service.create(undefined, input())).rejects.toMatchObject({ code: 'UNAUTHORIZED' }); await expect(service.create('patient-a', input({ serviceExposureId: 'another-doctor-exposure' }))).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('rejects inactive or unpublished patient/provider/service/price/policy state without ID authority', async () => { const { service, repository } = setup(); repository.patientActive = false; await expect(service.create('patient-a', input())).rejects.toMatchObject({ code: 'FORBIDDEN' }); repository.patientActive = true; repository.exposurePublished = false; await expect(service.create('patient-a', input())).rejects.toMatchObject({ code: 'FORBIDDEN' }); repository.exposurePublished = true; repository.bookable = false; await expect(service.create('patient-a', input())).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('enforces lead time, horizon, recurrence, breaks, exclusions, and allows valid one-off availability', async () => { const { service, repository } = setup(); await expect(service.create('patient-a', input({ requestedLocalAt: '2029-12-31T05:30:00', idempotencyKey: 'lead' }))).rejects.toMatchObject({ code: 'CONFLICT' }); await expect(service.create('patient-a', input({ requestedLocalAt: '2030-02-01T10:00:00', idempotencyKey: 'horizon' }))).rejects.toMatchObject({ code: 'CONFLICT' }); repository.exceptions = [{ kind: 'BLOCKED', status: 'ACTIVE', start: new Date('2030-01-07T04:30:00Z'), end: new Date('2030-01-07T05:00:00Z') }]; await expect(service.create('patient-a', input({ idempotencyKey: 'blocked' }))).rejects.toMatchObject({ code: 'CONFLICT' }); repository.exceptions = [{ kind: 'ONE_OFF', status: 'ACTIVE', start: new Date('2030-01-08T04:30:00Z'), end: new Date('2030-01-08T05:00:00Z') }]; await expect(service.create('patient-a', input({ requestedLocalAt: '2030-01-08T10:00:00', idempotencyKey: 'one-off' }))).resolves.toBeTruthy(); });
  it('derives a server-side fingerprint, returns only a same request, and audits idempotency conflicts', async () => { const { service, audit } = setup(); const created = await service.create('patient-a', input()); await expect(service.create('patient-a', input())).resolves.toMatchObject({ id: created.id }); await expect(service.create('patient-a', input({ requestedLocalAt: '2030-01-07T10:30:00' }))).rejects.toMatchObject({ code: 'CONFLICT' }); await expect(service.create('patient-b', input())).resolves.toBeTruthy(); expect(audit.events).toEqual(expect.arrayContaining([expect.objectContaining({ eventType: 'APPOINTMENT_INTENT_IDEMPOTENCY_CONFLICT', outcome: 'DENIED' })])); });
  it('acquires capacity once, rejects duplicate acquisition and deterministic capacity exhaustion', async () => { const { service } = setup(); const first = await service.create('patient-a', input()); await expect(service.reserve('patient-a', first.id)).resolves.toMatchObject({ status: 'HELD' }); await expect(service.reserve('patient-a', first.id)).rejects.toMatchObject({ code: 'CONFLICT' }); const second = await service.create('patient-b', input({ idempotencyKey: 'key-b' })); await expect(service.reserve('patient-b', second.id)).rejects.toMatchObject({ code: 'CONFLICT' }); });
  it('revalidates patient authorization before reservation and release', async () => { const { service, repository } = setup(); const intent = await service.create('patient-a', input()); repository.patientActive = false; await expect(service.reserve('patient-a', intent.id)).rejects.toMatchObject({ code: 'FORBIDDEN' }); repository.patientActive = true; const reservation = await service.reserve('patient-a', intent.id); repository.patientActive = false; await expect(service.release('patient-a', reservation.id)).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('does not invalidate an existing intent when its exposure is later unpublished', async () => { const { service, repository } = setup(); const intent = await service.create('patient-a', input()); repository.exposurePublished = false; await expect(service.reserve('patient-a', intent.id)).resolves.toMatchObject({ appointmentIntentId: intent.id, status: 'HELD' }); expect(repository.intents.get(intent.id)).toMatchObject({ serviceExposureId: 'exposure-a', state: 'SLOT_RESERVED' }); });
  it('does not reserve expired intents, audits expiry, and records release without allowing reactivation', async () => { const { service, repository } = setup(); const expired = await service.create('patient-a', input()); repository.intents.set(expired.id, { ...expired, expiresAt: new Date('2029-12-31T00:00:00Z') }); await expect(service.reserve('patient-a', expired.id)).rejects.toMatchObject({ code: 'CONFLICT' }); expect(repository.intents.get(expired.id)).toMatchObject({ state: 'EXPIRED' }); expect(repository.audits).toEqual(expect.arrayContaining([expect.objectContaining({ eventType: 'APPOINTMENT_INTENT_EXPIRED' })])); const current = await service.create('patient-a', input({ idempotencyKey: 'releasable' })); const reservation = await service.reserve('patient-a', current.id); await service.release('patient-a', reservation.id); expect(repository.reservations.get(reservation.id)).toMatchObject({ status: 'RELEASED', releasedAt: now }); await expect(service.release('patient-a', reservation.id)).rejects.toMatchObject({ code: 'CONFLICT' }); });
  it('provides an internal expiry cleanup operation without exposing a worker or payment path', async () => { const { service, repository } = setup(); const intent = await service.create('patient-a', input()); const reservation = await service.reserve('patient-a', intent.id); repository.reservations.set(reservation.id, { ...reservation, expiresAt: new Date('2029-12-31T00:00:00Z') }); await expect(service.expire(reservation.id)).resolves.toBe(true); expect(repository.reservations.get(reservation.id)).toMatchObject({ status: 'EXPIRED' }); await expect(service.expire(reservation.id)).resolves.toBe(false); });
  it('audits successful intent/reservation lifecycle and denied access', async () => { const { service, repository, audit } = setup(); const intent = await service.create('patient-a', input()); const reservation = await service.reserve('patient-a', intent.id); await expect(service.release('patient-b', reservation.id)).rejects.toBeInstanceOf(AppointmentError); expect(repository.audits).toEqual(expect.arrayContaining([expect.objectContaining({ eventType: 'APPOINTMENT_INTENT_CREATED' }), expect.objectContaining({ eventType: 'SLOT_RESERVED' })])); expect(audit.events).toEqual(expect.arrayContaining([expect.objectContaining({ eventType: 'APPOINTMENT_ACCESS_DENIED', outcome: 'DENIED' })])); });
  it('treats Sunday as weekday 7 without changing Monday working-window behavior', async () => { const { service, repository } = setup(); const sunday = '2030-01-06T10:00:00'; repository.bookable = true; const original = await repository.lockBookable({} as never, 'offering-a', doctor, sunday); if (!original) throw new Error('Expected fixture bookable service.'); const sundayBookable = { ...original, rules: [{ ...original.rules[0]!, canonicalRecurrence: 'FREQ=WEEKLY;BYDAY=SU', windows: [{ kind: 'WORKING' as const, weekday: 7, startSeconds: 9 * 3600, endSeconds: 17 * 3600 }] }] }; repository.lockBookable = async () => sundayBookable; await expect(service.create('patient-a', input({ requestedLocalAt: sunday, idempotencyKey: 'sunday' }))).resolves.toMatchObject({ state: 'APPOINTMENT_INTENT' }); });
});
