import { describe, expect, it } from 'vitest';
import { AppointmentPrescriptionService, type Prescription, type PrescriptionAccess, type PrescriptionItemInput, type PrescriptionRepository } from '../src/modules/prescriptions/appointment-prescriptions.js';

const item = (): PrescriptionItemInput => ({ position: 1, medicineName: 'Medicine', strength: '10mg', dosage: '1 tablet', frequency: 'daily', duration: '5 days', route: null, quantity: null, instructions: null });
class Repo implements PrescriptionRepository {
  public accessValue: PrescriptionAccess | null = { appointmentId: 'a', status: 'IN_PROGRESS', patientProfileId: 'p', doctorProfileId: 'd' }; public prescription: Prescription | null = null; public audits: string[] = []; public doctorAlsoPatient = false;
  async transaction<T>(op: (db: never) => Promise<T>) { return op(undefined as never); } async lockAccess(){return this.accessValue;} async access(){return this.accessValue;} async ownsPatient(_: never,account:string,profile:string){return (account==='patient'||this.doctorAlsoPatient&&account==='doctor')&&profile==='p';} async ownsDoctor(_: never,account:string,profile:string){return account==='doctor'&&profile==='d';}
  async find(){return this.prescription ? structuredClone(this.prescription) : null;} async findByCreateKey(_:never,account:string,key:string){return this.prescription?.createdByAccountId===account && (this.prescription as Prescription & { createKey?:string }).createKey===key ? structuredClone(this.prescription) : null;} async findByIssueKey(_:never,account:string,key:string){return this.prescription?.issuedByAccountId===account && (this.prescription as Prescription & { issueKey?:string }).issueKey===key ? structuredClone(this.prescription) : null;}
  async create(_:never,value:Prescription & {createIdempotencyKey:string}){this.prescription={...value,items:[],createdAt:new Date(0),updatedAt:new Date(0)}; (this.prescription as Prescription & {createKey:string}).createKey=value.createIdempotencyKey;} async replaceItems(_:never,_id:string,items:PrescriptionItemInput[]){if(!this.prescription)throw new Error();this.prescription.items=items.map((v,i)=>({id:`i${i}`,...v}));} async updateDraft(_:never,_id:string,v:number){if(!this.prescription||this.prescription.status!=='DRAFT'||this.prescription.draftVersion!==v)return false;this.prescription.draftVersion++;return true;}
  async issue(_:never,v:{id:string;expectedVersion:number;issuedAt:Date;issuedByAccountId:string;issueIdempotencyKey:string;snapshot:Record<string,unknown>;hash:string}){if(!this.prescription||this.prescription.status!=='DRAFT'||this.prescription.draftVersion!==v.expectedVersion)return false;Object.assign(this.prescription,{status:'ISSUED',issuedAt:v.issuedAt,issuedByAccountId:v.issuedByAccountId,finalSnapshot:v.snapshot,finalSnapshotHash:v.hash});(this.prescription as Prescription & {issueKey:string}).issueKey=v.issueIdempotencyKey;return true;} async appendAudit(_:never,e:{eventType:string}){this.audits.push(e.eventType);}
}
describe('appointment prescriptions',()=>{
  it('allows only assigned doctor mutations and keeps drafts patient-private',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r);await expect(s.create('patient','a',{idempotencyKey:'c',items:[item()]})).rejects.toMatchObject({code:'FORBIDDEN'});await s.create('doctor','a',{idempotencyKey:'c',items:[item()]});await expect(s.get('patient','a')).rejects.toMatchObject({code:'FORBIDDEN'});expect(r.audits).toContain('PRESCRIPTION_ACCESS_DENIED');});
  it('uses the immutable create fingerprint after draft updates',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r),first=item(),changed={...item(),medicineName:'Changed'};await s.create('doctor','a',{idempotencyKey:'c',items:[first]});await s.update('doctor','a',{expectedDraftVersion:1,items:[changed]});expect((await s.create('doctor','a',{idempotencyKey:'c',items:[first]})).replayed).toBe(true);await expect(s.create('doctor','a',{idempotencyKey:'c',items:[changed]})).rejects.toMatchObject({code:'CONFLICT'});});
  it('gives doctor authority precedence when the account owns both profiles',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r);await s.create('doctor','a',{idempotencyKey:'c',items:[item()]});r.doctorAlsoPatient=true;expect((await s.get('doctor','a')).status).toBe('DRAFT');await expect(s.get('patient','a')).rejects.toMatchObject({code:'FORBIDDEN'});expect(r.audits).toContain('PRESCRIPTION_ACCESS_DENIED');});
  it('replays creation, enforces versioning, issues deterministically, and preserves issued immutability',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r);const created=await s.create('doctor','a',{idempotencyKey:'c',items:[item()]});expect((await s.create('doctor','a',{idempotencyKey:'c',items:[item()]})).replayed).toBe(true);const updated=await s.update('doctor','a',{expectedDraftVersion:1,items:[item()]});await expect(s.update('doctor','a',{expectedDraftVersion:1,items:[item()]})).rejects.toMatchObject({code:'CONFLICT'});const issued=await s.issue('doctor','a','i');expect(issued.prescription.finalSnapshotHash).toMatch(/^[0-9a-f]{64}$/);expect((await s.issue('doctor','a','i')).replayed).toBe(true);await expect(s.update('doctor','a',{expectedDraftVersion:updated.draftVersion,items:[item()]})).rejects.toMatchObject({code:'CONFLICT'});expect(created.prescription.appointmentId).toBe('a');expect(r.audits).toEqual(expect.arrayContaining(['PRESCRIPTION_CREATED','PRESCRIPTION_DRAFT_UPDATED','PRESCRIPTION_ISSUED']));});
  it('rejects cancelled and clinic-only appointment contexts',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r);r.accessValue={...r.accessValue!,status:'CANCELLED'};await expect(s.create('doctor','a',{idempotencyKey:'c'})).rejects.toMatchObject({code:'CONFLICT'});r.accessValue=null;await expect(s.create('doctor','a',{idempotencyKey:'x'})).rejects.toMatchObject({code:'FORBIDDEN'});});
  it('maps only relevant PostgreSQL uniqueness races and replays the committed create',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r);let racing=true;const findKey=r.findByCreateKey.bind(r),find=r.find.bind(r);r.findByCreateKey=async(db,account,key)=>racing?null:findKey(db,account,key);r.find=async(db,appointmentId)=>racing?null:find(db,appointmentId);r.create=async(_db,value)=>{r.prescription={...value,items:[{id:'i0',...item()}]};(r.prescription as Prescription & {createKey:string}).createKey=value.createIdempotencyKey;racing=false;throw Object.assign(new Error('unique'),{code:'23505',constraint:'prescriptions_created_by_account_id_create_idempotency_key_key'});};expect((await s.create('doctor','a',{idempotencyKey:'c',items:[item()]})).replayed).toBe(true);racing=true;r.create=async()=>{throw Object.assign(new Error('other unique'),{code:'23505',constraint:'unrelated_unique'});};await expect(s.create('doctor','a',{idempotencyKey:'different',items:[item()]})).rejects.toMatchObject({code:'23505'});});
  it('replays a committed issue after the relevant uniqueness race',async()=>{const r=new Repo(),s=new AppointmentPrescriptionService(r);await s.create('doctor','a',{idempotencyKey:'c',items:[item()]});let visible=false;const findIssue=r.findByIssueKey.bind(r);r.findByIssueKey=async(db,account,key)=>visible?findIssue(db,account,key):null;r.issue=async(_db,value)=>{Object.assign(r.prescription!,{status:'ISSUED',issuedAt:value.issuedAt,issuedByAccountId:value.issuedByAccountId,finalSnapshot:value.snapshot,finalSnapshotHash:value.hash});(r.prescription as Prescription & {issueKey:string}).issueKey=value.issueIdempotencyKey;visible=true;throw Object.assign(new Error('unique'),{code:'23505',constraint:'prescriptions_issue_idempotency_unique'});};expect((await s.issue('doctor','a','i')).replayed).toBe(true);});
});
