import { describe, expect, it } from 'vitest';
import { AvailabilityError, AvailabilityService, type AvailabilityConfiguration, type AvailabilityOwner, type AvailabilityRepository } from '../src/modules/availability/availability.js';
import { canonicalizeWeeklyRecurrence } from '../src/modules/availability/recurrence.js';
import { localToUtcEarlier } from '../src/modules/availability/timezone.js';

class Repository implements AvailabilityRepository {
  public records = new Map<string, AvailabilityConfiguration>(); public owners = new Map<string, AvailabilityOwner>([['doctor-version', { kind: 'DOCTOR' }], ['clinic-version', { kind: 'CLINIC', tenantId: 'tenant-a' }]]);
  async transaction<T>(operation: Parameters<AvailabilityRepository['transaction']>[0]): Promise<T> { return operation({ query: async () => ({ rows: [], rowCount: 0 }) }); }
  async findVersionOwnerForDoctor(version: string, account: string) { return version === 'doctor-version' && account === 'doctor-account' ? { kind: 'DOCTOR' as const } : null; }
  async findVersionOwner(version: string) { return this.owners.get(version) ?? null; }
  async create(_database: unknown, value: AvailabilityConfiguration) { if (this.records.has(value.serviceOfferingVersionId)) throw { code: '23505' }; this.records.set(value.serviceOfferingVersionId, value); }
  async findManaged(version: string) { return this.records.get(version) ?? null; }
}
function setup() { const repository = new Repository(); const audit = { events: [] as unknown[], append: async (event: unknown) => { audit.events.push(event); } }; const context = { require: async (account: string, tenant: string, permission: string) => { if (account !== 'clinic-owner' || tenant !== 'tenant-a' || permission !== 'clinic.manage') throw new Error('FORBIDDEN'); return { id: 'membership', accountId: account, tenantId: tenant, role: 'CLINIC_OWNER' as const, status: 'ACTIVE' as const }; } }; return { repository, audit, service: new AvailabilityService(repository, context, audit) }; }
const base = { providerTimezone: 'Asia/Kolkata', slotDurationSeconds: 1800, bufferBeforeSeconds: 0, bufferAfterSeconds: 0, capacity: 1, bookingLeadTimeSeconds: 0, bookingHorizonSeconds: 86_400, rules: [{ recurrence: 'BYDAY=WE,MO;FREQ=WEEKLY', effectiveFrom: new Date('2026-10-01T00:00:00Z'), windows: [{ kind: 'WORKING' as const, weekday: 1, startSeconds: 32400, endSeconds: 61200 }, { kind: 'BREAK' as const, weekday: 1, startSeconds: 43200, endSeconds: 45000 }] }] };

describe('theCliniQ Phase 5 Step 2 Availability Foundation', () => {
  it('canonicalizes only controlled weekly recurrence identities', () => { expect(canonicalizeWeeklyRecurrence('BYDAY=WE,MO;FREQ=WEEKLY')).toMatchObject({ canonical: 'FREQ=WEEKLY;BYDAY=MO,WE' }); expect(() => canonicalizeWeeklyRecurrence('FREQ=MONTHLY;BYDAY=MO')).toThrow(); });
  it('validates immutable configuration vocabulary, windows, and break containment', async () => { const { service } = setup(); await expect(service.create('doctor-account', 'doctor-version', base)).resolves.toMatchObject({ providerTimezone: 'Asia/Kolkata' }); await expect(service.create('doctor-account', 'new-version', { ...base, slotDurationSeconds: 0 })).rejects.toBeInstanceOf(AvailabilityError); await expect(service.create('doctor-account', 'new-version', { ...base, rules: [{ ...base.rules[0], windows: [{ kind: 'BREAK', weekday: 1, startSeconds: 1, endSeconds: 2 }] }] })).rejects.toBeInstanceOf(AvailabilityError); });
  it('enforces doctor ownership and clinic.manage without tenant context becoming authority', async () => { const { service } = setup(); await expect(service.create('other-doctor', 'doctor-version', base)).rejects.toMatchObject({ code: 'FORBIDDEN' }); await expect(service.create('clinic-owner', 'clinic-version', base)).resolves.toMatchObject({ serviceOfferingVersionId: 'clinic-version' }); await expect(service.create('clinic-staff', 'clinic-version', base)).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('derives exception UTC from local input using IANA rules and rejects nonexistent time', async () => { expect(localToUtcEarlier('2026-11-01T01:30:00', 'America/New_York').toISOString()).toBe('2026-11-01T05:30:00.000Z'); expect(() => localToUtcEarlier('2026-03-08T02:30:00', 'America/New_York')).toThrow(); const { service } = setup(); const result = await service.create('doctor-account', 'doctor-version', { ...base, exceptions: [{ kind: 'ONE_OFF', localStart: '2027-01-01T10:00:00', localEnd: '2027-01-01T11:00:00' }] }); expect(result.exceptions[0].derivedStartUtc).toBeInstanceOf(Date); });
});
