import { MembershipAccessError, MembershipService, TenantContextService, secretHash, type MembershipRepository, type TenantInvitation, type TenantMembership } from '../src/modules/memberships/memberships.js';
import { describe, expect, it } from 'vitest';

type Invitation = TenantInvitation & { secretHash: string; createdByAccountId: string; acceptedByAccountId?: string };
function setup() {
  const rows = new Map<string, TenantMembership>(); const invitations = new Map<string, Invitation>();
  const repository: MembershipRepository = {
    transaction: async (operation) => operation({ query: async () => ({ rows: [] }) }),
    findActiveContext: async (accountId, tenantId) => [...rows.values()].find((row) => row.accountId === accountId && row.tenantId === tenantId && row.status === 'ACTIVE') ?? null,
    findActiveContextForUpdate: async (_db, accountId, tenantId) => [...rows.values()].find((row) => row.accountId === accountId && row.tenantId === tenantId && row.status === 'ACTIVE') ?? null,
    createInvitation: async (_db, value) => { invitations.set(value.id, value); }, lockInvitation: async (_db, id) => invitations.get(id) ?? null,
    activeMembership: async (_db, tenantId, accountId) => [...rows.values()].find((row) => row.tenantId === tenantId && row.accountId === accountId && ['ACTIVE', 'INVITED'].includes(row.status)) ?? null,
    activateMembership: async (_db, tenantId, accountId, role) => { const row = { id: `m-${rows.size}`, accountId, tenantId, role, status: 'ACTIVE' as const }; rows.set(row.id, row); return row; },
    acceptInvitation: async (_db, id, accountId) => { const invitation = invitations.get(id)!; invitation.status = 'ACCEPTED'; invitation.acceptedByAccountId = accountId; },
    setInvitationStatus: async (_db, id, status) => { invitations.get(id)!.status = status; },
    lockActiveOwners: async (_db, tenantId) => [...rows.values()].filter((row) => row.tenantId === tenantId && row.role === 'CLINIC_OWNER' && row.status === 'ACTIVE'),
    lockMembership: async (_db, tenantId, id) => rows.get(id)?.tenantId === tenantId ? rows.get(id)! : null,
    updateMembership: async (_db, tenantId, id, status, role) => { const row = rows.get(id); if (!row || row.tenantId !== tenantId) return null; row.status = status; row.role = role; return row; },
  };
  const audit = { events: [] as { eventType: string }[], append: async (event: { eventType: string }) => { audit.events.push(event); } };
  const context = new TenantContextService(repository, audit); return { rows, invitations, audit, service: new MembershipService(repository, context, audit) };
}
function owner(rows: Map<string, TenantMembership>, id: string, accountId = id) { rows.set(id, { id, accountId, tenantId: 'tenant', role: 'CLINIC_OWNER', status: 'ACTIVE' }); }
function admin(rows: Map<string, TenantMembership>, id: string, accountId = id) { rows.set(id, { id, accountId, tenantId: 'tenant', role: 'CLINIC_ADMIN', status: 'ACTIVE' }); }
describe('Step 6-8 membership security', () => {
  it('denies admin self-promotion and promotion of another member, but permits owner promotion', async () => { const { rows, service, audit } = setup(); owner(rows, 'owner'); admin(rows, 'admin'); rows.set('staff', { id: 'staff', accountId: 'staff', tenantId: 'tenant', role: 'CLINIC_STAFF', status: 'ACTIVE' }); await expect(service.change('admin', 'tenant', 'admin', 'ACTIVE', 'CLINIC_OWNER')).rejects.toBeInstanceOf(MembershipAccessError); await expect(service.change('admin', 'tenant', 'staff', 'ACTIVE', 'CLINIC_OWNER')).rejects.toBeInstanceOf(MembershipAccessError); await expect(service.change('owner', 'tenant', 'staff', 'ACTIVE', 'CLINIC_OWNER')).resolves.toMatchObject({ role: 'CLINIC_OWNER' }); expect(audit.events.filter((event) => event.eventType === 'TENANT_MEMBERSHIP_CHANGE_DENIED')).toHaveLength(2); });
  it('denies an admin owner invitation and permits an owner invitation', async () => { const { rows, audit, service } = setup(); owner(rows, 'owner'); admin(rows, 'admin'); await expect(service.invite('admin', 'tenant', 'target-a', 'CLINIC_OWNER', new Date(Date.now() + 60_000))).rejects.toBeInstanceOf(MembershipAccessError); await expect(service.invite('owner', 'tenant', 'target-b', 'CLINIC_OWNER', new Date(Date.now() + 60_000))).resolves.toMatchObject({ invitation: { role: 'CLINIC_OWNER' } }); expect(audit.events.some((event) => event.eventType === 'TENANT_INVITATION_CREATE_DENIED')).toBe(true); });
  it('protects the final owner and permits owner removal when another owner remains', async () => { const { rows, service } = setup(); owner(rows, 'owner-a'); await expect(service.change('owner-a', 'tenant', 'owner-a', 'REMOVED', 'CLINIC_OWNER')).rejects.toBeInstanceOf(MembershipAccessError); owner(rows, 'owner-b'); await expect(service.change('owner-a', 'tenant', 'owner-b', 'REMOVED', 'CLINIC_OWNER')).resolves.toMatchObject({ status: 'REMOVED' }); });
  it('hashes secrets, binds acceptance, rejects replay, and audits denied acceptance', async () => { const { rows, invitations, audit, service } = setup(); owner(rows, 'owner'); const created = await service.invite('owner', 'tenant', 'target', 'DOCTOR', new Date(Date.now() + 60_000)); expect(invitations.get(created.invitation.id)?.secretHash).toBe(secretHash(created.secret)); await expect(service.accept('other', created.invitation.id, created.secret)).rejects.toBeInstanceOf(MembershipAccessError); await expect(service.accept('target', created.invitation.id, created.secret)).resolves.toMatchObject({ accountId: 'target' }); await expect(service.accept('target', created.invitation.id, created.secret)).rejects.toBeInstanceOf(MembershipAccessError); expect(audit.events.filter((event) => event.eventType === 'TENANT_INVITATION_ACCEPT_DENIED')).toHaveLength(2); });
  it('rejects and revokes invitations only through tenant authority', async () => { const { rows, invitations, audit, service } = setup(); owner(rows, 'owner'); const rejected = await service.invite('owner', 'tenant', 'target-a', 'DOCTOR', new Date(Date.now() + 60_000)); await expect(service.reject('target-a', rejected.invitation.id)).rejects.toBeInstanceOf(MembershipAccessError); expect(invitations.get(rejected.invitation.id)?.status).toBe('INVITED'); await service.reject('owner', rejected.invitation.id); expect(invitations.get(rejected.invitation.id)?.status).toBe('REJECTED'); const revoked = await service.invite('owner', 'tenant', 'target-b', 'DOCTOR', new Date(Date.now() + 60_000)); await service.revoke('owner', revoked.invitation.id); expect(invitations.get(revoked.invitation.id)?.status).toBe('REVOKED'); await expect(service.accept('target-a', rejected.invitation.id, 'x')).rejects.toBeInstanceOf(MembershipAccessError); await expect(service.accept('target-b', revoked.invitation.id, 'x')).rejects.toBeInstanceOf(MembershipAccessError); expect(audit.events.some((event) => event.eventType === 'TENANT_INVITATION_REJECTED')).toBe(true); expect(audit.events.some((event) => event.eventType === 'TENANT_INVITATION_REVOKED')).toBe(true); expect(audit.events.some((event) => event.eventType === 'TENANT_INVITATION_LIFECYCLE_DENIED')).toBe(true); });
  it('atomically expires an invitation when encountered and denies acceptance', async () => { const { rows, invitations, audit, service } = setup(); owner(rows, 'owner'); const created = await service.invite('owner', 'tenant', 'target', 'DOCTOR', new Date(Date.now() + 1)); await new Promise((resolve) => setTimeout(resolve, 5)); await expect(service.accept('target', created.invitation.id, created.secret)).rejects.toBeInstanceOf(MembershipAccessError); expect(invitations.get(created.invitation.id)?.status).toBe('EXPIRED'); expect(audit.events.some((event) => event.eventType === 'TENANT_INVITATION_EXPIRED')).toBe(true); });
});
