import { describe, expect, it } from 'vitest';
import { NetworkError, NetworkService, type Connection, type NetworkRepository, type Party, type Proposal } from '../src/modules/network/network.js';

class Repository implements NetworkRepository {
  public connections = new Map<string, Connection>(); public proposals = new Map<string, Proposal>(); public capabilities = new Set<string>(); public clinics = new Map<string, Party>(); public doctors = new Map<string, { account: string; party: Party; eligible: boolean }>();
  async transaction<T>(operation: (database: { query: () => Promise<{ rows: unknown[]; rowCount: number }> }) => Promise<T>): Promise<T> { return operation({ query: async () => ({ rows: [], rowCount: 0 }) }); }
  async clinic(_db: unknown, id: string) { return [...this.clinics.values()].find((p) => p.id === id) ?? null; }
  async ownedEligibleDoctor(_db: unknown, account: string, id: string) { const doctor = this.doctors.get(id); return doctor?.account === account && doctor.eligible ? doctor.party : null; } async eligibleDoctor(_db: unknown, id: string) { const doctor = this.doctors.get(id); return doctor?.eligible ? doctor.party : null; }
  async create(_db: unknown, connection: Connection) { if ([...this.connections.values()].some((item) => item.status === 'REQUESTED' || item.status === 'ACCEPTED')) throw new Error('duplicate'); this.connections.set(connection.id, connection); }
  async lockConnection(_db: unknown, id: string) { return this.connections.get(id) ?? null; } async updateConnection(_db: unknown, id: string, from: Connection['status'], to: Connection['status']) { const c = this.connections.get(id); if (!c || c.status !== from) return false; this.connections.set(id, { ...c, status: to }); return true; } async appendConnectionEvent() {}
  async createProposal(_db: unknown, proposal: Proposal) { if ([...this.proposals.values()].some((p) => p.connectionId === proposal.connectionId && p.capability === proposal.capability && p.status === 'PENDING')) throw new Error('duplicate'); this.proposals.set(proposal.id, proposal); }
  async lockProposal(_db: unknown, id: string) { return this.proposals.get(id) ?? null; } async acceptProposal(_db: unknown, proposal: Proposal) { const current = this.proposals.get(proposal.id); if (!current || current.status !== 'PENDING') return false; this.proposals.set(proposal.id, { ...current, status: 'ACCEPTED' }); this.capabilities.add(`${proposal.connectionId}:${proposal.capability}`); return true; } async revokeCapability(_db: unknown, connectionId: string, capability: 'DISCOVER' | 'CONTACT') { return this.capabilities.delete(`${connectionId}:${capability}`); }
}
function setup() { const repository = new Repository(); const audit = { events: [] as unknown[], append: async (e: unknown) => { audit.events.push(e); } }; const allowed = new Set(['a:tenant-a','b:tenant-b']); const context = { require: async (accountId: string, tenantId: string, permission: string) => { if (permission !== 'network.manage' || !allowed.has(`${accountId}:${tenantId}`)) throw new Error('FORBIDDEN'); return { accountId, tenantId, role: 'CLINIC_OWNER' as const, status: 'ACTIVE' as const, id: 'membership' }; } }; repository.clinics.set('a:clinic-a', { kind: 'CLINIC', id: 'clinic-a', tenantId: 'tenant-a' }); repository.clinics.set('b:clinic-b', { kind: 'CLINIC', id: 'clinic-b', tenantId: 'tenant-b' }); repository.doctors.set('doctor-x', { account: 'doctor', eligible: true, party: { kind: 'DOCTOR', id: 'doctor-x' } }); return { repository, audit, allowed, service: new NetworkService(repository, context, audit) }; }
describe('Phase 2 Steps 9-12 network authorization', () => {
  it('supports clinic to clinic request, accept, and revocation while rejecting replay', async () => { const { service } = setup(); const c = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'CLINIC', clinicId: 'clinic-b' }); await service.accept('b', c.id); await service.revoke('a', c.id); await expect(service.accept('b', c.id)).rejects.toBeInstanceOf(NetworkError); });
  it('supports clinic to active verified independent doctor without tenant membership', async () => { const { service } = setup(); const c = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' }); await expect(service.accept('doctor', c.id)).resolves.toBeUndefined(); });
  it('denies doctor-to-doctor, self, cross-account clinic use, and ineligible doctors', async () => { const { service, repository } = setup(); await expect(service.request('doctor', { kind: 'DOCTOR', doctorProfileId: 'doctor-x' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' })).rejects.toBeInstanceOf(NetworkError); await expect(service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'CLINIC', clinicId: 'clinic-a' })).rejects.toBeInstanceOf(NetworkError); await expect(service.request('a', { kind: 'CLINIC', clinicId: 'clinic-b' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' })).rejects.toBeInstanceOf(NetworkError); repository.doctors.get('doctor-x')!.eligible = false; await expect(service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' })).rejects.toBeInstanceOf(NetworkError); });
  it('denies every non-eligible doctor state and profile impersonation', async () => { const { service, repository } = setup(); for (const state of ['DRAFT', 'PENDING_VERIFICATION', 'UNVERIFIED', 'SUSPENDED', 'INACTIVE']) { repository.doctors.set(`doctor-${state}`, { account: `account-${state}`, eligible: false, party: { kind: 'DOCTOR', id: `doctor-${state}` } }); await expect(service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'DOCTOR', doctorProfileId: `doctor-${state}` })).rejects.toBeInstanceOf(NetworkError); } await expect(service.request('imposter', { kind: 'DOCTOR', doctorProfileId: 'doctor-x' }, { kind: 'CLINIC', clinicId: 'clinic-a' })).rejects.toBeInstanceOf(NetworkError); });
  it('revalidates doctor eligibility for every sensitive operation', async () => { const { service, repository } = setup(); const c = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' }); repository.doctors.get('doctor-x')!.eligible = false; await expect(service.accept('doctor', c.id)).rejects.toBeInstanceOf(NetworkError); repository.doctors.get('doctor-x')!.eligible = true; await service.accept('doctor', c.id); repository.doctors.get('doctor-x')!.eligible = false; await expect(service.propose('doctor', c.id, 'CONTACT')).rejects.toBeInstanceOf(NetworkError); });
  it('uses network.manage for clinic parties but never requires tenant authority for an independent doctor', async () => { const { service, allowed } = setup(); allowed.delete('a:tenant-a'); await expect(service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' })).rejects.toBeInstanceOf(NetworkError); await expect(service.request('doctor', { kind: 'DOCTOR', doctorProfileId: 'doctor-x' }, { kind: 'CLINIC', clinicId: 'clinic-a' })).resolves.toBeTruthy(); });
  it('allows only the recipient to accept or reject and only participants to revoke', async () => { const { service } = setup(); const accepted = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'CLINIC', clinicId: 'clinic-b' }); await expect(service.accept('a', accepted.id)).rejects.toBeInstanceOf(NetworkError); await expect(service.accept('other', accepted.id)).rejects.toBeInstanceOf(NetworkError); await service.accept('b', accepted.id); await expect(service.revoke('other', accepted.id)).rejects.toBeInstanceOf(NetworkError); await service.revoke('b', accepted.id); const rejected = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'CLINIC', clinicId: 'clinic-b' }); await expect(service.reject('a', rejected.id)).rejects.toBeInstanceOf(NetworkError); await service.reject('b', rejected.id); await expect(service.accept('b', rejected.id)).rejects.toBeInstanceOf(NetworkError); });
  it('requires bilateral acceptance and a fresh proposal after revocation', async () => { const { service, repository } = setup(); const c = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'DOCTOR', doctorProfileId: 'doctor-x' }); await service.accept('doctor', c.id); const proposal = await service.propose('a', c.id, 'DISCOVER'); expect(repository.capabilities.size).toBe(0); await expect(service.acceptCapability('a', c.id, proposal.id)).rejects.toBeInstanceOf(NetworkError); await service.acceptCapability('doctor', c.id, proposal.id); expect(repository.capabilities.has(`${c.id}:DISCOVER`)).toBe(true); await service.revokeCapability('a', c.id, 'DISCOVER'); expect(repository.capabilities.has(`${c.id}:DISCOVER`)).toBe(false); await expect(service.acceptCapability('doctor', c.id, proposal.id)).rejects.toBeInstanceOf(NetworkError); await expect(service.propose('a', c.id, 'REFER')).rejects.toBeInstanceOf(NetworkError); });
  it('audits successful and denied network operations', async () => { const { service, audit } = setup(); const c = await service.request('a', { kind: 'CLINIC', clinicId: 'clinic-a' }, { kind: 'CLINIC', clinicId: 'clinic-b' }); await expect(service.accept('a', c.id)).rejects.toBeInstanceOf(NetworkError); await service.accept('b', c.id); expect(audit.events).toEqual(expect.arrayContaining([expect.objectContaining({ eventType: 'NETWORK_REQUESTED', outcome: 'SUCCESS' }), expect.objectContaining({ eventType: 'NETWORK_ACCESS_DENIED', outcome: 'DENIED' }), expect.objectContaining({ eventType: 'NETWORK_ACCEPTED', outcome: 'SUCCESS' })])); });
});
