import { TenantAccessError, TenantClinicService, type Clinic, type ClinicInput, type TenantRepository } from '../src/modules/tenants/tenants.js';
import { describe, expect, it } from 'vitest';
class Repository implements TenantRepository { public clinics = new Map<string, Clinic>(); public transactions = 0; async transaction<T>(operation: Parameters<TenantRepository['transaction']>[0]) { this.transactions += 1; return operation({ query: async () => ({ rows: [] }) }) as T; } async create(_db: unknown, account: string, input: ClinicInput) { const clinic = { id: `clinic-${this.clinics.size}`, tenantId: `tenant-${this.clinics.size}`, status: 'DRAFT' as const, legalName: input.legalName, displayName: input.displayName }; (clinic as Clinic & { account: string }).account = account; this.clinics.set(clinic.id, clinic); return clinic; } async findForCreator(id: string, account: string) { const clinic = this.clinics.get(id) as (Clinic & { account?: string }) | undefined; return clinic?.account === account ? clinic : null; } async updateForCreator(id: string, account: string, input: ClinicInput) { const clinic = await this.findForCreator(id, account); if (!clinic) return null; const updated = { ...clinic, ...input }; this.clinics.set(id, updated); return updated; } }
function setup() { const repository = new Repository(); const audit = { events: [] as unknown[], append: async (event: unknown) => { audit.events.push(event); } }; return { repository, audit, service: new TenantClinicService(repository, audit) }; }
describe('Step 5 tenant and clinic foundations', () => {
  it('creates a tenant and clinic atomically from the authenticated creator', async () => { const { service, repository } = setup(); const clinic = await service.create('account-a', { legalName: 'Legal', displayName: 'Clinic' }); expect(clinic.tenantId).toBeTruthy(); expect(repository.transactions).toBe(1); });
  it('denies cross-account clinic reads and updates without leaking ownership', async () => { const { service, audit } = setup(); const clinic = await service.create('account-a', { legalName: 'Legal', displayName: 'Clinic' }); await expect(service.read('account-b', clinic.id)).rejects.toBeInstanceOf(TenantAccessError); await expect(service.update('account-b', clinic.id, { legalName: 'Other', displayName: 'Other' })).rejects.toBeInstanceOf(TenantAccessError); expect(audit.events).toHaveLength(3); });
  it('rejects unauthenticated creation', async () => { const { service } = setup(); await expect(service.create(undefined, { legalName: 'Legal', displayName: 'Clinic' })).rejects.toBeInstanceOf(TenantAccessError); });
});
