import type { DatabaseHealth } from '../../infrastructure/database.js';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { FinancialAdjustment, FinancialRepository, PaymentIntent, PaymentIntentStatus, WebhookEvent, WebhookStatus } from './financial.js';

/** PostgreSQL owns idempotency and state-transition compare-and-set semantics. */
export class PostgresFinancialRepository implements FinancialRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public async transaction<T>(operation: (repository: FinancialRepository) => Promise<T>): Promise<T> {
    return this.database.transaction(async (database) => {
      const transactional = new PostgresFinancialRepository({
        query: database.query,
        transaction: async <U>(nested: (repository: FinancialRepository) => Promise<U>): Promise<U> => nested(transactional),
      } as unknown as DatabaseHealth);
      return operation(transactional);
    });
  }
  public async saveAllocation(snapshot: { id: string; gross: { amountMinor: bigint; currency: string }; platformCommission: { amountMinor: bigint }; providerPayable: { amountMinor: bigint }; selectedRuleVersionId: string; calculationBasis: string; createdAt: Date }): Promise<void> {
    await this.database.query('INSERT INTO financial_allocation_snapshots (id,status,currency,gross_amount_minor,calculation_basis,selected_rule_versions,created_at) VALUES ($1,\'FINAL\',$2,$3,$4,jsonb_build_array($5),$6)', [snapshot.id, snapshot.gross.currency, snapshot.gross.amountMinor, snapshot.calculationBasis, snapshot.selectedRuleVersionId, snapshot.createdAt]);
    await this.database.query('INSERT INTO financial_allocation_components (id,allocation_snapshot_id,component_type,amount_minor,currency) VALUES ($1,$2,\'GROSS\',$3,$4),($5,$2,\'PLATFORM_COMMISSION\',$6,$4),($7,$2,\'PROVIDER_PAYABLE\',$8,$4)', [createIdentifier(), snapshot.id, snapshot.gross.amountMinor, snapshot.gross.currency, createIdentifier(), snapshot.platformCommission.amountMinor, createIdentifier(), snapshot.providerPayable.amountMinor]);
  }
  public async findIntent(providerKey: string, idempotencyKey: string): Promise<PaymentIntent | null> { const result = await this.database.query('SELECT id,provider_key,idempotency_key,currency,amount_minor,allocation_snapshot_id,status FROM payment_intents WHERE provider_key=$1 AND idempotency_key=$2 FOR UPDATE', [providerKey, idempotencyKey]); return intent(result.rows[0] as Record<string, unknown> | undefined); }
  public async saveIntent(value: PaymentIntent): Promise<void> { await this.database.query('INSERT INTO payment_intents (id,provider_key,status,currency,amount_minor,allocation_snapshot_id,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7)', [value.id, value.providerKey, value.status, value.amount.currency, value.amount.amountMinor, value.allocationSnapshotId ?? null, value.idempotencyKey]); }
  public async updateIntent(id: string, from: PaymentIntentStatus, to: PaymentIntentStatus): Promise<boolean> { const result = await this.database.query('UPDATE payment_intents SET status=$3,updated_at=current_timestamp,reconciliation_required_at=CASE WHEN $3=\'RECONCILIATION_REQUIRED\' THEN current_timestamp ELSE reconciliation_required_at END WHERE id=$1 AND status=$2', [id, from, to]); return result.rowCount === 1; }
  public async findWebhook(providerKey: string, providerEventId: string): Promise<WebhookEvent | null> { const result = await this.database.query('SELECT id,provider_key,provider_event_id,event_type,payload,payload_raw,payload_hash,status,handler_version FROM provider_webhook_events WHERE provider_key=$1 AND provider_event_id=$2 FOR UPDATE', [providerKey, providerEventId]); return webhook(result.rows[0] as Record<string, unknown> | undefined); }
  public async saveWebhook(value: WebhookEvent): Promise<void> { await this.database.query('INSERT INTO provider_webhook_events (id,provider_key,provider_event_id,event_type,handler_version,status,payload,payload_raw,payload_hash,authenticated_at,persisted_at) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,current_timestamp,current_timestamp)', [value.id, value.providerKey, value.providerEventId, value.eventType, value.handlerVersion, value.status, JSON.stringify(value.payload), value.payloadRaw, value.payloadHash]); }
  public async transitionWebhook(id: string, from: WebhookStatus, to: WebhookStatus): Promise<boolean> { const result = await this.database.query('UPDATE provider_webhook_events SET status=$3,processing_started_at=CASE WHEN $3=\'PROCESSING\' THEN current_timestamp ELSE processing_started_at END,processed_at=CASE WHEN $3 IN (\'PROCESSED\',\'UNKNOWN\') THEN current_timestamp ELSE processed_at END,reconciliation_required_at=CASE WHEN $3=\'RECONCILIATION_REQUIRED\' THEN current_timestamp ELSE reconciliation_required_at END WHERE id=$1 AND status=$2', [id, from, to]); return result.rowCount === 1; }
  public async saveAdjustment(value: FinancialAdjustment): Promise<void> { await this.database.query('INSERT INTO financial_adjustments (id,allocation_snapshot_id,status,category,affected_component_type,currency,amount_minor,reason,reference_context,requested_by_account_id) VALUES ($1,$2,$3,$4,$5,\'INR\',$6,$7,$8,$9)', [value.id,value.allocationSnapshotId,value.status,value.category,value.component,value.amountMinor,value.reason,value.reference,value.requestedByAccountId]); }
  public async findAdjustment(id: string): Promise<FinancialAdjustment | null> { const result = await this.database.query('SELECT id,allocation_snapshot_id,requested_by_account_id,amount_minor,category,affected_component_type,reason,reference_context,status FROM financial_adjustments WHERE id=$1 FOR UPDATE', [id]); const row = result.rows[0] as Record<string, unknown> | undefined; return row ? { id: String(row.id), allocationSnapshotId: String(row.allocation_snapshot_id), requestedByAccountId: String(row.requested_by_account_id), amountMinor: BigInt(String(row.amount_minor)), category: String(row.category), component: String(row.affected_component_type), reason: String(row.reason), reference: String(row.reference_context), status: row.status as FinancialAdjustment['status'] } : null; }
  public async approveAdjustment(id: string, approverAccountId: string): Promise<boolean> { const result = await this.database.query("UPDATE financial_adjustments SET status = 'APPROVED' WHERE id=$1 AND status='REQUESTED'", [id]); if (result.rowCount !== 1) return false; await this.database.query("INSERT INTO financial_adjustment_approvals (id,financial_adjustment_id,decision,approver_account_id) VALUES ($1,$2,'APPROVED',$3)", [createIdentifier(), id, approverAccountId]); return true; }
}
function intent(row: Record<string, unknown> | undefined): PaymentIntent | null { return row ? { id: String(row.id), providerKey: String(row.provider_key), idempotencyKey: String(row.idempotency_key), amount: { amountMinor: BigInt(String(row.amount_minor)), currency: String(row.currency) }, allocationSnapshotId: row.allocation_snapshot_id ? String(row.allocation_snapshot_id) : undefined, status: row.status as PaymentIntentStatus } : null; }
function webhook(row: Record<string, unknown> | undefined): WebhookEvent | null { return row ? { id: String(row.id), providerKey: String(row.provider_key), providerEventId: String(row.provider_event_id), eventType: String(row.event_type), payload: (row.payload && typeof row.payload === 'object' ? row.payload : {}) as Record<string, unknown>, payloadRaw: String(row.payload_raw), payloadHash: String(row.payload_hash), status: row.status as WebhookStatus, handlerVersion: String(row.handler_version) } : null; }
