import type { DatabaseHealth } from '../../infrastructure/database.js';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { ServiceOffering, ServiceOfferingMutation, ServiceOfferingRepository, ServiceOfferingVersion } from './service-offerings.js';

export class PostgresServiceOfferingRepository implements ServiceOfferingRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public async transaction<T>(operation: (database: PostgresExecutor) => Promise<T>): Promise<T> { return this.database.transaction(operation); }
  public async find(id: string): Promise<ServiceOffering | null> { return offering(await this.database.query('SELECT offering.id, offering.owner_doctor_profile_id, offering.owner_clinic_id, clinic.tenant_id, offering.name, offering.description, offering.status FROM service_offerings offering LEFT JOIN clinics clinic ON clinic.id = offering.owner_clinic_id WHERE offering.id = $1', [id])); }
  public async findDoctorOwnedForAccount(id: string, accountId: string): Promise<ServiceOffering | null> { return offering(await this.database.query('SELECT offering.id, offering.owner_doctor_profile_id, offering.owner_clinic_id, NULL::uuid AS tenant_id, offering.name, offering.description, offering.status FROM service_offerings offering JOIN doctor_profiles doctor ON doctor.id = offering.owner_doctor_profile_id WHERE offering.id = $1 AND doctor.account_id = $2', [id, accountId])); }
  public async create(database: PostgresExecutor, value: ServiceOffering, actorAccountId: string): Promise<void> { await database.query('INSERT INTO service_offerings (id,owner_doctor_profile_id,owner_clinic_id,name,description,status,created_by_account_id,updated_by_account_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$7)', [value.id, value.owner.kind === 'DOCTOR' ? value.owner.doctorProfileId : null, value.owner.kind === 'CLINIC' ? value.owner.clinicId : null, value.name, value.description, value.status, actorAccountId]); }
  public async update(database: PostgresExecutor, id: string, mutation: ServiceOfferingMutation, actorAccountId: string): Promise<ServiceOffering | null> { return offering(await database.query('UPDATE service_offerings SET name=$2, description=$3, status=$4, updated_by_account_id=$5, updated_at=current_timestamp WHERE id=$1 RETURNING id, owner_doctor_profile_id, owner_clinic_id, NULL::uuid AS tenant_id, name, description, status', [id, mutation.name, mutation.description ?? null, mutation.status, actorAccountId])); }
  public async createVersion(database: PostgresExecutor, value: ServiceOfferingVersion, actorAccountId: string): Promise<void> { await database.query('INSERT INTO service_offering_versions (id,service_offering_id,version_number,status,effective_from,effective_to,created_by_account_id) VALUES ($1,$2,$3,$4,$5,$6,$7)', [value.id, value.serviceOfferingId, value.versionNumber, value.status, value.effectiveFrom, value.effectiveTo, actorAccountId]); await database.query('INSERT INTO service_offering_prices (id,service_offering_version_id,currency,amount_minor,created_by_account_id) VALUES ($1,$2,$3,$4,$5)', [createIdentifier(), value.id, value.price.currency, value.price.amountMinor, actorAccountId]); }
  public async findApplicableVersion(serviceOfferingId: string, at: Date): Promise<ServiceOfferingVersion | null> { return version(await this.database.query("SELECT version.id, version.service_offering_id, version.version_number, version.status, version.effective_from, version.effective_to, price.currency, price.amount_minor FROM service_offering_versions version JOIN service_offering_prices price ON price.service_offering_version_id=version.id WHERE version.service_offering_id=$1 AND version.status='ACTIVE' AND version.effective_from <= $2 AND (version.effective_to IS NULL OR version.effective_to > $2) ORDER BY version.effective_from DESC LIMIT 1", [serviceOfferingId, at])); }
  public async doctorProfileOwned(accountId: string, doctorProfileId: string): Promise<boolean> { const result = await this.database.query('SELECT 1 FROM doctor_profiles WHERE id=$1 AND account_id=$2', [doctorProfileId, accountId]); return result.rows.length === 1; }
  public async clinicTenant(clinicId: string): Promise<string | null> { const result = await this.database.query('SELECT tenant_id FROM clinics WHERE id=$1', [clinicId]); return result.rows[0] ? String((result.rows[0] as { tenant_id: unknown }).tenant_id) : null; }
}

function offering(result: { rows: unknown[] }): ServiceOffering | null { const row = result.rows[0] as Record<string, unknown> | undefined; if (!row) return null; return { id: String(row.id), owner: row.owner_doctor_profile_id ? { kind: 'DOCTOR', doctorProfileId: String(row.owner_doctor_profile_id) } : { kind: 'CLINIC', clinicId: String(row.owner_clinic_id), tenantId: String(row.tenant_id) }, name: String(row.name), description: row.description === null ? null : String(row.description), status: row.status as ServiceOffering['status'] }; }
function version(result: { rows: unknown[] }): ServiceOfferingVersion | null { const row = result.rows[0] as Record<string, unknown> | undefined; return row ? { id: String(row.id), serviceOfferingId: String(row.service_offering_id), versionNumber: Number(row.version_number), status: row.status as ServiceOfferingVersion['status'], effectiveFrom: new Date(String(row.effective_from)), effectiveTo: row.effective_to ? new Date(String(row.effective_to)) : null, price: { currency: String(row.currency), amountMinor: BigInt(String(row.amount_minor)) } } : null; }
