import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { InvitationStatus, MembershipRepository, MembershipStatus, TenantInvitation, TenantMembership } from './memberships.js';
import type { TenantRole } from '../authorization/authorization.js';

export class PostgresMembershipRepository implements MembershipRepository {
  public constructor(private readonly database: { transaction<T>(operation: (database: PostgresExecutor) => Promise<T>): Promise<T>; query: PostgresExecutor['query'] }) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async findActiveContext(accountId: string, tenantId: string) { return one(await this.database.query("SELECT tenant_memberships.id, tenant_memberships.account_id, tenant_memberships.tenant_id, tenant_memberships.role_key, tenant_memberships.status FROM tenant_memberships JOIN tenants ON tenants.id = tenant_memberships.tenant_id WHERE tenant_memberships.account_id = $1 AND tenant_memberships.tenant_id = $2 AND tenant_memberships.status = 'ACTIVE' AND tenants.status = 'ACTIVE'", [accountId, tenantId])); }
  public async findActiveContextForUpdate(database: PostgresExecutor, accountId: string, tenantId: string) { return one(await database.query("SELECT tenant_memberships.id, tenant_memberships.account_id, tenant_memberships.tenant_id, tenant_memberships.role_key, tenant_memberships.status FROM tenant_memberships JOIN tenants ON tenants.id = tenant_memberships.tenant_id WHERE tenant_memberships.account_id = $1 AND tenant_memberships.tenant_id = $2 AND tenant_memberships.status = 'ACTIVE' AND tenants.status = 'ACTIVE' FOR UPDATE OF tenant_memberships", [accountId, tenantId])); }
  public async createInvitation(database: PostgresExecutor, value: TenantInvitation & { secretHash: string; createdByAccountId: string }) { await database.query('INSERT INTO tenant_invitations (id, tenant_id, target_account_id, role_key, secret_hash, status, expires_at, created_by_account_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)', [value.id, value.tenantId, value.targetAccountId, value.role, value.secretHash, value.status, value.expiresAt, value.createdByAccountId]); }
  public async lockInvitation(database: PostgresExecutor, id: string) { const result = await database.query('SELECT id, tenant_id, target_account_id, created_by_account_id, role_key, secret_hash, status, expires_at FROM tenant_invitations WHERE id = $1 FOR UPDATE', [id]); const row = result.rows[0]; return row ? invitation(row) : null; }
  public async activeMembership(database: PostgresExecutor, tenantId: string, accountId: string) { return one(await database.query("SELECT id, account_id, tenant_id, role_key, status FROM tenant_memberships WHERE tenant_id = $1 AND account_id = $2 AND status IN ('INVITED', 'ACTIVE') FOR UPDATE", [tenantId, accountId])); }
  public async activateMembership(database: PostgresExecutor, tenantId: string, accountId: string, role: TenantRole, invitedByAccountId: string) { const result = await database.query("INSERT INTO tenant_memberships (id, tenant_id, account_id, role_key, status, invited_by_account_id, invited_at, accepted_at) VALUES ($1, $2, $3, $4, 'ACTIVE', $5, current_timestamp, current_timestamp) RETURNING id, account_id, tenant_id, role_key, status", [createIdentifier(), tenantId, accountId, role, invitedByAccountId]); return one(result)!; }
  public async acceptInvitation(database: PostgresExecutor, invitationId: string, accountId: string) { await database.query("UPDATE tenant_invitations SET status = 'ACCEPTED', accepted_at = current_timestamp, accepted_by_account_id = $2, updated_at = current_timestamp WHERE id = $1 AND status = 'INVITED'", [invitationId, accountId]); }
  public async setInvitationStatus(database: PostgresExecutor, invitationId: string, status: 'REJECTED' | 'REVOKED' | 'EXPIRED', actorAccountId?: string) { await database.query("UPDATE tenant_invitations SET status = $2, rejected_at = CASE WHEN $2 = 'REJECTED' THEN current_timestamp ELSE rejected_at END, revoked_at = CASE WHEN $2 = 'REVOKED' THEN current_timestamp ELSE revoked_at END, revoked_by_account_id = CASE WHEN $2 = 'REVOKED' THEN $3 ELSE revoked_by_account_id END, updated_at = current_timestamp WHERE id = $1 AND status = 'INVITED'", [invitationId, status, actorAccountId ?? null]); }
  public async lockActiveOwners(database: PostgresExecutor, tenantId: string): Promise<TenantMembership[]> { const result = await database.query("SELECT id, account_id, tenant_id, role_key, status FROM tenant_memberships WHERE tenant_id = $1 AND role_key = 'CLINIC_OWNER' AND status = 'ACTIVE' FOR UPDATE", [tenantId]); return result.rows.map((row) => one({ rows: [row] })!);
  }
  public async lockMembership(database: PostgresExecutor, tenantId: string, membershipId: string) { return one(await database.query('SELECT id, account_id, tenant_id, role_key, status FROM tenant_memberships WHERE id = $1 AND tenant_id = $2 FOR UPDATE', [membershipId, tenantId])); }
  public async updateMembership(database: PostgresExecutor, tenantId: string, membershipId: string, status: MembershipStatus, role: TenantRole, actorAccountId: string) { const result = await database.query("UPDATE tenant_memberships SET status = $3, role_key = $4, removed_at = CASE WHEN $3 = 'REMOVED' THEN current_timestamp ELSE removed_at END, removed_by_account_id = CASE WHEN $3 = 'REMOVED' THEN $5 ELSE removed_by_account_id END, updated_at = current_timestamp WHERE id = $1 AND tenant_id = $2 RETURNING id, account_id, tenant_id, role_key, status", [membershipId, tenantId, status, role, actorAccountId]); return one(result); }
}
function one(result: { rows: Record<string, unknown>[] }): TenantMembership | null { const row = result.rows[0]; return row ? { id: String(row.id), accountId: String(row.account_id), tenantId: String(row.tenant_id), role: row.role_key as TenantRole, status: row.status as MembershipStatus } : null; }
function invitation(row: Record<string, unknown>): TenantInvitation & { secretHash: string } { return { id: String(row.id), tenantId: String(row.tenant_id), targetAccountId: String(row.target_account_id), createdByAccountId: String(row.created_by_account_id), role: row.role_key as TenantRole, secretHash: String(row.secret_hash), status: row.status as InvitationStatus, expiresAt: new Date(String(row.expires_at)) }; }
