import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import { newClinic, type Clinic, type ClinicInput, type TenantRepository } from './tenants.js';
export class PostgresTenantRepository implements TenantRepository {
  public constructor(private readonly database: { transaction<T>(operation: (database: PostgresExecutor) => Promise<T>): Promise<T>; query: PostgresExecutor['query'] }) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async create(database: PostgresExecutor, accountId: string, input: ClinicInput): Promise<Clinic> { const ids = newClinic(input); await database.query('INSERT INTO tenants (id, status, created_by_account_id, updated_by_account_id) VALUES ($1, $2, $3, $3)', [ids.tenantId, 'ACTIVE', accountId]); await database.query("INSERT INTO tenant_memberships (id, tenant_id, account_id, role_key, status, accepted_at) VALUES ($1, $2, $3, 'CLINIC_OWNER', 'ACTIVE', current_timestamp)", [createIdentifier(), ids.tenantId, accountId]); const result = await database.query('INSERT INTO clinics (id, tenant_id, status, legal_name, display_name, created_by_account_id, updated_by_account_id) VALUES ($1, $2, $3, $4, $5, $6, $6) RETURNING id, tenant_id, status, legal_name, display_name', [ids.clinicId, ids.tenantId, 'DRAFT', input.legalName, input.displayName, accountId]); return clinic(result.rows[0]!); }
  public async find(clinicId: string): Promise<Clinic | null> { const result = await this.database.query('SELECT id, tenant_id, status, legal_name, display_name FROM clinics WHERE id = $1', [clinicId]); return result.rows[0] ? clinic(result.rows[0]) : null; }
  public async update(clinicId: string, accountId: string, input: ClinicInput): Promise<Clinic | null> { const result = await this.database.query("UPDATE clinics SET legal_name = $3, display_name = $4, updated_at = current_timestamp, updated_by_account_id = $2 WHERE id = $1 AND status IN ('DRAFT', 'PENDING_VERIFICATION', 'ACTIVE') RETURNING id, tenant_id, status, legal_name, display_name", [clinicId, accountId, input.legalName, input.displayName]); return result.rows[0] ? clinic(result.rows[0]) : null; }
}
function clinic(row: Record<string, unknown>): Clinic { return { id: String(row.id), tenantId: String(row.tenant_id), status: row.status as Clinic['status'], legalName: String(row.legal_name), displayName: String(row.display_name) }; }
