import type { DatabaseHealth } from '../../infrastructure/database.js';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { AuditEventInput } from '../audit/audit.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { AppointmentIntent, AppointmentRepository, AvailabilityException, AvailabilityRule, BookableService, ProviderInput, SlotReservation } from './appointments.js';

export class PostgresAppointmentRepository implements AppointmentRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async activePatient(database: PostgresExecutor, accountId: string) { return (await database.query('SELECT 1 FROM patient_profiles WHERE account_id=$1 AND status=\'ACTIVE\'', [accountId])).rowCount === 1; }
  public async lockPublishedExposure(database: PostgresExecutor, exposureId: string) {
    const result = await database.query<Record<string, unknown>>(`SELECT exposure.id,exposure.service_offering_id,exposure.provider_doctor_profile_id,exposure.provider_clinic_id FROM service_exposures exposure JOIN service_offerings offering ON offering.id=exposure.service_offering_id WHERE exposure.id=$1 AND exposure.status='PUBLISHED' AND exposure.provider_doctor_profile_id IS NOT DISTINCT FROM offering.owner_doctor_profile_id AND exposure.provider_clinic_id IS NOT DISTINCT FROM offering.owner_clinic_id FOR UPDATE OF exposure`, [exposureId]);
    const row=result.rows[0];
    return row ? {id:String(row.id),serviceOfferingId:String(row.service_offering_id),provider:row.provider_doctor_profile_id ? {kind:'DOCTOR' as const,doctorProfileId:String(row.provider_doctor_profile_id)} : {kind:'CLINIC' as const,clinicId:String(row.provider_clinic_id)}} : null;
  }
  public async findByIdempotency(actor: string, key: string) { return intent((await this.database.query('SELECT * FROM appointment_intents WHERE booking_actor_account_id=$1 AND idempotency_key=$2', [actor, key])).rows[0]); }
  public async lockBookable(database: PostgresExecutor, offeringId: string, provider: ProviderInput, requestedLocalAt: string): Promise<BookableService | null> {
    const rows = await database.query<Record<string, unknown>>(`
      SELECT offering.id AS offering_id, version.id AS version_id, price.id AS price_id, price.currency, price.amount_minor,
        clinic.tenant_id AS booking_tenant_id,
        configuration.id AS configuration_id, configuration.provider_timezone, configuration.slot_duration_seconds,
        configuration.buffer_before_seconds, configuration.buffer_after_seconds, configuration.capacity,
        configuration.booking_lead_time_seconds, configuration.booking_horizon_seconds, policy.hold_seconds
      FROM service_offerings offering
      JOIN service_offering_versions version ON version.service_offering_id=offering.id
      JOIN service_offering_prices price ON price.service_offering_version_id=version.id
      JOIN service_offering_version_reservation_policies policy ON policy.service_offering_version_id=version.id
      JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id
      LEFT JOIN doctor_profiles doctor ON doctor.id=offering.owner_doctor_profile_id
      LEFT JOIN clinics clinic ON clinic.id=offering.owner_clinic_id
      LEFT JOIN tenants tenant ON tenant.id=clinic.tenant_id
      WHERE offering.id=$1 AND offering.status='ACTIVE' AND version.status='ACTIVE' AND configuration.status='ACTIVE'
        AND ($2::timestamp AT TIME ZONE configuration.provider_timezone) >= version.effective_from
        AND (version.effective_to IS NULL OR ($2::timestamp AT TIME ZONE configuration.provider_timezone) < version.effective_to)
        AND (($3='DOCTOR' AND offering.owner_doctor_profile_id=$4 AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED')
          OR ($3='CLINIC' AND offering.owner_clinic_id=$4 AND clinic.status='ACTIVE' AND tenant.status='ACTIVE'))
      FOR UPDATE OF version, configuration
    `, [offeringId, requestedLocalAt, provider.kind, provider.kind === 'DOCTOR' ? provider.doctorProfileId : provider.clinicId]);
    const row = rows.rows[0]; if (!row) return null;
    const configurationId = String(row.configuration_id);
    const [rules, exceptions] = await Promise.all([this.rules(database, configurationId), this.exceptions(database, configurationId)]);
    if (provider.kind === 'CLINIC' && !row.booking_tenant_id) return null;
    return { provider, serviceOfferingId: String(row.offering_id), versionId: String(row.version_id), priceId: String(row.price_id), currency: String(row.currency), priceAmountMinor: BigInt(String(row.amount_minor)), bookingTenantId: provider.kind === 'CLINIC' ? String(row.booking_tenant_id) : null, timezone: String(row.provider_timezone), durationSeconds: Number(row.slot_duration_seconds), bufferBeforeSeconds: Number(row.buffer_before_seconds), bufferAfterSeconds: Number(row.buffer_after_seconds), capacity: Number(row.capacity), bookingLeadSeconds: Number(row.booking_lead_time_seconds), bookingHorizonSeconds: Number(row.booking_horizon_seconds), holdSeconds: Number(row.hold_seconds), rules, exceptions };
  }
  public async createIntent(database: PostgresExecutor, value: AppointmentIntent) {
    await database.query(`INSERT INTO appointment_intents (id,patient_account_id,booking_actor_account_id,booking_tenant_id,service_exposure_id,provider_doctor_profile_id,provider_clinic_id,service_offering_id,service_offering_version_id,service_offering_price_id,currency,price_amount_minor,provider_timezone,requested_local_at,starts_at,ends_at,service_duration_seconds,buffer_before_seconds,buffer_after_seconds,hold_seconds,booking_relationship,state,idempotency_key,request_fingerprint,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'PATIENT_PROVIDER',$21,$22,$23,$24)`, [value.id,value.patientAccountId,value.bookingActorAccountId,value.bookingTenantId,value.serviceExposureId,value.provider.kind === 'DOCTOR' ? value.provider.doctorProfileId : null,value.provider.kind === 'CLINIC' ? value.provider.clinicId : null,value.serviceOfferingId,value.serviceOfferingVersionId,value.serviceOfferingPriceId,value.currency,value.priceAmountMinor.toString(),value.providerTimezone,value.requestedLocalAt,value.startsAt,value.endsAt,value.serviceDurationSeconds,value.bufferBeforeSeconds,value.bufferAfterSeconds,value.holdSeconds,value.state,value.idempotencyKey,value.requestFingerprint,value.expiresAt]);
  }
  public async lockIntent(database: PostgresExecutor, intentId: string) { return intent((await database.query('SELECT * FROM appointment_intents WHERE id=$1 FOR UPDATE', [intentId])).rows[0]); }
  public async activeCapacityUnits(database: PostgresExecutor, versionId: string, startsAt: Date, endsAt: Date) { const row = (await database.query<{ used: string }>("SELECT COALESCE(sum(capacity_units),0)::text AS used FROM slot_reservations WHERE service_offering_version_id=$1 AND status='HELD' AND expires_at > current_timestamp AND starts_at < $3 AND $2 < ends_at", [versionId, startsAt, endsAt])).rows[0]; return Number(row?.used ?? '0'); }
  public async createReservation(database: PostgresExecutor, value: SlotReservation) { await database.query("INSERT INTO slot_reservations (id,appointment_intent_id,service_offering_version_id,provider_doctor_profile_id,provider_clinic_id,starts_at,ends_at,capacity_units,status,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)", [value.id,value.appointmentIntentId,value.serviceOfferingVersionId,value.provider.kind === 'DOCTOR' ? value.provider.doctorProfileId : null,value.provider.kind === 'CLINIC' ? value.provider.clinicId : null,value.startsAt,value.endsAt,value.capacityUnits,value.status,value.expiresAt]); }
  public async transitionIntent(database: PostgresExecutor, id: string, from: AppointmentIntent['state'], to: AppointmentIntent['state'], at: Date) { const lifecycle = to === 'EXPIRED' ? ', expired_at=$4' : ''; const result = await database.query(`UPDATE appointment_intents SET state=$3${lifecycle} WHERE id=$1 AND state=$2`, [id, from, to, at]); return result.rowCount === 1; }
  public async lockReservation(database: PostgresExecutor, id: string) { return reservation((await database.query('SELECT * FROM slot_reservations WHERE id=$1 FOR UPDATE', [id])).rows[0]); }
  public async releaseReservation(database: PostgresExecutor, id: string, at: Date) { const result = await database.query("UPDATE slot_reservations SET status='RELEASED', released_at=$2 WHERE id=$1 AND status='HELD'", [id, at]); return result.rowCount === 1; }
  public async expireReservation(database: PostgresExecutor, id: string, at: Date) { const result = await database.query("UPDATE slot_reservations SET status='EXPIRED', expired_at=$2 WHERE id=$1 AND status='HELD' AND expires_at <= $2", [id, at]); return result.rowCount === 1; }
  public async appendAudit(database: PostgresExecutor, event: AuditEventInput) { await database.query('INSERT INTO audit_events (id,category,event_type,actor_account_id,tenant_id,target_type,target_id,outcome,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)', [createIdentifier(),event.category,event.eventType,event.actorAccountId ?? null,event.tenantId ?? null,event.targetType,event.targetId ?? null,event.outcome,event.metadata ?? {}]); }
  private async rules(database: PostgresExecutor, configurationId: string): Promise<AvailabilityRule[]> { const result = await database.query<Record<string, unknown>>('SELECT rule.id,rule.canonical_recurrence,rule.effective_from,rule.effective_to,window.kind,window.weekday,window.start_seconds,window.end_seconds FROM availability_rules rule JOIN availability_windows window ON window.availability_rule_id=rule.id WHERE rule.availability_configuration_id=$1 AND rule.status=\'ACTIVE\' ORDER BY rule.id,window.kind,window.weekday,window.start_seconds', [configurationId]); const values = new Map<string, AvailabilityRule>(); for (const row of result.rows) { const id=String(row.id); const rule=values.get(id) ?? { canonicalRecurrence:String(row.canonical_recurrence),effectiveFrom:new Date(String(row.effective_from)),effectiveTo:row.effective_to ? new Date(String(row.effective_to)) : null,windows:[] }; rule.windows.push({kind:row.kind as 'WORKING' | 'BREAK',weekday:Number(row.weekday),startSeconds:Number(row.start_seconds),endSeconds:Number(row.end_seconds)}); values.set(id,rule); } return [...values.values()]; }
  private async exceptions(database: PostgresExecutor, configurationId: string): Promise<AvailabilityException[]> { const result = await database.query<Record<string, unknown>>('SELECT kind,derived_start_utc,derived_end_utc,status FROM availability_exceptions WHERE availability_configuration_id=$1', [configurationId]); return result.rows.map((row) => ({kind:row.kind as AvailabilityException['kind'],start:new Date(String(row.derived_start_utc)),end:new Date(String(row.derived_end_utc)),status:row.status as AvailabilityException['status']})); }
}

function intent(row: Record<string, unknown> | undefined): AppointmentIntent | null { if (!row) return null; return { id:String(row.id),patientAccountId:String(row.patient_account_id),bookingActorAccountId:String(row.booking_actor_account_id),bookingTenantId:row.booking_tenant_id ? String(row.booking_tenant_id) : null,serviceExposureId:row.service_exposure_id ? String(row.service_exposure_id) : null,provider:row.provider_doctor_profile_id ? {kind:'DOCTOR',doctorProfileId:String(row.provider_doctor_profile_id)} : {kind:'CLINIC',clinicId:String(row.provider_clinic_id)},serviceOfferingId:String(row.service_offering_id),serviceOfferingVersionId:String(row.service_offering_version_id),serviceOfferingPriceId:String(row.service_offering_price_id),currency:String(row.currency),priceAmountMinor:BigInt(String(row.price_amount_minor)),providerTimezone:String(row.provider_timezone),requestedLocalAt:formatLocal(row.requested_local_at),startsAt:new Date(String(row.starts_at)),endsAt:new Date(String(row.ends_at)),serviceDurationSeconds:Number(row.service_duration_seconds),bufferBeforeSeconds:Number(row.buffer_before_seconds),bufferAfterSeconds:Number(row.buffer_after_seconds),holdSeconds:Number(row.hold_seconds),state:row.state as AppointmentIntent['state'],idempotencyKey:String(row.idempotency_key),requestFingerprint:String(row.request_fingerprint),expiresAt:new Date(String(row.expires_at)) }; }
function reservation(row: Record<string, unknown> | undefined): SlotReservation | null { if (!row) return null; return {id:String(row.id),appointmentIntentId:String(row.appointment_intent_id),serviceOfferingVersionId:String(row.service_offering_version_id),provider:row.provider_doctor_profile_id ? {kind:'DOCTOR',doctorProfileId:String(row.provider_doctor_profile_id)} : {kind:'CLINIC',clinicId:String(row.provider_clinic_id)},startsAt:new Date(String(row.starts_at)),endsAt:new Date(String(row.ends_at)),capacityUnits:Number(row.capacity_units),status:row.status as SlotReservation['status'],expiresAt:new Date(String(row.expires_at)),releasedAt:row.released_at ? new Date(String(row.released_at)) : null,expiredAt:row.expired_at ? new Date(String(row.expired_at)) : null}; }
function formatLocal(value: unknown) { return String(value).replace(' ', 'T').replace(/\.\d+$/, '').slice(0, 19); }
