import type { DatabaseHealth } from '../../infrastructure/database.js';
import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { AuditEventInput } from '../audit/audit.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { DelegatedAuthorization, DelegatedAuthorizationInput, DelegatedBookingContext, DelegatedBookingRepository } from './delegated-bookings.js';

export class PostgresDelegatedBookingRepository implements DelegatedBookingRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async activePatient(db: PostgresExecutor, accountId: string) { const row = (await db.query<{ id: string }>("SELECT id FROM patient_profiles WHERE account_id=$1 AND status='ACTIVE' FOR UPDATE", [accountId])).rows[0]; return row ? { profileId: row.id } : null; }
  public async activePolicy(db: PostgresExecutor) { const row = (await db.query<{ id: string; expiry_seconds: number }>("SELECT id,expiry_seconds FROM patient_delegated_booking_authorization_policy_versions WHERE status='APPROVED' AND effective_from <= current_timestamp AND (effective_until IS NULL OR effective_until > current_timestamp) ORDER BY version_number DESC LIMIT 1 FOR UPDATE", [])).rows[0]; return row ? { id: row.id, expirySeconds: Number(row.expiry_seconds) } : null; }
  public async resolveAuthorizationScope(db: PostgresExecutor, patientAccountId: string, input: DelegatedAuthorizationInput, expiresAt: Date): Promise<DelegatedAuthorization | null> {
    const row = (await db.query<Record<string, unknown>>(`SELECT clinic.tenant_id,exposure.provider_doctor_profile_id,exposure.service_offering_id
      FROM service_exposures exposure JOIN service_offerings offering ON offering.id=exposure.service_offering_id AND offering.status='ACTIVE' AND offering.owner_doctor_profile_id=exposure.provider_doctor_profile_id
      JOIN doctor_profiles doctor ON doctor.id=exposure.provider_doctor_profile_id AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED'
      JOIN clinics clinic ON clinic.id=$2 AND clinic.status='ACTIVE'
      JOIN network_connections connection ON connection.connection_kind='CLINIC_DOCTOR' AND connection.status='ACCEPTED' AND connection.clinic_left_id=clinic.id AND connection.doctor_profile_id=doctor.id
      JOIN network_connection_capabilities capability ON capability.network_connection_id=connection.id AND capability.capability_key='BOOK' AND capability.status='ACTIVE'
      WHERE exposure.id=$1 AND exposure.status='PUBLISHED' FOR UPDATE OF exposure,connection,capability`, [input.serviceExposureId,input.delegatedClinicId])).rows[0];
    return row ? { id:createIdentifier(),patientAccountId,delegatedClinicId:input.delegatedClinicId,delegatedTenantId:String(row.tenant_id),targetDoctorProfileId:String(row.provider_doctor_profile_id),serviceExposureId:input.serviceExposureId,serviceOfferingId:String(row.service_offering_id),approvedStartsAt:new Date(input.approvedStartsAt),approvedEndsAt:new Date(input.approvedEndsAt),expiresAt,status:'ACTIVE' } : null;
  }
  public async createAuthorization(db: PostgresExecutor, value: DelegatedAuthorization & { patientProfileId: string; scopeFingerprint: string; policyVersionId: string }) { await db.query(`INSERT INTO patient_clinic_booking_authorizations (id,patient_account_id,patient_profile_id,delegated_clinic_id,delegated_tenant_id,target_doctor_profile_id,service_exposure_id,service_offering_id,scheduling_mode,approved_starts_at,approved_ends_at,scope_fingerprint,policy_version_id,consented_by_account_id,consented_at,expires_at,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'FIXED_SLOT',$9,$10,$11,$12,$2,current_timestamp,current_timestamp + make_interval(secs => (SELECT expiry_seconds FROM patient_delegated_booking_authorization_policy_versions WHERE id=$12)),'ACTIVE')`, [value.id,value.patientAccountId,value.patientProfileId,value.delegatedClinicId,value.delegatedTenantId,value.targetDoctorProfileId,value.serviceExposureId,value.serviceOfferingId,value.approvedStartsAt,value.approvedEndsAt,value.scopeFingerprint,value.policyVersionId]); }
  public async lockAuthorization(db: PostgresExecutor, id: string) { return parseAuthorization((await db.query<Record<string, unknown>>('SELECT * FROM patient_clinic_booking_authorizations WHERE id=$1 FOR UPDATE', [id])).rows[0]); }
  public async revokeAuthorization(db: PostgresExecutor, id: string, actorId: string, at: Date) { return (await db.query("UPDATE patient_clinic_booking_authorizations SET status='REVOKED',revoked_at=$3,revoked_by_account_id=$2,revocation_reason_category='PATIENT' WHERE id=$1 AND status='ACTIVE'", [id,actorId,at])).rowCount === 1; }
  public async findBookingByIdempotency(actorId: string, key: string) { const row = (await this.database.query<{ id: string; reservation_id: string; network_booking_context_id: string }>(`SELECT intent.id,reservation.id AS reservation_id,intent.network_booking_context_id FROM appointment_intents intent JOIN slot_reservations reservation ON reservation.appointment_intent_id=intent.id WHERE intent.booking_actor_account_id=$1 AND intent.idempotency_key=$2 AND intent.booking_relationship='CLINIC_DOCTOR'`, [actorId,key])).rows[0]; return row ? { appointmentIntentId: row.id, slotReservationId: row.reservation_id, networkBookingContextId: row.network_booking_context_id } : null; }
  public async lockBookingContext(db: PostgresExecutor, authorization: DelegatedAuthorization, actorId: string): Promise<DelegatedBookingContext | null> {
    const row = (await db.query<Record<string, unknown>>(`
      SELECT authorization.*, offering_version.id AS version_id, price.id AS price_id,price.currency,price.amount_minor,configuration.provider_timezone,configuration.slot_duration_seconds,configuration.buffer_before_seconds,configuration.buffer_after_seconds,configuration.capacity,reservation_policy.hold_seconds,capability.network_connection_id,capability.id AS capability_id,capability.accepted_proposal_id,
        to_char(authorization.approved_starts_at AT TIME ZONE configuration.provider_timezone,'YYYY-MM-DD"T"HH24:MI:SS') AS requested_local_at
      FROM patient_clinic_booking_authorizations authorization
      JOIN service_exposures exposure ON exposure.id=authorization.service_exposure_id AND exposure.status='PUBLISHED' AND exposure.provider_doctor_profile_id=authorization.target_doctor_profile_id AND exposure.service_offering_id=authorization.service_offering_id
      JOIN service_offerings offering ON offering.id=authorization.service_offering_id AND offering.status='ACTIVE' AND offering.owner_doctor_profile_id=authorization.target_doctor_profile_id
      JOIN doctor_profiles doctor ON doctor.id=authorization.target_doctor_profile_id AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED'
      JOIN service_offering_versions offering_version ON offering_version.service_offering_id=offering.id AND offering_version.status='ACTIVE' AND authorization.approved_starts_at >= offering_version.effective_from AND (offering_version.effective_to IS NULL OR authorization.approved_starts_at < offering_version.effective_to)
      JOIN service_offering_prices price ON price.service_offering_version_id=offering_version.id
      JOIN service_offering_version_reservation_policies reservation_policy ON reservation_policy.service_offering_version_id=offering_version.id
      JOIN availability_configurations configuration ON configuration.service_offering_version_id=offering_version.id AND configuration.status='ACTIVE'
      JOIN network_connections connection ON connection.id IN (SELECT network_connection_id FROM network_connection_capabilities WHERE id IS NOT NULL) AND connection.connection_kind='CLINIC_DOCTOR' AND connection.status='ACCEPTED' AND connection.doctor_profile_id=authorization.target_doctor_profile_id AND connection.clinic_left_id=authorization.delegated_clinic_id
      JOIN network_connection_capabilities capability ON capability.network_connection_id=connection.id AND capability.capability_key='BOOK' AND capability.status='ACTIVE'
      JOIN network_capability_proposals proposal ON proposal.id=capability.accepted_proposal_id AND proposal.status='ACCEPTED' AND proposal.proposer_doctor_profile_id=authorization.target_doctor_profile_id AND proposal.accepter_clinic_id=authorization.delegated_clinic_id
      LEFT JOIN tenant_memberships membership ON membership.tenant_id=authorization.delegated_tenant_id AND membership.account_id=$2 AND membership.status='ACTIVE' AND membership.role IN ('CLINIC_OWNER','CLINIC_ADMIN')
      WHERE authorization.id=$1 AND authorization.scheduling_mode='FIXED_SLOT' AND authorization.approved_ends_at=authorization.approved_starts_at + make_interval(secs => configuration.slot_duration_seconds + configuration.buffer_before_seconds + configuration.buffer_after_seconds)
        AND membership.id IS NOT NULL
      FOR UPDATE OF authorization,offering_version,configuration,capability,connection
    `, [authorization.id, actorId])).rows[0];
    if (!row) return null; const auth = parseAuthorization(row)!;
    return { authorization: auth, bookingTenantId: String(row.delegated_tenant_id), doctorProfileId: String(row.target_doctor_profile_id), serviceOfferingId: String(row.service_offering_id), versionId: String(row.version_id), priceId: String(row.price_id), currency: String(row.currency), amountMinor: BigInt(String(row.amount_minor)), timezone: String(row.provider_timezone), durationSeconds: Number(row.slot_duration_seconds), bufferBeforeSeconds: Number(row.buffer_before_seconds), bufferAfterSeconds: Number(row.buffer_after_seconds), holdSeconds: Number(row.hold_seconds), capacity: Number(row.capacity), networkConnectionId: String(row.network_connection_id), networkCapabilityId: String(row.capability_id), acceptedProposalId: String(row.accepted_proposal_id), requestedLocalAt: String(row.requested_local_at) };
  }
  public async createBooking(db: PostgresExecutor, value: DelegatedBookingContext & { intentId: string; reservationId: string; contextId: string; actorId: string; idempotencyKey: string; requestFingerprint: string; expiresAt: Date }) {
    await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))', [value.versionId]);
    const used = await db.query<{ used: string }>(`SELECT COALESCE(sum(capacity_units),0)::text AS used FROM slot_reservations WHERE service_offering_version_id=$1 AND status='HELD' AND expires_at > current_timestamp AND starts_at < $3 AND $2 < ends_at`, [value.versionId,value.authorization.approvedStartsAt,value.authorization.approvedEndsAt]); if (Number(used.rows[0]?.used ?? 0) >= value.capacity) throw new Error('CAPACITY');
    await db.query(`INSERT INTO appointment_intents (id,patient_account_id,booking_actor_account_id,booking_tenant_id,service_exposure_id,provider_doctor_profile_id,service_offering_id,service_offering_version_id,service_offering_price_id,currency,price_amount_minor,provider_timezone,requested_local_at,starts_at,ends_at,service_duration_seconds,buffer_before_seconds,buffer_after_seconds,hold_seconds,booking_relationship,capability_key,scheduling_mode,state,idempotency_key,request_fingerprint,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,'CLINIC_DOCTOR','BOOK','FIXED_SLOT','SLOT_RESERVED',$20,$21,$22)`, [value.intentId,value.authorization.patientAccountId,value.actorId,value.bookingTenantId,value.authorization.serviceExposureId,value.doctorProfileId,value.serviceOfferingId,value.versionId,value.priceId,value.currency,value.amountMinor.toString(),value.timezone,value.requestedLocalAt,value.authorization.approvedStartsAt,value.authorization.approvedEndsAt,value.durationSeconds,value.bufferBeforeSeconds,value.bufferAfterSeconds,value.holdSeconds,value.idempotencyKey,value.requestFingerprint,value.expiresAt]);
    await db.query("INSERT INTO slot_reservations (id,appointment_intent_id,service_offering_version_id,provider_doctor_profile_id,starts_at,ends_at,capacity_units,status,expires_at) VALUES ($1,$2,$3,$4,$5,$6,1,'HELD',$7)", [value.reservationId,value.intentId,value.versionId,value.doctorProfileId,value.authorization.approvedStartsAt,value.authorization.approvedEndsAt,value.expiresAt]);
  }
  public async consumeAuthorization(db: PostgresExecutor, id: string, intentId: string, actorId: string, at: Date) { return (await db.query("UPDATE patient_clinic_booking_authorizations SET status='CONSUMED',consuming_appointment_intent_id=$2,consumed_at=$4,consumed_by_account_id=$3 WHERE id=$1 AND status='ACTIVE' AND expires_at > $4", [id,intentId,actorId,at])).rowCount === 1; }
  public async createNetworkBookingContext(db: PostgresExecutor, value: DelegatedBookingContext & { intentId: string; contextId: string; actorId: string }) { await db.query(`INSERT INTO network_booking_contexts (id,appointment_intent_id,booking_kind,patient_account_id,booking_actor_account_id,originating_tenant_id,network_connection_id,network_capability_id,accepted_proposal_id,patient_clinic_booking_authorization_id,service_exposure_id,service_offering_id,service_offering_version_id,service_offering_price_id,scheduling_mode) VALUES ($1,$2,'CLINIC_DOCTOR_DELEGATED',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'FIXED_SLOT')`, [value.contextId,value.intentId,value.authorization.patientAccountId,value.actorId,value.bookingTenantId,value.networkConnectionId,value.networkCapabilityId,value.acceptedProposalId,value.authorization.id,value.authorization.serviceExposureId,value.serviceOfferingId,value.versionId,value.priceId]); }
  public async attachContext(db: PostgresExecutor, intentId: string, contextId: string) { return (await db.query('UPDATE appointment_intents SET network_booking_context_id=$2 WHERE id=$1 AND network_booking_context_id IS NULL', [intentId,contextId])).rowCount === 1; }
  public async appendAudit(db: PostgresExecutor, event: AuditEventInput) { await db.query('INSERT INTO audit_events (id,category,event_type,actor_account_id,tenant_id,target_type,target_id,outcome,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)', [createIdentifier(),event.category,event.eventType,event.actorAccountId ?? null,event.tenantId ?? null,event.targetType,event.targetId ?? null,event.outcome,event.metadata ?? {}]); }
}
function parseAuthorization(row: Record<string, unknown> | undefined): DelegatedAuthorization | null { if (!row) return null; return { id:String(row.id),patientAccountId:String(row.patient_account_id),delegatedClinicId:String(row.delegated_clinic_id),delegatedTenantId:String(row.delegated_tenant_id),targetDoctorProfileId:String(row.target_doctor_profile_id),serviceExposureId:String(row.service_exposure_id),serviceOfferingId:String(row.service_offering_id),approvedStartsAt:new Date(String(row.approved_starts_at)),approvedEndsAt:new Date(String(row.approved_ends_at)),expiresAt:new Date(String(row.expires_at)),status:row.status as DelegatedAuthorization['status'] }; }
