import { createIdentifier } from '../../shared/identifiers/uuid.js';
import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { AuditEventInput } from '../audit/audit.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { AppointmentIntent, SlotReservation } from './appointments.js';
import type { RescheduleRepository, RescheduleResult, RescheduleSource } from './rescheduling.js';

export class PostgresRescheduleRepository implements RescheduleRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async findByIdempotency(db: PostgresExecutor, actorId: string, key: string) {
    const row=(await db.query<Record<string,unknown>>('SELECT id,source_appointment_id,successor_appointment_id,successor_appointment_intent_id,successor_slot_reservation_id,request_fingerprint FROM appointment_reschedules WHERE actor_account_id=$1 AND idempotency_key=$2 FOR UPDATE',[actorId,key])).rows[0];
    return row ? {id:String(row.id),sourceAppointmentId:String(row.source_appointment_id),successorAppointmentId:String(row.successor_appointment_id),successorIntentId:String(row.successor_appointment_intent_id),successorReservationId:String(row.successor_slot_reservation_id),fingerprint:String(row.request_fingerprint),replayed:false} : null;
  }
  /** Locks the common lifecycle prefix and then the current committed capacity. */
  public async lockSource(db: PostgresExecutor, appointmentId: string): Promise<RescheduleSource | null> {
    const identity=(await db.query<{appointment_intent_id:string}>('SELECT appointment_intent_id FROM appointments WHERE id=$1',[appointmentId])).rows[0]; if(!identity)return null;
    const intent=(await db.query<Record<string,unknown>>('SELECT appointment_intents.*,requested_local_at::text AS requested_local_at_text FROM appointment_intents WHERE id=$1 FOR UPDATE',[identity.appointment_intent_id])).rows[0]; if(!intent)return null;
    const reservation=(await db.query<Record<string,unknown>>('SELECT id FROM slot_reservations WHERE appointment_intent_id=$1 FOR UPDATE',[intent.id])).rows[0]; if(!reservation)return null;
    const handoff=(await db.query<Record<string,unknown>>('SELECT id,payment_intent_id,financial_allocation_snapshot_id FROM appointment_financial_handoffs WHERE appointment_intent_id=$1 FOR UPDATE',[intent.id])).rows[0]; if(!handoff)return null;
    const appointment=(await db.query<Record<string,unknown>>('SELECT id,status,slot_reservation_id,appointment_financial_handoff_id,financial_allocation_snapshot_id,payment_intent_id FROM appointments WHERE id=$1 FOR UPDATE',[appointmentId])).rows[0]; if(!appointment)return null;
    await db.query('SELECT id FROM payment_intents WHERE id=$1 FOR UPDATE',[handoff.payment_intent_id]);
    const capacity=(await db.query<Record<string,unknown>>("SELECT id FROM appointment_committed_capacities WHERE appointment_id=$1 AND status='ACTIVE' FOR UPDATE",[appointmentId])).rows[0]; if(!capacity)return null;
    return {appointmentId:String(appointment.id),status:String(appointment.status),reservationId:String(appointment.slot_reservation_id),committedCapacityId:String(capacity.id),handoffId:String(handoff.id),allocationId:String(handoff.financial_allocation_snapshot_id),paymentIntentId:String(handoff.payment_intent_id),intent:asIntent(intent)};
  }
  public async createSuccessorAppointment(db: PostgresExecutor, source: RescheduleSource, intent: AppointmentIntent, reservation: SlotReservation) {
    const id=createIdentifier();
    await db.query(`INSERT INTO appointments (id,reschedule_source_appointment_id,appointment_intent_id,slot_reservation_id,appointment_financial_handoff_id,financial_allocation_snapshot_id,payment_intent_id,patient_account_id,booking_actor_account_id,booking_tenant_id,provider_doctor_profile_id,provider_clinic_id,service_exposure_id,service_offering_id,service_offering_version_id,service_offering_price_id,currency,price_amount_minor,provider_timezone,requested_local_at,starts_at,ends_at,service_duration_seconds,buffer_before_seconds,buffer_after_seconds,hold_seconds,status)
      SELECT $1,$2,$3,$4,source.appointment_financial_handoff_id,source.financial_allocation_snapshot_id,source.payment_intent_id,$5,$5,source.booking_tenant_id,source.provider_doctor_profile_id,source.provider_clinic_id,source.service_exposure_id,source.service_offering_id,source.service_offering_version_id,source.service_offering_price_id,source.currency,source.price_amount_minor,source.provider_timezone,$6,$7,$8,source.service_duration_seconds,source.buffer_before_seconds,source.buffer_after_seconds,source.hold_seconds,'CONFIRMED' FROM appointments source WHERE source.id=$2`,[id,source.appointmentId,intent.id,reservation.id,intent.patientAccountId,intent.requestedLocalAt,intent.startsAt,intent.endsAt]);
    await db.query(`INSERT INTO appointment_participants (id,appointment_id,participant_type,patient_profile_id)
      SELECT $1,$2,'PATIENT',patient_profile_id FROM appointment_participants WHERE appointment_id=$3 AND participant_type='PATIENT'`,[createIdentifier(),id,source.appointmentId]);
    await db.query(`INSERT INTO appointment_participants (id,appointment_id,participant_type,doctor_profile_id)
      SELECT $1,$2,'DOCTOR',doctor_profile_id FROM appointment_participants WHERE appointment_id=$3 AND participant_type='DOCTOR'`,[createIdentifier(),id,source.appointmentId]);
    await db.query(`INSERT INTO appointment_participants (id,appointment_id,participant_type,clinic_id,tenant_id)
      SELECT $1,$2,'CLINIC',clinic_id,tenant_id FROM appointment_participants WHERE appointment_id=$3 AND participant_type='CLINIC'`,[createIdentifier(),id,source.appointmentId]);
    return id;
  }
  public async createCommittedCapacity(db: PostgresExecutor, appointmentId: string, reservationId: string) { await db.query(`INSERT INTO appointment_committed_capacities (id,appointment_id,slot_reservation_id,service_offering_version_id,starts_at,ends_at,capacity_units)
    SELECT $1,$2,reservation.id,reservation.service_offering_version_id,reservation.starts_at,reservation.ends_at,reservation.capacity_units FROM slot_reservations reservation WHERE reservation.id=$3`,[createIdentifier(),appointmentId,reservationId]); }
  public async createReschedule(db: PostgresExecutor, v: Omit<RescheduleResult,'replayed'> & {actorId:string;reason:string;idempotencyKey:string;fingerprint:string;auditEventId:string}) { await db.query('INSERT INTO appointment_reschedules (id,source_appointment_id,successor_appointment_id,successor_appointment_intent_id,successor_slot_reservation_id,actor_account_id,reason,idempotency_key,request_fingerprint,audit_event_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[v.id,v.sourceAppointmentId,v.successorAppointmentId,v.successorIntentId,v.successorReservationId,v.actorId,v.reason,v.idempotencyKey,v.fingerprint,v.auditEventId]); }
  public async releaseSourceCapacity(db: PostgresExecutor,id:string,at:Date){return (await db.query("UPDATE appointment_committed_capacities SET status='RELEASED',released_at=$2 WHERE id=$1 AND status='ACTIVE'",[id,at])).rowCount===1;}
  public async appendAudit(db: PostgresExecutor,e:AuditEventInput){const id=createIdentifier();await db.query('INSERT INTO audit_events (id,category,event_type,actor_account_id,tenant_id,target_type,target_id,outcome,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[id,e.category,e.eventType,e.actorAccountId??null,e.tenantId??null,e.targetType,e.targetId??null,e.outcome,JSON.stringify(e.metadata??{})]);return id;}
  public async appendEvent(db: PostgresExecutor,id:string,type:'RESCHEDULE_REQUESTED'|'RESCHEDULED',actor:string,reason:string,audit:string,context:Record<string,string>){await db.query('INSERT INTO appointment_events (id,appointment_id,event_type,actor_account_id,reason,context,audit_event_id) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7)',[createIdentifier(),id,type,actor,reason,JSON.stringify(context),audit]);}
}
function asIntent(r:Record<string,unknown>):AppointmentIntent{return {id:String(r.id),patientAccountId:String(r.patient_account_id),bookingActorAccountId:String(r.booking_actor_account_id),bookingTenantId:r.booking_tenant_id?String(r.booking_tenant_id):null,serviceExposureId:r.service_exposure_id?String(r.service_exposure_id):null,provider:r.provider_doctor_profile_id?{kind:'DOCTOR',doctorProfileId:String(r.provider_doctor_profile_id)}:{kind:'CLINIC',clinicId:String(r.provider_clinic_id)},serviceOfferingId:String(r.service_offering_id),serviceOfferingVersionId:String(r.service_offering_version_id),serviceOfferingPriceId:String(r.service_offering_price_id),currency:String(r.currency),priceAmountMinor:BigInt(String(r.price_amount_minor)),providerTimezone:String(r.provider_timezone),requestedLocalAt:String(r.requested_local_at_text).replace(' ','T').slice(0,19),startsAt:new Date(String(r.starts_at)),endsAt:new Date(String(r.ends_at)),serviceDurationSeconds:Number(r.service_duration_seconds),bufferBeforeSeconds:Number(r.buffer_before_seconds),bufferAfterSeconds:Number(r.buffer_after_seconds),holdSeconds:Number(r.hold_seconds),bookingRelationship:r.booking_relationship as AppointmentIntent['bookingRelationship'],state:r.state as AppointmentIntent['state'],idempotencyKey:String(r.idempotency_key),requestFingerprint:String(r.request_fingerprint),expiresAt:new Date(String(r.expires_at))};}
