import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { ProviderAppointment, ProviderClinic, ProviderClinicDoctor, ProviderDashboard, ProviderDoctor, ProviderPortalRepository, ProviderService } from './provider-portal.js';

export class PostgresProviderPortalRepository implements ProviderPortalRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public async clinics(accountId: string): Promise<ProviderClinic[]> { return (await this.database.query<Record<string, unknown>>(`SELECT clinic.id,clinic.tenant_id,clinic.display_name,clinic.legal_name,clinic.status,membership.role_key FROM tenant_memberships membership JOIN clinics clinic ON clinic.tenant_id=membership.tenant_id WHERE membership.account_id=$1 AND membership.status='ACTIVE' AND membership.role_key IN ('CLINIC_OWNER','CLINIC_ADMIN','CLINIC_STAFF') ORDER BY clinic.display_name`, [accountId])).rows.map(clinic); }
  public async hasActiveProviderAccess(accountId: string): Promise<boolean> { return (await this.database.query<Record<string, unknown>>(`SELECT 1 FROM tenant_memberships WHERE account_id=$1 AND status='ACTIVE' AND role_key IN ('CLINIC_OWNER','CLINIC_ADMIN','CLINIC_STAFF') UNION ALL SELECT 1 FROM doctor_profiles WHERE account_id=$1 AND status='ACTIVE' LIMIT 1`, [accountId])).rows.length > 0; }
  public async doctor(accountId: string): Promise<ProviderDoctor | null> { const row=(await this.database.query<Record<string, unknown>>(`SELECT id,display_name,status,professional_verification_status FROM doctor_profiles WHERE account_id=$1 AND status='ACTIVE'`,[accountId])).rows[0]; return row ? doctor(row) : null; }
  public async servicesForClinic(clinicId: string) { return this.services('offering.owner_clinic_id=$1',[clinicId]); }
  public async servicesForDoctor(doctorId: string) { return this.services('offering.owner_doctor_profile_id=$1',[doctorId]); }
  public async doctorsForClinic(clinicId: string): Promise<ProviderClinicDoctor[]> { return (await this.database.query<Record<string, unknown>>(`SELECT doctor.id,doctor.display_name,doctor.status,doctor.professional_verification_status,connection.id connection_id,connection.status connection_status,connection.initiator_party_kind connection_initiator_kind FROM network_connections connection JOIN doctor_profiles doctor ON doctor.id=connection.doctor_profile_id WHERE connection.connection_kind='CLINIC_DOCTOR' AND connection.clinic_left_id=$1 AND connection.status IN ('REQUESTED','ACCEPTED') ORDER BY doctor.display_name NULLS LAST`,[clinicId])).rows.map(clinicDoctor); }
  public async appointmentsForClinic(clinicId: string) { return this.appointments('appointment.provider_clinic_id=$1',[clinicId]); }
  public async appointmentsForDoctor(doctorId: string) { return this.appointments('appointment.provider_doctor_profile_id=$1',[doctorId]); }
  public async dashboard(clinicId: string): Promise<Omit<ProviderDashboard, 'clinic'>> { const row=(await this.database.query<Record<string,unknown>>(`SELECT (SELECT count(*)::text FROM service_offerings WHERE owner_clinic_id=$1) services,(SELECT count(*)::text FROM network_connections WHERE connection_kind='CLINIC_DOCTOR' AND clinic_left_id=$1 AND status='ACCEPTED') doctors,(SELECT count(*)::text FROM availability_configurations configuration JOIN service_offering_versions version ON version.id=configuration.service_offering_version_id JOIN service_offerings offering ON offering.id=version.service_offering_id WHERE offering.owner_clinic_id=$1 AND configuration.status='ACTIVE') availability,(SELECT count(*)::text FROM appointments WHERE provider_clinic_id=$1 AND status IN ('PAYMENT_PENDING','CONFIRMED','IN_PROGRESS')) appointments,(SELECT status FROM platform_public_discovery_approvals WHERE subject_kind='CLINIC' AND clinic_id=$1) public_discovery`,[clinicId])).rows[0]??{}; return { services:Number(row.services??0),doctors:Number(row.doctors??0),availability:Number(row.availability??0),appointments:Number(row.appointments??0),publicDiscovery:row.public_discovery?String(row.public_discovery):'NOT_PUBLISHED' }; }
  private async services(predicate: string, values: unknown[]): Promise<ProviderService[]> { return (await this.database.query<Record<string,unknown>>(`SELECT offering.id,offering.name,offering.description,offering.status,version.id version_id,version.status version_status,availability.status availability_status,exposure.id exposure_id,exposure.status exposure_status,approval.status public_discovery_status FROM service_offerings offering LEFT JOIN LATERAL (SELECT id,status FROM service_offering_versions WHERE service_offering_id=offering.id ORDER BY version_number DESC LIMIT 1) version ON true LEFT JOIN availability_configurations availability ON availability.service_offering_version_id=version.id LEFT JOIN service_exposures exposure ON exposure.service_offering_id=offering.id LEFT JOIN platform_public_discovery_approvals approval ON (approval.subject_kind='CLINIC' AND approval.clinic_id=offering.owner_clinic_id) OR (approval.subject_kind='DOCTOR' AND approval.doctor_profile_id=offering.owner_doctor_profile_id) WHERE ${predicate} ORDER BY offering.created_at DESC`,values)).rows.map(service); }
  private async appointments(predicate:string, values:unknown[]):Promise<ProviderAppointment[]> { return (await this.database.query<Record<string,unknown>>(`SELECT appointment.id,appointment.status,appointment.starts_at,appointment.ends_at,offering.name service_name FROM appointments appointment JOIN service_offerings offering ON offering.id=appointment.service_offering_id WHERE ${predicate} ORDER BY appointment.starts_at DESC LIMIT 100`,values)).rows.map(appointment); }
}
function clinic(row:Record<string,unknown>):ProviderClinic{return{id:String(row.id),tenantId:String(row.tenant_id),displayName:String(row.display_name),legalName:String(row.legal_name),status:String(row.status),role:row.role_key as ProviderClinic['role']};}
function doctor(row:Record<string,unknown>):ProviderDoctor{return{id:String(row.id),displayName:row.display_name===null?null:String(row.display_name),status:String(row.status),professionalVerificationStatus:String(row.professional_verification_status)};}
function clinicDoctor(row:Record<string,unknown>):ProviderClinicDoctor{return{...doctor(row),connectionId:String(row.connection_id),connectionStatus:row.connection_status==='ACCEPTED'?'ACCEPTED':'REQUESTED',connectionInitiatorKind:row.connection_initiator_kind==='DOCTOR'?'DOCTOR':'CLINIC'};}
function service(row:Record<string,unknown>):ProviderService{return{id:String(row.id),name:String(row.name),description:row.description===null?null:String(row.description),status:String(row.status),versionId:row.version_id?String(row.version_id):null,versionStatus:row.version_status?String(row.version_status):null,availabilityStatus:row.availability_status?String(row.availability_status):null,exposureId:row.exposure_id?String(row.exposure_id):null,exposureStatus:row.exposure_status?String(row.exposure_status):null,publicDiscoveryStatus:row.public_discovery_status?String(row.public_discovery_status):null};}
function appointment(row:Record<string,unknown>):ProviderAppointment{return{id:String(row.id),status:String(row.status),startsAt:new Date(String(row.starts_at)),endsAt:new Date(String(row.ends_at)),serviceName:String(row.service_name)};}
