import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { PostgresExecutor } from '../sessions/postgres-session-repository.js';
import type { ClinicOwnedOffering, ClinicServiceDoctorAssignment, ClinicServiceDoctorAssignmentRepository } from './clinic-service-doctors.js';

export class PostgresClinicServiceDoctorAssignmentRepository implements ClinicServiceDoctorAssignmentRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public transaction<T>(operation: (database: PostgresExecutor) => Promise<T>) { return this.database.transaction(operation); }
  public async clinicOwnedOffering(serviceOfferingId: string): Promise<ClinicOwnedOffering | null> { const row = (await this.database.query<Record<string, unknown>>('SELECT offering.id,offering.owner_clinic_id,clinic.tenant_id FROM service_offerings offering JOIN clinics clinic ON clinic.id=offering.owner_clinic_id WHERE offering.id=$1', [serviceOfferingId])).rows[0]; return row ? { id: String(row.id), clinicId: String(row.owner_clinic_id), tenantId: String(row.tenant_id) } : null; }
  public async acceptedEligibleConnection(serviceOfferingId: string, doctorProfileId: string): Promise<string | null> { const row = (await this.database.query<{ id: string }>("SELECT connection.id FROM service_offerings offering JOIN network_connections connection ON connection.connection_kind='CLINIC_DOCTOR' AND connection.clinic_left_id=offering.owner_clinic_id AND connection.doctor_profile_id=$2 AND connection.status='ACCEPTED' JOIN doctor_profiles doctor ON doctor.id=connection.doctor_profile_id AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' WHERE offering.id=$1 AND offering.owner_clinic_id IS NOT NULL", [serviceOfferingId, doctorProfileId])).rows[0]; return row?.id ?? null; }
  public async list(serviceOfferingId: string) { return (await this.database.query<Record<string, unknown>>("SELECT assignment.id,assignment.service_offering_id,assignment.doctor_profile_id,doctor.display_name,assignment.network_connection_id,assignment.status,assignment.created_at,assignment.revoked_at FROM clinic_service_doctor_assignments assignment JOIN doctor_profiles doctor ON doctor.id=assignment.doctor_profile_id WHERE assignment.service_offering_id=$1 ORDER BY CASE assignment.status WHEN 'ACTIVE' THEN 0 ELSE 1 END,assignment.created_at DESC", [serviceOfferingId])).rows.map(assignment); }
  public async create(database: PostgresExecutor, assignmentValue: ClinicServiceDoctorAssignment, actorId: string) { await database.query("INSERT INTO clinic_service_doctor_assignments (id,service_offering_id,doctor_profile_id,network_connection_id,status,created_by_account_id) VALUES ($1,$2,$3,$4,'ACTIVE',$5)", [assignmentValue.id, assignmentValue.serviceOfferingId, assignmentValue.doctorProfileId, assignmentValue.networkConnectionId, actorId]); }
  public async revoke(database: PostgresExecutor, serviceOfferingId: string, doctorProfileId: string, actorId: string) { return assignment((await database.query<Record<string, unknown>>("UPDATE clinic_service_doctor_assignments SET status='REVOKED',revoked_at=current_timestamp,revoked_by_account_id=$3 WHERE service_offering_id=$1 AND doctor_profile_id=$2 AND status='ACTIVE' RETURNING id,service_offering_id,doctor_profile_id,NULL::text AS display_name,network_connection_id,status,created_at,revoked_at", [serviceOfferingId, doctorProfileId, actorId])).rows[0]); }
}
function assignment(row: Record<string, unknown>): ClinicServiceDoctorAssignment { return { id: String(row.id), serviceOfferingId: String(row.service_offering_id), doctorProfileId: String(row.doctor_profile_id), doctorDisplayName: row.display_name === null ? null : String(row.display_name), networkConnectionId: String(row.network_connection_id), status: row.status as 'ACTIVE' | 'REVOKED', createdAt: new Date(String(row.created_at)), revokedAt: row.revoked_at === null ? null : new Date(String(row.revoked_at)) }; }
