import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { AvailabilityException, AvailabilityRule, BookableService } from '../appointments/appointments.js';
import type { PublicDiscoveryRepository, PublicDoctor, PublicService } from './public-discovery.js';

export class PostgresPublicDiscoveryRepository implements PublicDiscoveryRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public async listDoctors(query: string | undefined): Promise<PublicDoctor[]> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT DISTINCT doctor.id,doctor.display_name FROM doctor_profiles doctor JOIN service_offerings offering ON offering.owner_doctor_profile_id=doctor.id AND offering.status='ACTIVE' JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND exposure.status='PUBLISHED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' AND ($1::text IS NULL OR doctor.display_name ILIKE '%' || $1 || '%') ORDER BY doctor.display_name NULLS LAST,doctor.id`, [query ?? null]);
    return result.rows.map(doctor);
  }
  public async findDoctor(id: string): Promise<PublicDoctor | null> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT doctor.id,doctor.display_name FROM doctor_profiles doctor WHERE doctor.id=$1 AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' AND EXISTS (SELECT 1 FROM service_offerings offering JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND exposure.status='PUBLISHED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE offering.owner_doctor_profile_id=doctor.id AND offering.status='ACTIVE')`, [id]);
    return result.rows[0] ? doctor(result.rows[0]) : null;
  }
  public async listServices(filter: { doctorProfileId?: string; query?: string }): Promise<PublicService[]> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT exposure.id,doctor.id AS doctor_profile_id,offering.name,offering.description,price.currency,price.amount_minor FROM service_exposures exposure JOIN service_offerings offering ON offering.id=exposure.service_offering_id AND offering.status='ACTIVE' JOIN doctor_profiles doctor ON doctor.id=exposure.provider_doctor_profile_id AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' JOIN LATERAL (SELECT version.id FROM service_offering_versions version WHERE version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) ORDER BY version.effective_from DESC LIMIT 1) version ON true JOIN service_offering_prices price ON price.service_offering_version_id=version.id JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE exposure.status='PUBLISHED' AND ($1::uuid IS NULL OR doctor.id=$1) AND ($2::text IS NULL OR offering.name ILIKE '%' || $2 || '%' OR COALESCE(offering.description,'') ILIKE '%' || $2 || '%') ORDER BY offering.name,exposure.id`, [filter.doctorProfileId ?? null, filter.query ?? null]);
    return result.rows.map(service);
  }
  public async findCandidateServices(exposureId: string): Promise<BookableService[]> {
    const result = await this.database.query<Record<string, unknown>>(`${bookableSelect} WHERE exposure.id=$1 AND exposure.status='PUBLISHED' ORDER BY version.effective_from`, [exposureId]);
    return Promise.all(result.rows.map((row) => this.bookable(row)));
  }
  public async findBookableService(exposureId: string, requestedLocalAt: string): Promise<BookableService | null> {
    const result = await this.database.query<Record<string, unknown>>(`${bookableSelect} WHERE exposure.id=$1 AND exposure.status='PUBLISHED' AND ($2::timestamp AT TIME ZONE configuration.provider_timezone) >= version.effective_from AND (version.effective_to IS NULL OR ($2::timestamp AT TIME ZONE configuration.provider_timezone) < version.effective_to) ORDER BY version.effective_from DESC LIMIT 1`, [exposureId, requestedLocalAt]);
    return result.rows[0] ? this.bookable(result.rows[0]) : null;
  }
  public async activeCapacityUnits(versionId: string, startsAt: Date, endsAt: Date): Promise<number> { const row = (await this.database.query<{ used: string }>(`SELECT COALESCE(sum(units),0)::text AS used FROM (SELECT capacity_units AS units FROM appointment_committed_capacities WHERE service_offering_version_id=$1 AND status='ACTIVE' AND starts_at<$3 AND $2<ends_at UNION ALL SELECT reservation.capacity_units FROM slot_reservations reservation WHERE reservation.service_offering_version_id=$1 AND reservation.status='HELD' AND reservation.expires_at>current_timestamp AND reservation.starts_at<$3 AND $2<reservation.ends_at AND NOT EXISTS (SELECT 1 FROM appointment_committed_capacities committed WHERE committed.slot_reservation_id=reservation.id AND committed.status='ACTIVE')) capacity`, [versionId, startsAt, endsAt])).rows[0]; return Number(row?.used ?? '0'); }
  private async rules(configurationId: string): Promise<AvailabilityRule[]> { const result = await this.database.query<Record<string, unknown>>(`SELECT rule.id,rule.canonical_recurrence,rule.effective_from,rule.effective_to,window.kind,window.weekday,window.start_seconds,window.end_seconds FROM availability_rules rule JOIN availability_windows window ON window.availability_rule_id=rule.id WHERE rule.availability_configuration_id=$1 AND rule.status='ACTIVE' ORDER BY rule.id,window.kind,window.weekday,window.start_seconds`, [configurationId]); const values = new Map<string, AvailabilityRule>(); for (const row of result.rows) { const id=String(row.id); const rule=values.get(id) ?? { canonicalRecurrence:String(row.canonical_recurrence), effectiveFrom:new Date(String(row.effective_from)), effectiveTo:row.effective_to ? new Date(String(row.effective_to)) : null, windows:[] }; rule.windows.push({ kind:row.kind as 'WORKING' | 'BREAK', weekday:Number(row.weekday), startSeconds:Number(row.start_seconds), endSeconds:Number(row.end_seconds) }); values.set(id,rule); } return [...values.values()]; }
  private async exceptions(configurationId: string): Promise<AvailabilityException[]> { const result = await this.database.query<Record<string, unknown>>(`SELECT kind,derived_start_utc,derived_end_utc,status FROM availability_exceptions WHERE availability_configuration_id=$1`, [configurationId]); return result.rows.map((row) => ({ kind:row.kind as AvailabilityException['kind'], start:new Date(String(row.derived_start_utc)), end:new Date(String(row.derived_end_utc)), status:row.status as AvailabilityException['status'] })); }
  private async bookable(row: Record<string, unknown>): Promise<BookableService> { const configurationId = String(row.configuration_id); return { provider: { kind: 'DOCTOR', doctorProfileId: String(row.doctor_profile_id) }, serviceOfferingId: String(row.offering_id), versionId: String(row.version_id), priceId: String(row.price_id), currency: String(row.currency), priceAmountMinor: BigInt(String(row.amount_minor)), bookingTenantId: null, timezone: String(row.provider_timezone), slotDurationSeconds: Number(row.slot_duration_seconds), durationSeconds: Number(row.slot_duration_seconds), bufferBeforeSeconds: Number(row.buffer_before_seconds), bufferAfterSeconds: Number(row.buffer_after_seconds), capacity: Number(row.capacity), bookingLeadSeconds: Number(row.booking_lead_time_seconds), bookingHorizonSeconds: Number(row.booking_horizon_seconds), holdSeconds: 0, rules: await this.rules(configurationId), exceptions: await this.exceptions(configurationId) }; }
}

const bookableSelect = `SELECT offering.id AS offering_id,version.id AS version_id,price.id AS price_id,price.currency,price.amount_minor,configuration.id AS configuration_id,configuration.provider_timezone,configuration.slot_duration_seconds,configuration.buffer_before_seconds,configuration.buffer_after_seconds,configuration.capacity,configuration.booking_lead_time_seconds,configuration.booking_horizon_seconds,doctor.id AS doctor_profile_id FROM service_exposures exposure JOIN service_offerings offering ON offering.id=exposure.service_offering_id AND offering.status='ACTIVE' JOIN doctor_profiles doctor ON doctor.id=exposure.provider_doctor_profile_id AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' JOIN service_offering_prices price ON price.service_offering_version_id=version.id JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE'`;
function doctor(row: Record<string, unknown>): PublicDoctor { return { id:String(row.id), displayName:row.display_name === null ? null : String(row.display_name) }; }
function service(row: Record<string, unknown>): PublicService { return { id:String(row.id), doctorProfileId:String(row.doctor_profile_id), name:String(row.name), description:row.description === null ? null : String(row.description), currency:String(row.currency), amountMinor:String(row.amount_minor) }; }
