import type { DatabaseHealth } from '../../infrastructure/database.js';
import type { AvailabilityException, AvailabilityRule, BookableService } from '../appointments/appointments.js';
import type { PublicClinic, PublicDiscoveryRepository, PublicDoctor, PublicService } from './public-discovery.js';

export class PostgresPublicDiscoveryRepository implements PublicDiscoveryRepository {
  public constructor(private readonly database: DatabaseHealth) {}
  public async listDoctors(query: string | undefined): Promise<PublicDoctor[]> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT DISTINCT doctor.id,doctor.display_name FROM doctor_profiles doctor JOIN service_offerings offering ON offering.owner_doctor_profile_id=doctor.id AND offering.status='ACTIVE' JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND exposure.status='PUBLISHED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' AND ${approval('doctor.id', 'DOCTOR')} AND ($1::text IS NULL OR doctor.display_name ILIKE '%' || $1 || '%') ORDER BY doctor.display_name NULLS LAST,doctor.id`, [query ?? null]);
    return result.rows.map(doctor);
  }
  public async findDoctor(id: string): Promise<PublicDoctor | null> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT doctor.id,doctor.display_name FROM doctor_profiles doctor WHERE doctor.id=$1 AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' AND ${approval('doctor.id', 'DOCTOR')} AND EXISTS (SELECT 1 FROM service_offerings offering JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND exposure.status='PUBLISHED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE offering.owner_doctor_profile_id=doctor.id AND offering.status='ACTIVE')`, [id]);
    return result.rows[0] ? doctor(result.rows[0]) : null;
  }
  public async listClinics(query: string | undefined): Promise<PublicClinic[]> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT DISTINCT clinic.id,clinic.display_name FROM clinics clinic JOIN tenants tenant ON tenant.id=clinic.tenant_id AND tenant.status='ACTIVE' JOIN service_offerings offering ON offering.owner_clinic_id=clinic.id AND offering.status='ACTIVE' JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND exposure.provider_clinic_id=clinic.id AND exposure.status='PUBLISHED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE clinic.status='ACTIVE' AND ${approval('clinic.id', 'CLINIC')} AND ($1::text IS NULL OR clinic.display_name ILIKE '%' || $1 || '%') ORDER BY clinic.display_name,clinic.id`, [query ?? null]);
    return result.rows.map(clinic);
  }
  public async findClinic(id: string): Promise<PublicClinic | null> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT clinic.id,clinic.display_name FROM clinics clinic JOIN tenants tenant ON tenant.id=clinic.tenant_id AND tenant.status='ACTIVE' WHERE clinic.id=$1 AND clinic.status='ACTIVE' AND ${approval('clinic.id', 'CLINIC')} AND EXISTS (SELECT 1 FROM service_offerings offering JOIN service_exposures exposure ON exposure.service_offering_id=offering.id AND exposure.provider_clinic_id=clinic.id AND exposure.status='PUBLISHED' JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE offering.owner_clinic_id=clinic.id AND offering.status='ACTIVE')`, [id]);
    return result.rows[0] ? clinic(result.rows[0]) : null;
  }
  public async listServices(filter: { doctorProfileId?: string; clinicId?: string; query?: string }): Promise<PublicService[]> {
    const result = await this.database.query<Record<string, unknown>>(`SELECT exposure.id,exposure.provider_doctor_profile_id,exposure.provider_clinic_id,offering.name,offering.description,price.currency,price.amount_minor FROM service_exposures exposure JOIN service_offerings offering ON offering.id=exposure.service_offering_id AND offering.status='ACTIVE' LEFT JOIN doctor_profiles doctor ON doctor.id=exposure.provider_doctor_profile_id LEFT JOIN clinics clinic ON clinic.id=exposure.provider_clinic_id LEFT JOIN tenants tenant ON tenant.id=clinic.tenant_id JOIN LATERAL (SELECT version.id FROM service_offering_versions version WHERE version.service_offering_id=offering.id AND version.status='ACTIVE' AND version.effective_from<=current_timestamp AND (version.effective_to IS NULL OR version.effective_to>current_timestamp) ORDER BY version.effective_from DESC LIMIT 1) version ON true JOIN service_offering_prices price ON price.service_offering_version_id=version.id JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE exposure.status='PUBLISHED' AND ((doctor.id IS NOT NULL AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' AND ${approval('doctor.id', 'DOCTOR')}) OR (clinic.id IS NOT NULL AND clinic.status='ACTIVE' AND tenant.status='ACTIVE' AND ${approval('clinic.id', 'CLINIC')})) AND ($1::uuid IS NULL OR exposure.provider_doctor_profile_id=$1) AND ($2::uuid IS NULL OR exposure.provider_clinic_id=$2) AND ($3::text IS NULL OR offering.name ILIKE '%' || $3 || '%' OR COALESCE(offering.description,'') ILIKE '%' || $3 || '%') ORDER BY offering.name,exposure.id`, [filter.doctorProfileId ?? null, filter.clinicId ?? null, filter.query ?? null]);
    return result.rows.map(service);
  }
  public async findCandidateServices(exposureId: string): Promise<BookableService[]> {
    const result = await this.database.query<Record<string, unknown>>(`${bookableSelect} AND exposure.id=$1 AND exposure.status='PUBLISHED' ORDER BY version.effective_from`, [exposureId]);
    return Promise.all(result.rows.map((row) => this.bookable(row)));
  }
  public async findBookableService(exposureId: string, requestedLocalAt: string): Promise<BookableService | null> {
    const result = await this.database.query<Record<string, unknown>>(`${bookableSelect} AND exposure.id=$1 AND exposure.status='PUBLISHED' AND ($2::timestamp AT TIME ZONE configuration.provider_timezone) >= version.effective_from AND (version.effective_to IS NULL OR ($2::timestamp AT TIME ZONE configuration.provider_timezone) < version.effective_to) ORDER BY version.effective_from DESC LIMIT 1`, [exposureId, requestedLocalAt]);
    return result.rows[0] ? this.bookable(result.rows[0]) : null;
  }
  public async activeCapacityUnits(versionId: string, startsAt: Date, endsAt: Date): Promise<number> { const row = (await this.database.query<{ used: string }>(`SELECT COALESCE(sum(units),0)::text AS used FROM (SELECT capacity_units AS units FROM appointment_committed_capacities WHERE service_offering_version_id=$1 AND status='ACTIVE' AND starts_at<$3 AND $2<ends_at UNION ALL SELECT reservation.capacity_units FROM slot_reservations reservation WHERE reservation.service_offering_version_id=$1 AND reservation.status='HELD' AND reservation.expires_at>current_timestamp AND reservation.starts_at<$3 AND $2<reservation.ends_at AND NOT EXISTS (SELECT 1 FROM appointment_committed_capacities committed WHERE committed.slot_reservation_id=reservation.id AND committed.status='ACTIVE')) capacity`, [versionId, startsAt, endsAt])).rows[0]; return Number(row?.used ?? '0'); }
  private async rules(configurationId: string): Promise<AvailabilityRule[]> { const result = await this.database.query<Record<string, unknown>>(`SELECT rule.id,rule.canonical_recurrence,rule.effective_from,rule.effective_to,item.kind,item.weekday,item.start_seconds,item.end_seconds FROM availability_rules rule JOIN availability_windows item ON item.availability_rule_id=rule.id WHERE rule.availability_configuration_id=$1 AND rule.status='ACTIVE' ORDER BY rule.id,item.kind,item.weekday,item.start_seconds`, [configurationId]); const values = new Map<string, AvailabilityRule>(); for (const row of result.rows) { const id=String(row.id); const rule=values.get(id) ?? { canonicalRecurrence:String(row.canonical_recurrence), effectiveFrom:new Date(String(row.effective_from)), effectiveTo:row.effective_to ? new Date(String(row.effective_to)) : null, windows:[] }; rule.windows.push({ kind:row.kind as 'WORKING' | 'BREAK', weekday:Number(row.weekday), startSeconds:Number(row.start_seconds), endSeconds:Number(row.end_seconds) }); values.set(id,rule); } return [...values.values()]; }
  private async exceptions(configurationId: string): Promise<AvailabilityException[]> { const result = await this.database.query<Record<string, unknown>>(`SELECT kind,derived_start_utc,derived_end_utc,status FROM availability_exceptions WHERE availability_configuration_id=$1`, [configurationId]); return result.rows.map((row) => ({ kind:row.kind as AvailabilityException['kind'], start:new Date(String(row.derived_start_utc)), end:new Date(String(row.derived_end_utc)), status:row.status as AvailabilityException['status'] })); }
  private async bookable(row: Record<string, unknown>): Promise<BookableService> { const configurationId = String(row.configuration_id); const doctorProfileId = row.doctor_profile_id ? String(row.doctor_profile_id) : null; const clinicId = row.clinic_id ? String(row.clinic_id) : null; if (!doctorProfileId && !clinicId) throw new Error('Public service provider context is missing.'); return { provider: doctorProfileId ? { kind: 'DOCTOR', doctorProfileId } : { kind: 'CLINIC', clinicId: clinicId! }, serviceOfferingId: String(row.offering_id), versionId: String(row.version_id), priceId: String(row.price_id), currency: String(row.currency), priceAmountMinor: BigInt(String(row.amount_minor)), bookingTenantId: doctorProfileId ? null : String(row.booking_tenant_id), timezone: String(row.provider_timezone), slotDurationSeconds: Number(row.slot_duration_seconds), durationSeconds: Number(row.slot_duration_seconds), bufferBeforeSeconds: Number(row.buffer_before_seconds), bufferAfterSeconds: Number(row.buffer_after_seconds), capacity: Number(row.capacity), bookingLeadSeconds: Number(row.booking_lead_time_seconds), bookingHorizonSeconds: Number(row.booking_horizon_seconds), holdSeconds: Number(row.hold_seconds), rules: await this.rules(configurationId), exceptions: await this.exceptions(configurationId) }; }
}

const bookableSelect = `SELECT offering.id AS offering_id,version.id AS version_id,price.id AS price_id,price.currency,price.amount_minor,configuration.id AS configuration_id,configuration.provider_timezone,configuration.slot_duration_seconds,configuration.buffer_before_seconds,configuration.buffer_after_seconds,configuration.capacity,configuration.booking_lead_time_seconds,configuration.booking_horizon_seconds,policy.hold_seconds,exposure.provider_doctor_profile_id AS doctor_profile_id,exposure.provider_clinic_id AS clinic_id,clinic.tenant_id AS booking_tenant_id FROM service_exposures exposure JOIN service_offerings offering ON offering.id=exposure.service_offering_id AND offering.status='ACTIVE' LEFT JOIN doctor_profiles doctor ON doctor.id=exposure.provider_doctor_profile_id LEFT JOIN clinics clinic ON clinic.id=exposure.provider_clinic_id LEFT JOIN tenants tenant ON tenant.id=clinic.tenant_id JOIN service_offering_versions version ON version.service_offering_id=offering.id AND version.status='ACTIVE' JOIN service_offering_prices price ON price.service_offering_version_id=version.id JOIN service_offering_version_reservation_policies policy ON policy.service_offering_version_id=version.id JOIN availability_configurations configuration ON configuration.service_offering_version_id=version.id AND configuration.status='ACTIVE' WHERE ((doctor.id IS NOT NULL AND doctor.status='ACTIVE' AND doctor.professional_verification_status='VERIFIED' AND ${approval('doctor.id', 'DOCTOR')}) OR (clinic.id IS NOT NULL AND clinic.status='ACTIVE' AND tenant.status='ACTIVE' AND ${approval('clinic.id', 'CLINIC')}))`;
function approval(id: string, kind: 'CLINIC' | 'DOCTOR') { const column = kind === 'CLINIC' ? 'clinic_id' : 'doctor_profile_id'; return `EXISTS (SELECT 1 FROM platform_public_discovery_approvals approval WHERE approval.subject_kind='${kind}' AND approval.${column}=${id} AND approval.status='PUBLISHED')`; }
function doctor(row: Record<string, unknown>): PublicDoctor { return { id:String(row.id), displayName:row.display_name === null ? null : String(row.display_name) }; }
function clinic(row: Record<string, unknown>): PublicClinic { return { id:String(row.id), displayName:String(row.display_name) }; }
function service(row: Record<string, unknown>): PublicService { const doctorProfileId=row.provider_doctor_profile_id ? String(row.provider_doctor_profile_id) : null; return { id:String(row.id), provider:doctorProfileId ? { kind:'DOCTOR',doctorProfileId } : { kind:'CLINIC',clinicId:String(row.provider_clinic_id) }, name:String(row.name), description:row.description === null ? null : String(row.description), currency:String(row.currency), amountMinor:String(row.amount_minor) }; }
